### ISSUE TITLE
Archive.zip Error 404 

### ISSUE THREAD

**Issue by teilala** [tanersener/react-native-ffmpeg#1]
[!] Error installing react-native-ffmpeg-min-gpl
[!] /usr/bin/curl -f -L -o /var/folders/nd/m3yr54xs3hs8k323wplvdsg80000gn/T/d20180922-13808-1swouxu/file.zip https://www.dropbox.com/s/atj0nh1jwkz9ssj/Archive.zip --create-dirs --netrc-optional

I Need your HELP

**Comment by tanersener** [comment]
Could you please update your `package.json` with `"react-native-ffmpeg": "^0.1.1",` dependency and try again after deleting existing `ios/Pods` directory?

Early beta versions had this Dropbox link for testing but it is not used anymore.

**Comment by teilala** [comment]
thank you it's work.

**Comment by tanersener** [comment]
Great 👍
