### ISSUE TITLE
UI freezes while executing ffmpeg command

### ISSUE THREAD

**Issue by oleh-mryhlod** [tanersener/react-native-ffmpeg#10]
**Description**
UI freezes or totally blocks while executing FFmpeg command using RNFFmpeg.execute() on Android and iOS

**Expected behavior**
Calling RNFFmpeg.execute() must not block UI thread

**Current behavior**
Calling RNFFmpeg.execute() blocks UI thread

**Screenshots**
https://github.com/oleh-mryhlod/test-rn-ffmpeg-async/raw/master/rn-ffmpeg-test.gif

**Environment**
    "react": "16.6.0-alpha.8af6728",
    "react-native": "0.57.4",
    "react-native-ffmpeg": "^0.2.0"

**Reproducing Demo**
https://github.com/oleh-mryhlod/test-rn-ffmpeg-async

**Other**
Maybe its possinble to just run ffmpeg command in another thread
e.g in java:
```java
new Thread(new Runnable() {
      @Override
      public void run() {
        // ... existing code ...
      }
}).start();
```

**Comment by tanersener** [comment]
You are right about the `Android`, but `IOS` is already executed inside `dispatch_async()`. Let me make a few tests to understand the actual cause.

**Comment by oleh-mryhlod** [comment]
Hi,
but on `iOS` it runs in main queue
changing to `dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)` fixes the lag for me

**Comment by tanersener** [comment]
You are right, it should be `global queue` instead of `main queue`. 

I updated both `Android` and `IOS` implementations and published a new release `v0.2.1`. Could you please test it with your test app?

**Comment by oleh-mryhlod** [comment]
Hi,
I've just tested v0.2.1 and now async tasks really work and don't block ui
Thanks a lot for the quick fix and release!)

**Comment by tanersener** [comment]
I thank you for reporting this issue 👍
