### ISSUE TITLE
Building the ios version failed- Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by TopCoder1119** [tanersener/react-native-ffmpeg#101]
**Current behavior**
When I tried to build the ios version, I am getting following error

**Screenshots**
![screen](https://user-images.githubusercontent.com/28654007/63343561-6df86d00-c378-11e9-9084-ed55cea4179a.png)

**Environment**
 - React Native Environment Info
React Native version: 0.57.8
Xcode version: 10.3
React Native ffmpeg version: 0.35

Could you please let me know how I can resolve it?

Thanks

**Comment by tanersener** [comment]
These errors show that Xcode can not find some of the libraries. Either they are not installed using `pod install` or your search paths does not include them.

Most of the time, installing `react-native-ffmpeg` using instructions in [README](https://github.com/tanersener/react-native-ffmpeg#2-installation) does not require any modifications. Can you please give more detail about how you install `react-native-ffmpeg`? Additionally, can you provide steps to reproduce this issue locally?

**Comment by TopCoder1119** [comment]
I added the below link to pod file and run `pod install`
`pod 'react-native-ffmpeg/full-gpl-lts', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec'`

**Comment by tanersener** [comment]
Unfortunately, I can't reproduce this issue. I'm using the following steps to create a new project, update versions and build the project. It works as expected for me.

Do you have the same issue when you create a new project?

```
react-native init new_test
cd new_test
vi package.json
yarn install
cd ios
vi Podfile
pod install
```

**Comment by TopCoder1119** [comment]
Not tested it with the new project, but I tried to remove and install for several times.

I will try to do it with the new project.

**Comment by TopCoder1119** [comment]
OK, I found the solution. thank you for your help.

**Comment by tanersener** [comment]
@TopCoder1119 what is the solution?

**Comment by PradeepLinkites** [comment]
> OK, I found the solution. thank you for your help.

Hi TopCoder119 have you found the solution of this package? I am facing same issue on this package when adding from pod. Can you please give me any solution to resolve it?

**Comment by TopCoder1119** [comment]
That is because the pod-appname.debug.xcconfig/release.xcconfig file did not imported properly into xcode.

That was a problem for me and I resolved it by generating them newly.
