### ISSUE TITLE
Question: how to use the standard or default font 

### ISSUE THREAD

**Issue by idoor88** [tanersener/react-native-ffmpeg#103]
**Description**
When I use this call:
RNFFmpeg.setFontDirectory(['/system/fonts/']); 
to set the system default fonts, I am assuming arial is the default font, but when I use this command:
-vf "drawtext=text='Title1 Goood Friend':enable='between(t,0,6)':fontsize=80:fontcolor=white:fontfile='arial.ttf'

I got error message: no font arial found.

**Expected behavior**
My output video can be created successfully with Arial font.

**Current behavior**
No output video created with error message: no font arial found.

**Environment**
 - React Native Environment Info
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 301.58 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.4.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.2, 28.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.1 AI-173.4907809
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.8.6 
    react-native: ^0.60.0 => 0.60.0 
  npmGlobalPackages:
    react-native-asset: 2.0.0
    react-native-cli: 2.0.1
    react-native-cn-richtext-editor: 1.0.33
    react-native-git-upgrade: 0.2.7

**Comment by tanersener** [comment]
Can you try using full path in `fontfile` declaration, `fontfile='/system/fonts/arial.ttf'`?

If it does not work, another option is to use `font` option, `font='Arial'`.

**Comment by idoor88** [comment]
Thanks for your response, if I call RNFFmpeg.setFontDirectory(['/system/fonts/']); it will not work, after I changed to call RNFFmpeg.setFontDirectory('/system/fonts/');
and use  fontsize=50:fontcolor=white:fontfile='/system/fonts/arial.ttf', or use font='Arial', I got it working, but I got this log message:

Using "/system/fonts/DroidSans.ttf"

This message confused me, since I set the fontfile='/system/fonts/arial.ttf', why it said using "/system/fonts/DroidSans.ttf"?

Thanks

**Comment by tanersener** [comment]
Do you really have `/system/fonts/arial.ttf` on your devices? My Android test devices don't have it.

**Comment by idoor88** [comment]
How can I tell what fonts I have on my device?

**Comment by tanersener** [comment]
Can you try using `adb`?

```
adb shell
ls -l /system/fonts
```

**Comment by idoor88** [comment]
You are right, I can list all ttf files, and the Arial font is not there

**Comment by tanersener** [comment]
That's the reason then. Can you try using an existing .ttf file?

**Comment by idoor88** [comment]
Yes, it works, thank you very much!
