### ISSUE TITLE
ios build failed

### ISSUE THREAD

**Issue by AlexSeoven** [tanersener/react-native-ffmpeg#11]
**Description**
after pod install and build i have an error "mobileffmpeg/MediaInformation.h file not found"

my Podfile
platform :ios, '9.0'

install! 'cocoapods', :deterministic_uuids => false
target 'cfilming' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'jschelpers',
    'cxxreact',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTWebSocket', # needed for debugging
  ]

  # To use CocoaPods with React Native, you need to add this specific Yoga spec as well
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  # Third party deps
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'

  pod 'react-native-ffmpeg-full-gpl', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg-full-gpl.podspec'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

end

# do not allow Cocoapods to manage React dependencies
post_install do |installer|
    installer.pods_project.targets.each do |target|
      targets_to_ignore = %w(React yoga)
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
    end
end

Can you help me?
I can't build ios with react-native-ffmpeg with any podfile from test projects

**Comment by tanersener** [comment]
Could you please provide react-native environment info and build output?

**Comment by AlexSeoven** [comment]
sorry, i resolved the issue by removing ios dir, next react-native eject and pod install again

**Comment by ami9000** [comment]
I faced the same "mobileffmpeg/MediaInformation.h file not found" error. 

For me, doing 'pod update [ffmpeg package]' after 'pod install' added all the missing files (turns out there's more missing than just MediaInformation.h).

For those that didn't want to remove entire ios dir... 😁
