### ISSUE TITLE
resource android:attr/dialogCornerRadius not found when packaging

### ISSUE THREAD

**Issue by luandro** [tanersener/react-native-ffmpeg#110]
**Description**

Using v0.2.1 for compatibility with lower end devices. When developing everything works fine; but when packaging I get this error:
```
* What went wrong:
Execution failed for task ':react-native-ffmpeg:verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /home/luandro/Dev/huiom/node_modules/react-native-ffmpeg/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /home/luandro/Dev/huiom/node_modules/react-native-ffmpeg/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /home/luandro/Dev/huiom/node_modules/react-native-ffmpeg/android/build/intermediates/res/merged/release/values/values.xml:2753: error: resource android:attr/fontVariationSettings not found.
  /home/luandro/Dev/huiom/node_modules/react-native-ffmpeg/android/build/intermediates/res/merged/release/values/values.xml:2754: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
```

**Environment**
 - React Native 0.61.2
- react-native-ffmpeg 0.2.1

**Comment by tanersener** [comment]
This is an `AndroidX` issue but `react-native-ffmpeg` shouldn't be causing this. Do you have the same error when your temporarily disable `react-native-ffmpeg`?

**Comment by luandro** [comment]
I've removed `react-native-ffmpeg` from my project, and the error has gone away.

**Comment by tanersener** [comment]
Well, `v0.2.1` is pretty old and not tested against React Native `0.6x`. It may have an issue about `AndroidX`, I'm not % 100 sure.

You can support the same range of devices by using an `LTS` release in `v0.3.6`. Can you try installing it using instructions in [2.4 LTS Release](https://github.com/tanersener/react-native-ffmpeg#24-lts-release) and [2.3.1 Android](https://github.com/tanersener/react-native-ffmpeg#231-android). I'll help you if it fails somewhere.

**Comment by tanersener** [comment]
@luandro Any update on this?
