### ISSUE TITLE
option ignore_loop not found

### ISSUE THREAD

**Issue by audiobeing** [tanersener/react-native-ffmpeg#111]
I am using ffmpeg to convert gifs to videos. On the ios and android emulators everything works fine. When I run the app on my iphone I get the following error: 
2019-10-12 22:35:27.135 [info][tid:com.facebook.react.JavaScript] Option ignore_loop not found.
2019-10-12 22:35:27.135475-0400 soundmemes[1707:593973] Option ignore_loop not found.

**Comment by tanersener** [comment]
Can you share your command, logs, react-native package/version details and react-native environment info?

**Comment by audiobeing** [comment]
Thank you for the response. There was an issue with the type of file that was being uploaded to work with. In the end, it was not a gif but an jpg. When this was fixed the issue was resolved.
