### ISSUE TITLE
Unable to locate output file after execute command 

### ISSUE THREAD

**Issue by issamabdelkrim** [tanersener/react-native-ffmpeg#112]
Hello every one , i have a chat application with send video in react native 
i need to change the scale of video after recording 
i tried this code .
  let outputpath ='file://' + RNFS.DocumentDirectoryPath + '/my.mp4' ;
                                   RNFFmpeg.executeWithArguments(["-i", res.path , "-vf"," scale=480:848 ", outputpath])
                                           .then(result =>{

})
the conversion is successed but i can't locate the output file . and when i make the file outputpath in call of WS it  makes network error 
If one can solve me this problem 
thanks to everyone

**Comment by tanersener** [comment]
Could you please provide logs of your execution?

**Comment by issamabdelkrim** [comment]
the log print this message 
FFmpeg process exited with rc 0

**Comment by issamabdelkrim** [comment]
here all logs 
ffmpeg version v4.2-dev-1824
3index.js:70 
index.js:70  Copyright (c) 2000-2019 the FFmpeg developers
3index.js:70 
index.js:70 

3index.js:70 
index.js:70   built with Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)

Api.js:36 Api.call :  api/config/new
3index.js:70 
index.js:70   configuration: --cross-prefix=aarch64-linux-android- --sysroot=/files/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot --prefix=/home/taner/Projects/mobile-ffmpeg/prebuilt/android-arm64/ffmpeg --pkg-config=/usr/bin/pkg-config --enable-version3 --arch=aarch64 --cpu=armv8-a --cc=aarch64-linux-android21-clang --cxx=aarch64-linux-android21-clang++ --target-os=android --enable-neon --enable-asm --enable-inline-asm --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --enable-shared --disable-v4l2-m2m --disable-outdev=v4l2 --disable-outdev=fbdev --disable-indev=v4l2 --disable-indev=fbdev --enable-small --disable-openssl --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-static --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --disable-videotoolbox --disable-audiotoolbox --disable-appkit --disable-alsa --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --enable-gmp --enable-gnutls --enable-iconv --disable-sdl2 --enable-zlib --enable-mediacodec

3index.js:70 
index.js:70   libavutil      56. 30.100 / 56. 30.100

3index.js:70 
index.js:70   libavcodec     58. 53.101 / 58. 53.101

3index.js:70 
index.js:70   libavformat    58. 28.101 / 58. 28.101

3index.js:70 
index.js:70   libavdevice    58.  7.100 / 58.  7.100

3index.js:70 
index.js:70   libavfilter     7. 55.100 /  7. 55.100

3index.js:70 
index.js:70   libswscale      5.  4.101 /  5.  4.101

3index.js:70 
index.js:70   libswresample   3.  4.100 /  3.  4.100

3index.js:70 
index.js:70 Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/DCIM/Camera/VID_20191019_234459.mp4':

3index.js:70 
index.js:70   Metadata:

3index.js:70 
index.js:70     major_brand     : 
3index.js:70 
index.js:70 mp42
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     minor_version   : 
3index.js:70 
index.js:70 0
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     compatible_brands: 
3index.js:70 
index.js:70 isommp42
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     creation_time   : 
3index.js:70 
index.js:70 2019-10-19T22:45:06.000000Z
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     com.android.version: 
3index.js:70 
index.js:70 8.0.0
3index.js:70 
index.js:70 

3index.js:70 
index.js:70   Duration: 
3index.js:70 
index.js:70 00:00:06.98
3index.js:70 
index.js:70 , start: 
3index.js:70 
index.js:70 0.000000
3index.js:70 
index.js:70 , bitrate: 
3index.js:70 
index.js:70 20770 kb/s
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     Stream #0:0
3index.js:70 
index.js:70 (eng)
3index.js:70 
index.js:70 : Video: h264 (avc1 / 0x31637661), yuvj420p(pc, smpte170m), 1920x1080, 21203 kb/s
3index.js:70 
index.js:70 , SAR 1:1 DAR 16:9
3index.js:70 
index.js:70 , 
3index.js:70 
index.js:70 29.61 fps, 
3index.js:70 
index.js:70 29.75 tbr, 
3index.js:70 
index.js:70 90k tbn, 
3index.js:70 
index.js:70 180k tbc
3index.js:70 
index.js:70  (default)
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     Metadata:

3index.js:70 
index.js:70       rotate          : 
3index.js:70 
index.js:70 90
3index.js:70 
index.js:70 

3index.js:70 
index.js:70       creation_time   : 
3index.js:70 
index.js:70 2019-10-19T22:45:06.000000Z
3index.js:70 
index.js:70 

3index.js:70 
index.js:70       handler_name    : 
3index.js:70 
index.js:70 VideoHandle
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     Side data:

3index.js:70 
index.js:70       
3index.js:70 
index.js:70 displaymatrix: rotation of -90.00 degrees
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     Stream #0:1
3index.js:70 
index.js:70 (eng)
3index.js:70 
index.js:70 : Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 96 kb/s
3index.js:70 
index.js:70  (default)
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     Metadata:

3index.js:70 
index.js:70       creation_time   : 
3index.js:70 
index.js:70 2019-10-19T22:45:06.000000Z
3index.js:70 
index.js:70 

3index.js:70 
index.js:70       handler_name    : 
3index.js:70 
index.js:70 SoundHandle
3index.js:70 
index.js:70 

3index.js:70 
index.js:70 Stream mapping:

3index.js:70 
index.js:70   Stream #0:0 -> #0:0
3index.js:70 
index.js:70  (h264 (native) -> mpeg4 (native))
3index.js:70 
index.js:70 

3index.js:70 
index.js:70   Stream #0:1 -> #0:1
3index.js:70 
index.js:70  (aac (native) -> aac (native))
3index.js:70 
index.js:70 

3index.js:70 
index.js:70 Press [q] to stop, [?] for help

index.js:70 
index.js:70 [swscaler @ 0x7e693c9000] 
index.js:70 
index.js:70 deprecated pixel format used, make sure you did set range correctly

3index.js:70 
index.js:70 Output #0, mp4, to '/storage/emulated/0/Pictures/video3.mp4':

3index.js:70 
index.js:70   Metadata:

3index.js:70 
index.js:70     major_brand     : 
3index.js:70 
index.js:70 mp42
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     minor_version   : 
3index.js:70 
index.js:70 0
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     compatible_brands: 
3index.js:70 
index.js:70 isommp42
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     com.android.version: 
3index.js:70 
index.js:70 8.0.0
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     encoder         : 
3index.js:70 
index.js:70 Lavf58.28.101
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     Stream #0:0
3index.js:70 
index.js:70 (eng)
3index.js:70 
index.js:70 : Video: mpeg4 (mp4v / 0x7634706D), yuv420p, 480x848 [SAR 159:160 DAR 9:16], q=2-31, 200 kb/s
3index.js:70 
index.js:70 , 
3index.js:70 
index.js:70 29.75 fps, 
3index.js:70 
index.js:70 15232 tbn, 
3index.js:70 
index.js:70 29.75 tbc
3index.js:70 
index.js:70  (default)
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     Metadata:

3index.js:70 
index.js:70       encoder         : 
3index.js:70 
index.js:70 Lavc58.53.101 mpeg4
3index.js:70 
index.js:70 

3index.js:70 
index.js:70       creation_time   : 
3index.js:70 
index.js:70 2019-10-19T22:45:06.000000Z
3index.js:70 
index.js:70 

3index.js:70 
index.js:70       handler_name    : 
3index.js:70 
index.js:70 VideoHandle
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     Side data:

3index.js:70 
index.js:70       
3index.js:70 
index.js:70 cpb: 
3index.js:70 
index.js:70 bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
3index.js:70 
index.js:70 

3index.js:70 
index.js:70       
3index.js:70 
index.js:70 displaymatrix: rotation of -0.00 degrees
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     Stream #0:1
3index.js:70 
index.js:70 (eng)
3index.js:70 
index.js:70 : Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s
3index.js:70 
index.js:70  (default)
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     Metadata:

3index.js:70 
index.js:70       creation_time   : 
3index.js:70 
index.js:70 2019-10-19T22:45:06.000000Z
3index.js:70 
index.js:70 

3index.js:70 
index.js:70       handler_name    : 
3index.js:70 
index.js:70 SoundHandle
3index.js:70 
index.js:70 

3index.js:70 
index.js:70       encoder         : 
3index.js:70 
index.js:70 Lavc58.53.101 aac
3index.js:70 
index.js:70 

3index.js:70 
index.js:70 frame=    3 fps=0.0 q=2.0 size=       0kB time=00:00:01.00 bitrate=   0.4kbits/s dup=1 drop=0 speed= 1.4x    
frame=    6 fps=4.7 q=2.0 size=       0kB time=00:00:01.00 bitrate=   0.4kbits/s dup=1 drop=0 speed=0.79x    
3index.js:70 
index.js:70 frame=   11 fps=5.9 q=3.6 size=       0kB time=00:00:01.00 bitrate=   0.4kbits/s dup=1 drop=0 speed=0.535x    
3index.js:70 
index.js:70 frame=   15 fps=6.3 q=3.0 size=       0kB time=00:00:01.00 bitrate=   0.4kbits/s dup=1 drop=0 speed=0.421x    
3index.js:70 
index.js:70 frame=   21 fps=7.2 q=3.7 size=       0kB time=00:00:01.00 bitrate=   0.4kbits/s dup=1 drop=0 speed=0.342x    
3index.js:70 
index.js:70 frame=   25 fps=7.3 q=3.2 size=       0kB time=00:00:01.38 bitrate=   0.3kbits/s dup=1 drop=0 speed=0.404x    
3index.js:70 
index.js:70 frame=   30 fps=7.6 q=3.5 size=       0kB time=00:00:02.00 bitrate=   0.2kbits/s dup=1 drop=0 speed=0.506x    
3index.js:70 
index.js:70 frame=   36 fps=8.0 q=3.3 size=       0kB time=00:00:02.00 bitrate=   0.2kbits/s dup=1 drop=0 speed=0.443x    
3index.js:70 
index.js:70 frame=   42 fps=8.2 q=3.9 size=       0kB time=00:00:02.00 bitrate=   0.2kbits/s dup=1 drop=0 speed=0.393x    
Api.js:36 Api.call :  api/timeline
3index.js:70 
index.js:70 frame=   48 fps=8.5 q=3.3 size=       0kB time=00:00:02.00 bitrate=   0.2kbits/s dup=1 drop=0 speed=0.355x    
3index.js:70 
index.js:70 frame=   54 fps=8.7 q=3.8 size=       0kB time=00:00:02.00 bitrate=   0.2kbits/s dup=1 drop=0 speed=0.323x    
3index.js:70 
index.js:70 frame=   59 fps=8.7 q=3.2 size=       0kB time=00:00:03.00 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.444x  
frame=   70 fps=8.8 q=3.2 size=       0kB time=00:00:03.00 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.378x    
3index.js:70 
index.js:70 frame=   75 fps=8.7 q=3.4 size=       0kB time=00:00:03.00 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.35x    
3index.js:70 
index.js:70 frame=   80 fps=8.8 q=3.4 size=       0kB time=00:00:03.00 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.329x    
3index.js:70 
index.js:70 frame=   85 fps=8.8 q=3.4 size=       0kB time=00:00:03.00 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.31x    
3index.js:70 
index.js:70 frame=   89 fps=8.7 q=4.0 size=       0kB time=00:00:04.01 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.393x    
3index.js:70 
index.js:70 frame=   93 fps=8.7 q=3.5 size=       0kB time=00:00:04.01 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.374x    
3index.js:70 
index.js:70 frame=   98 fps=8.7 q=2.6 size=       0kB time=00:00:04.01 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.356x    
3index.js:70 
index.js:70 frame=  103 fps=8.7 q=3.6 size=       0kB time=00:00:04.01 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.339x    
3index.js:70 
index.js:70 frame=  108 fps=8.7 q=3.5 size=       0kB time=00:00:04.01 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.323x    
3index.js:70 
index.js:70 frame=  113 fps=8.7 q=3.9 size=       0kB time=00:00:04.01 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.308x    
3index.js:70 
index.js:70 frame=  117 fps=8.6 q=3.4 size=       0kB time=00:00:05.01 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.37x    
3index.js:70 
index.js:70 frame=  123 fps=8.7 q=3.4 size=       0kB time=00:00:05.01 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.354x    
3index.js:70 
index.js:70 frame=  129 fps=8.8 q=3.4 size=       0kB time=00:00:05.01 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.341x    
3index.js:70 
index.js:70 frame=  135 fps=8.8 q=3.4 size=       0kB time=00:00:05.01 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.327x    
3index.js:70 
index.js:70 frame=  141 fps=8.9 q=3.5 size=       0kB time=00:00:05.01 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.315x    
3index.js:70 
index.js:70 frame=  145 fps=8.8 q=3.5 size=     256kB time=00:00:05.03 bitrate= 416.6kbits/s dup=1 drop=0 speed=0.306x    
3index.js:70 
index.js:70 frame=  150 fps=8.8 q=4.0 size=     256kB time=00:00:06.01 bitrate= 348.7kbits/s dup=1 drop=0 speed=0.355x    
3index.js:70 
index.js:70 frame=  156 fps=8.9 q=3.5 size=     256kB time=00:00:06.01 bitrate= 348.7kbits/s dup=1 drop=0 speed=0.344x    
3index.js:70 
index.js:70 frame=  161 fps=8.9 q=4.1 size=     256kB time=00:00:06.01 bitrate= 348.7kbits/s dup=1 drop=0 speed=0.333x    
3index.js:70 
index.js:70 frame=  167 fps=9.0 q=3.3 size=     256kB time=00:00:06.01 bitrate= 348.7kbits/s dup=1 drop=0 speed=0.323x    
3index.js:70 
index.js:70 frame=  173 fps=9.0 q=4.2 size=     256kB time=00:00:06.01 bitrate= 348.7kbits/s dup=1 drop=0 speed=0.313x    
3index.js:70 
index.js:70 frame=  178 fps=9.0 q=3.5 size=     256kB time=00:00:06.01 bitrate= 348.7kbits/s dup=1 drop=0 speed=0.305x    
3index.js:70 
index.js:70 frame=  183 fps=9.1 q=3.6 size=     256kB time=00:00:06.11 bitrate= 342.9kbits/s dup=1 drop=0 speed=0.303x    
3index.js:70 
index.js:70 frame=  188 fps=9.0 q=3.9 size=     256kB time=00:00:06.93 bitrate= 302.5kbits/s dup=1 drop=0 speed=0.334x    
3index.js:70 
index.js:70 frame=  194 fps=9.1 q=2.8 size=     256kB time=00:00:06.93 bitrate= 302.5kbits/s dup=1 drop=0 speed=0.326x    
7index.js:70 
index.js:70 frame=  194 fps=9.1 q=2.8 Lsize=     353kB time=00:00:06.97 bitrate= 414.6kbits/s dup=1 drop=0 speed=0.326x    

3index.js:70 
index.js:70 video:235kB audio:112kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 
3index.js:70 
index.js:70 2.000124%
3index.js:70 
index.js:70 

index.js:70 
index.js:70 [aac @ 0x7e743ed400] 
index.js:70 
ContactPage.js:1975 FFmpeg process exited with rc 0
index.js:70 Qavg: 666.715

**Comment by tanersener** [comment]
That only shows the return code, which is not enough to see the details of your execution. 

Do you have anything printed on console? If not, what is the output printed by the following block?

```
RNFFmpeg.getLastCommandOutput().then(result => {
    console.log("Last command output: " + result.lastCommandOutput);
});
```

**Comment by issamabdelkrim** [comment]
here the result of add your code after execute command 
Last command output: ffmpeg version v4.2-dev-1824 Copyright (c) 2000-2019 the FFmpeg developers
  built with Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)
  configuration: --cross-prefix=aarch64-linux-android- --sysroot=/files/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot --prefix=/home/taner/Projects/mobile-ffmpeg/prebuilt/android-arm64/ffmpeg --pkg-config=/usr/bin/pkg-config --enable-version3 --arch=aarch64 --cpu=armv8-a --cc=aarch64-linux-android21-clang --cxx=aarch64-linux-android21-clang++ --target-os=android --enable-neon --enable-asm --enable-inline-asm --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --enable-shared --disable-v4l2-m2m --disable-outdev=v4l2 --disable-outdev=fbdev --disable-indev=v4l2 --disable-indev=fbdev --enable-small --disable-openssl --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-static --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --disable-videotoolbox --disable-audiotoolbox --disable-appkit --disable-alsa --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --enable-gmp --enable-gnutls --enable-iconv --disable-sdl2 --enable-zlib --enable-mediacodec
  libavutil      56. 30.100 / 56. 30.100
  libavcodec     58. 53.101 / 58. 53.101
  libavformat    58. 28.101 / 58. 28.101
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 55.100 /  7. 55.100
  libswscale      5.  4.101 /  5.  4.101
  libswresample   3.  4.100 /  3.  4.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/DCIM/Camera/VID_20191019_234850.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2019-10-19T22:48:54.000000Z
    com.android.version: 8.0.0
  Duration: 00:00:03.50, start: 0.000000, bitrate: 20482 kb/s
    Stream #0:0(eng): Video: h264 (avc1 / 0x31637661), yuvj420p(pc, smpte170m), 1920x1080, 21407 kb/s, SAR 1:1 DAR 16:9, 29.47 fps, 29.75 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      rotate          : 90
      creation_time   : 2019-10-19T22:48:54.000000Z
      handler_name    : VideoHandle
    Side data:
      displaymatrix: rotation of -90.00 degrees
    Stream #0:1(eng): Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 97 kb/s (default)
    Metadata:
      creation_time   : 2019-10-19T22:48:54.000000Z
      handler_name    : SoundHandle
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mpeg4 (native))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
[swscaler @ 0x7e675c9000] deprecated pixel format used, make sure you did set range correctly
Output #0, mp4, to '/storage/emulated/0/Pictures/video4.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    com.android.version: 8.0.0
    encoder         : Lavf58.28.101
    Stream #0:0(eng): Video: mpeg4 (mp4v / 0x7634706D), yuv420p, 480x848 [SAR 159:160 DAR 9:16], q=2-31, 200 kb/s, 29.75 fps, 15232 tbn, 29.75 tbc (default)
    Metadata:
      encoder         : Lavc58.53.101 mpeg4
      creation_time   : 2019-10-19T22:48:54.000000Z
      handler_name    : VideoHandle
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
      displaymatrix: rotation of -0.00 degrees
    Stream #0:1(eng): Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2019-10-19T22:48:54.000000Z
      handler_name    : SoundHandle
      encoder         : Lavc58.53.101 aac
frame=    4 fps=0.0 q=2.0 size=       0kB time=00:00:01.00 bitrate=   0.4kbits/s dup=1 drop=0 speed=1.47x    
frame=    9 fps=7.6 q=3.4 size=       0kB time=00:00:01.00 bitrate=   0.4kbits/s dup=1 drop=0 speed=0.848x    
frame=   15 fps=8.7 q=3.0 size=       0kB time=00:00:01.00 bitrate=   0.4kbits/s dup=1 drop=0 speed=0.58x    
frame=   21 fps=9.2 q=3.1 size=       0kB time=00:00:01.00 bitrate=   0.4kbits/s dup=1 drop=0 speed=0.438x    
frame=   25 fps=9.0 q=3.4 size=       0kB time=00:00:01.47 bitrate=   0.2kbits/s dup=1 drop=0 speed=0.527x    
frame=   31 fps=9.4 q=3.3 size=       0kB time=00:00:02.00 bitrate=   0.2kbits/s dup=1 drop=0 speed=0.605x    
frame=   37 fps=9.6 q=3.1 size=       0kB time=00:00:02.00 bitrate=   0.2kbits/s dup=1 drop=0 speed=0.52x    
frame=   43 fps=9.8 q=3.6 size=       0kB time=00:00:02.00 bitrate=   0.2kbits/s dup=1 drop=0 speed=0.456x    
frame=   49 fps=9.9 q=3.5 size=       0kB time=00:00:02.00 bitrate=   0.2kbits/s dup=1 drop=0 speed=0.406x    
frame=   55 fps= 10 q=3.4 size=       0kB time=00:00:02.00 bitrate=   0.2kbits/s dup=1 drop=0 speed=0.365x    
frame=   60 fps=9.9 q=3.1 size=       0kB time=00:00:03.00 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.497x    
frame=   66 fps= 10 q=4.1 size=       0kB time=00:00:03.00 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.457x    
frame=   72 fps= 10 q=3.4 size=       0kB time=00:00:03.00 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.423x    
frame=   78 fps= 10 q=3.7 size=       0kB time=00:00:03.00 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.394x    
frame=   83 fps= 10 q=3.3 size=       0kB time=00:00:03.02 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.371x    
frame=   89 fps= 10 q=4.4 size=       0kB time=00:00:03.45 bitrate=   0.1kbits/s dup=1 drop=0 speed=0.397x    
frame=   91 fps= 10 q=4.0 Lsize=     187kB time=00:00:03.49 bitrate= 436.7kbits/s dup=1 drop=0 speed=0.389x    
video:126kB audio:56kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.205682%
[aac @ 0x7e7339a200] Qavg: 1119.751

**Comment by tanersener** [comment]
It looks like your output file path is `/storage/emulated/0/Pictures/video3.mp4`. Do you have this file on your device?

**Comment by issamabdelkrim** [comment]
non i don't have this file after execute command i didn't locate the file

**Comment by tanersener** [comment]
On your last log it is `/storage/emulated/0/Pictures/video4.mp4`. Why it is changing on each run? 

Also, according to your post your output file should end with `my.mp4`. Do you execute another command?

**Comment by issamabdelkrim** [comment]
no just i change the file name because when i keep if the same name it show error cannot overwrite file

**Comment by tanersener** [comment]
Can you show me a log/screenshot/something which shows output file does not exist?

Btw, you can use `-y` option to overwrite an existing file.

**Comment by issamabdelkrim** [comment]
yes herre the last video in my phone . it didn't show the file 
![Screenshot_20191020-000118](https://user-images.githubusercontent.com/11806926/67152403-ed4ce300-f2cc-11e9-9184-7b009d52c327.jpg)

**Comment by issamabdelkrim** [comment]
you can please print me your code that you used

**Comment by tanersener** [comment]
According to your logs, `VID_20191019_....mp4`
 files are located under the `/storage/emulated/0/DCIM/Camera/` folder.

Contrarily, `video..mp4` files are located under the `/storage/emulated/0/Pictures/` folder, which is different than `/storage/emulated/0/DCIM/Camera/`. How can your screenshot show these two directories at the same time?

Can you use `adb` to list files under the `Pictures` by running `adb shell 'ls /storage/emulated/0/Pictures/'` in your terminal?

**Comment by issamabdelkrim** [comment]
Here i locate it i make test now with videos1 , videos2 but why  when i send it to the server i have network error ? i when i go to pictures directory it didn't show the file ? 
![Capture d’écran 2019-10-20 à 12 24 37 AM](https://user-images.githubusercontent.com/11806926/67152528-0014e700-f2d0-11e9-89a0-f4dc5d89cc5b.png)
Picture directory with Android file transfer here the screenshot
![Capture d’écran 2019-10-20 à 12 23 16 AM](https://user-images.githubusercontent.com/11806926/67152539-508c4480-f2d0-11e9-8b89-146edc298e17.png)

**Comment by tanersener** [comment]
I don't know, maybe `Pictures` folder is configured to show only images.

Does your network error have any logs or screenshots?

**Comment by issamabdelkrim** [comment]
![Capture d’écran 2019-10-20 à 12 37 42 AM](https://user-images.githubusercontent.com/11806926/67152606-d5c42900-f2d1-11e9-8485-6da654d5b614.png)

**Comment by tanersener** [comment]
That log does not include any details. Did you check Android `logcat`?

**Comment by issamabdelkrim** [comment]
the logcat show me this error
10-20 00:43:10.307   891  1066 W JankService: processEntry, not beta version or commercial log off
10-20 00:43:10.348 10678 11752 E unknown:ReactNative: Could not retrieve file for contentUri /storage/emulated/0/Pictures/video7.mp4
10-20 00:43:10.348 10678 11752 E unknown:ReactNative: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference

**Comment by issamabdelkrim** [comment]
i resolve the problem 
when you upload the uri file you need ton add file:// in android 
@tanersener  really thanks you

**Comment by tanersener** [comment]
Great 👍

**Comment by Balajisivakumar92** [comment]
> 
> 
> i resolve the problem
> when you upload the uri file you need ton add file:// in android
> @tanersener really thanks you

Hi @issamabdelkrim 
I am struggling with the same problem, can give more details, how you solved this problem?
