### ISSUE TITLE
Android compile issue

### ISSUE THREAD

**Issue by lirazhad** [tanersener/react-native-ffmpeg#115]
**Description**
Could not find com.arthenica:mobile-ffmpeg-<package name>:4.2.2.

**Comment by tanersener** [comment]
Do you have `reactNativeFFmpegPackage` defined in your `build.gradle`?

**Comment by lirazhad** [comment]
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 24
        compileSdkVersion = 28
        targetSdkVersion = 28
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.2")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

ext {
    reactNativeFFmpegPackage = "kix"
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

this is my build.gradle, i defined reactNativeFFmpegPackage in ext

**Comment by tanersener** [comment]
What is `kix`? 
You need to assign a valid `react-native-ffmpeg` package name to `reactNativeFFmpegPackage`, like `min`, `min-gpl`, `full`, ...

**Comment by lirazhad** [comment]
in the doc it say to enter the package name there

**Comment by tanersener** [comment]
I think, its name explains what is it for: `reactNativeFFmpegPackage`. Anyway, you don't need to define `reactNativeFFmpegPackage` in your `build.gradle`. It is only needed if you want to use one of the `react-native-ffmpeg` packages. Your issue will be resolved if you delete it.

**Comment by lirazhad** [comment]
ok thank you.
