### ISSUE TITLE
Nonfatal error when building on iOS

### ISSUE THREAD

**Issue by mifi** [tanersener/react-native-ffmpeg#118]
**Description**
I followed setup instructions and added to Podfile:
`pod 'react-native-ffmpeg', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec'`

When running `react-native run-ios --device` I get this error:
```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-ffmpeg (to unlink run: "react-native unlink react-native-ffmpeg")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
```

**NOTE: It builds and runs successfully but I'm thinking this error should not be here.**

If I run (as suggested) `react-native unlink react-native-ffmpeg`, it automatically removes the line I added to Podfile, but if I try to run now, I get a runtime error in the app `invariant violation native module cannot be null`

**Expected behavior**
No error

**Current behavior**
Error

**Environment**
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 675.04 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.11.1 - ~/tools/node-v12.11.1-darwin-x64/bin/node
    Yarn: 1.19.1 - ~/tools/node-v12.11.1-darwin-x64/bin/yarn
    npm: 6.13.0 - ~/tools/node-v12.11.1-darwin-x64/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 16, 26, 28
      Build Tools: 26.0.3, 28.0.2, 28.0.3
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5314842
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native: 0.61.5
```

By the way... awesome module!!

**Comment by tanersener** [comment]
Which `react-native` version do you use in your  `package.json`? It is newer than `0.60`?

**Comment by mifi** [comment]
react-native: 0.61.5 => 0.61.5

**Comment by mifi** [comment]
I just started a fresh rn project with the newest rn version and added react-native-ffmpeg to test it

**Comment by tanersener** [comment]
It is not easy to document version specific differences. On React Native > 0.60:

If you use the default package on `iOS`, you don't need to add the following line to your `Podfile`.

`
pod 'react-native-ffmpeg', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec'
`

However, if you use a non-default package on `iOS`, then you need to add the following line to your `Podfile`.

`
pod 'react-native-ffmpeg/<package name>', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec'
`

**Comment by mifi** [comment]
If I didn't add the line to Podfile I got a different error in a redbox when running. `invariant violation native module cannot be null`

**Comment by tanersener** [comment]
You've said that running `react-native unlink react-native-ffmpeg` caused this error in your first post.

Unfortunately, `link` and `unlink` commands break Cocoapods dependencies on `iOS`. I recommend creating a new project and not using `link` and `unlink` commands.

**Comment by mifi** [comment]
Forget about link/unlink. To clarify: When installing `react-native-ffmpeg`, I ran `yarn add react-native-ffmpeg` and then `pod install` and nothing else. No link/unlink commands. When I then ran the app I got `invariant violation native module cannot be null` error:

![IMG_3650](https://user-images.githubusercontent.com/402547/70290694-ae8ad200-1813-11ea-9a96-ba52267b1417.PNG)

Then I tried to add to Podfile `pod 'react-native-ffmpeg', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec'`, and after doing that it works - I don't get this `invariant violation` runtime error anymore, however I get the original (nonfatal) error in my first post about autolinking.

**Comment by tanersener** [comment]
You are right. When RN > 0.60 and `Podfile` includes `use_native_modules!`, application fails with `Invariant Violation: Native module cannot be null.`

Unfortunately, I don't have a fix for that right now. There are similar issues in other react-native plugins but none of them include a solution.

**Comment by mifi** [comment]
Ok thanks 👍

**Comment by DaleWebb** [comment]
@tanersener, @mifi - See the above PR, effectively, it moves the podspec file up one level out of `ios/`. This resolves the issue.

**Comment by tanersener** [comment]
This issue is fixed in `v0.4.4`.

**Comment by DISKONEKTeD** [comment]
I upgraded to v0.4.4, with react-native 60.6. I get this message:

```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-ffmpeg (to unlink run: "react-native unlink react-native-ffmpeg")
```

I don't recall every manually linking it, i'm pretty certain i never did. i did however added this manually originally:

```
  pod 'react-native-ffmpeg/https-lts', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec'
```

So I get rid of that and go for the default package instead (i did a pod repo update and install)

But i still get the same issue

If i run react-native unlink react-native-ffmpeg, will this fix my issue now? or is it still not a valid thing to do?

This only occurs when i run

```
react-native run-ios --configuration Release
```

**Comment by tanersener** [comment]
@DISKONEKTeD Well, I still don't recommend running `react-native link` on `iOS`. But `unlink` shouldn't be causing any problems. You can try it.

**Comment by DISKONEKTeD** [comment]
Got it, thanks. I just tried it and for whatever reason, it still gives me that same error message. I run it in the simulator or on my phone just fine, but as soon as I do release it throws that error. I have a lot of other packages, and this is the only one that gives me that error.

How would I know if my Cocoapods dependencies are broken? Do you know? Would it just effect one package or all of them?

**Comment by tanersener** [comment]
It's not easy to detect. I delete the following files/directories and run `yarn install`, `pod install` again if I receive this kind of errors.

```
rm -rf node_modules
rm -rf ios/build
rm -rf ios/Pods
rm -rf ios/Podfile.lock
```

**Comment by DISKONEKTeD** [comment]
So I did what you recommended, using rm and i still get the same message when i run react-native run-ios.

I'm puzzled as to why it won't work

**Comment by tanersener** [comment]
I don't have an answer for that. Maybe it is version specific issue, `0.60.6` is pretty old. Did you try upgrading it?
