### ISSUE TITLE
push video to azure RTMP server

### ISSUE THREAD

**Issue by ManuRodgers** [tanersener/react-native-ffmpeg#12]
**Description**
Description of what the issue is about.
I can use this command ( /usr/local/ffmpeg/bin/ffmpeg -i https://ia800308.us.archive.org/30/items/popeye_shuteye_popeye/popeye_shuteye_popeye_512kb.mp4  -pixel_format bgr0 -framerate 30   -target pal-vcd -v verbose  -strict -2 -c:a aac -b:a 128k -ar 44100 -r 30 -g 60 -keyint_min 60 -b:v 400000 -c:v libx264  -bufsize 400k -maxrate 400k -f flv rtmp://rnffmepg-streamtest-ausoe.channel.media.azure.net:1935/live/c476cbc41dfe420b9212746a1437f934/text_stream ) on my macbook to push that input video to my azure RTMP server. However, I cannot do it in React Native with this command (  RNFFmpeg.execute(
              `-i https://ia800308.us.archive.org/30/items/popeye_shuteye_popeye/popeye_shuteye_popeye_512kb.mp4  -pixel_format bgr0 -framerate 30   -target pal-vcd -v verbose  -strict -2 -c:a aac -b:a 128k -ar 44100 -r 30 -g 60 -keyint_min 60 -b:v 400000 -c:v libx264  -bufsize 400k -maxrate 400k -f flv rtmp://rnffmepg-streamtest-ausoe.channel.media.azure.net:1935/live/c476cbc41dfe420b9212746a1437f934/text_stream`
            );)

**Expected behavior**
What you expected to happen.
that command should be working to push that video input to my Azure RTMP server.
**Current behavior**
What happened.

**Screenshots**
![image](https://user-images.githubusercontent.com/33333844/48168158-5ba9c700-e342-11e8-8e34-0de2ce62e012.png)
![image](https://user-images.githubusercontent.com/33333844/48168188-7419e180-e342-11e8-8880-d94b0f7a1c62.png)
![image](https://user-images.githubusercontent.com/33333844/48168215-8b58cf00-e342-11e8-991a-2bbcd1790e11.png)
![image](https://user-images.githubusercontent.com/33333844/48168248-a3c8e980-e342-11e8-98a6-207155bf1915.png)
![image](https://user-images.githubusercontent.com/33333844/48168273-bb07d700-e342-11e8-87fd-84547043bdf3.png)

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.com) and insert the link here.

**Environment**
 - React Native Environment Info

**Other**
thank you for your time and patience reading through my question

**Comment by tanersener** [comment]
There is an `Unable to find a suitable output format for ''` error in your command. 

 ![48168273-bb07d700-e342-11e8-87fd-84547043bdf3](https://user-images.githubusercontent.com/10158439/48182715-4a11f080-e33d-11e8-93b1-cc212b7dd135.png)

Most of the time this error occurs when your command includes double space characters, unnecessary new line character, etc. Can you check your command to see if it has these characters?

**Comment by ManuRodgers** [comment]
> There is an `Unable to find a suitable output format for ''` error in your command.
> 
> ![48168273-bb07d700-e342-11e8-87fd-84547043bdf3](https://user-images.githubusercontent.com/10158439/48182715-4a11f080-e33d-11e8-93b1-cc212b7dd135.png)
> 
> Most of the time this error occurs when your command includes double space characters, unnecessary new line character, etc. Can you check your command to see if it has these characters?

OK I will do it

**Comment by ManuRodgers** [comment]
> There is an `Unable to find a suitable output format for ''` error in your command.
> 
> ![48168273-bb07d700-e342-11e8-87fd-84547043bdf3](https://user-images.githubusercontent.com/10158439/48182715-4a11f080-e33d-11e8-93b1-cc212b7dd135.png)
> 
> Most of the time this error occurs when your command includes double space characters, unnecessary new line character, etc. Can you check your command to see if it has these characters?

Hi mate, I got this error right now, which means that I need to install full-gpl package to have 'libx264' library?
![image](https://user-images.githubusercontent.com/33333844/48184212-6d608e00-e385-11e8-913e-fee14f0b4b1a.png)

**Comment by tanersener** [comment]
You can use both `https-gpl` and `full-gpl` packages in your case. `full-gpl` is bigger in size, so I recommend using `https-gpl`.

**Comment by ManuRodgers** [comment]
Thanks mate, I will try tomorrow morning

Taner Sener <notifications@github.com>于2018年11月8日 周四19:11写道：

**Comment by ManuRodgers** [comment]
> You can use both `https-gpl` and `full-gpl` packages in your case. `full-gpl` is bigger in size, so I recommend using `https-gpl`.

hello mate,
I am meeting this problem, when I am using ffmpeg on my laptop, then I can get my expected result and if I am using it in React Native app with your library I cannot push video to Azure RTMP server as the fps is too low
![image](https://user-images.githubusercontent.com/33333844/48319206-20b7d400-e65f-11e8-9d90-17df5f1194a0.png)
![image](https://user-images.githubusercontent.com/33333844/48319231-8ad07900-e65f-11e8-9493-5cada72e0b6d.png)
![image](https://user-images.githubusercontent.com/33333844/48319243-bfdccb80-e65f-11e8-93f6-12625fabad61.png)
![image](https://user-images.githubusercontent.com/33333844/48319252-e26ee480-e65f-11e8-9570-803f58263fd8.png)
![image](https://user-images.githubusercontent.com/33333844/48319266-fa466880-e65f-11e8-804b-4b8ec78a565b.png)
![image](https://user-images.githubusercontent.com/33333844/48319303-65903a80-e660-11e8-955f-eeec1cfd2e74.png)
![image](https://user-images.githubusercontent.com/33333844/48319312-86589000-e660-11e8-8d2d-a4f8de0a821d.png)
![image](https://user-images.githubusercontent.com/33333844/48319329-ba33b580-e660-11e8-9bd4-07e6800e315c.png)

**Comment by tanersener** [comment]
> hello mate,
> I am meeting this problem, when I am using ffmpeg on my laptop, then I can get my expected result and if I am using it in React Native app with your library I cannot push video to Azure RTMP server as the fps is too low

Well, I'm not sure about the exact reason.
Mobile devices are slower and limited in resources. So If I were you I'd try to minimize resource usage by trying different values for command parameters. For example using a smaller/bigger `bufsize` may increase the speed of processing. 
Additionally I see that you have two phases in your command: downloading and rtmp streaming. I'd make different tests to see the performance of each phase. Maybe download speed is too slow and it effects the whole streaming speed.

**Comment by ManuRodgers** [comment]
> > hello mate,
> > I am meeting this problem, when I am using ffmpeg on my laptop, then I can get my expected result and if I am using it in React Native app with your library I cannot push video to Azure RTMP server as the fps is too low
> 
> Well, I'm not sure about the exact reason.
> Mobile devices are slower and limited in resources. So If I were you I'd try to minimize resource usage by trying different values for command parameters. For example using a smaller/bigger `bufsize` may increase the speed of processing.
> Additionally I see that you have two phases in your command: downloading and rtmp streaming. I'd make different tests to see the performance of each phase. Maybe download speed is too slow and it effects the whole streaming speed.

OK I will try it

**Comment by tanersener** [comment]
@ManuRodgers I don't know the last status on these tests but I want to let you know that a new `mobile-ffmpeg` release, `v3.1`, is published recently. It has noticeable performance boost and decreased memory usage on `IOS`. It is installed automatically when you run `pod install`. You may want to repeat these tests on that release.

**Comment by tanersener** [comment]
I'm closing this issue, you can re-open it if you still need help.
