### ISSUE TITLE
Reading CameraRoll video assets

### ISSUE THREAD

**Issue by billdami** [tanersener/react-native-ffmpeg#121]
I am using the official RN CameraRoll package (https://github.com/react-native-community/react-native-cameraroll) to access videos stored in the device's photos library, and I want to use react-native-ffmpeg to trim/compress/transcode these videos before being uploaded. Is this possible?

On Android, using the filepath provided by the CameraRoll API for each video in `node.image.uri` works fine. However, on iOS I get either `"Protocol Not found` or `No such file or directory` errors from FFmpeg, when passing in this uri value. 

The default format coming from CameraRoll for these URI's are like:
```
ph://B10CF88E-CC87-467D-AD12-EC70A4E5FF24/L0/001
```
I've also tried other protocols/variations, such as:
```
file://B10CF88E-CC87-467D-AD12-EC70A4E5FF24/L0/001
```
and
```
assets-library://asset/asset.mov?id=470D2A1F-B0A9-43E5-8C4B-7368D6869E1E&ext=mov
```
(^ this is the format required to play videos on iOS using react-native-video)

Will react-native-ffmpeg handle iOS PH library assets directly like this in any uri/protocol format? Or is there some other package that can be used to make a temp copy in the cache folder that is usable by ffmpeg?

Thanks in advance.

**Comment by billdami** [comment]
Disregard this, I answered my own question. 😄

For anyone that stumbles on this with the same question, I was able to do this with the react-native-fs package. Specifically, copying the asset library file to the application cache directory, using this:

https://github.com/itinance/react-native-fs#copyassetsvideoiosvideouri-string-destpath-string-promise

**Comment by JoudAwEpic** [comment]
@billdami are you able to post your solution for this problem ? as i was having the same issue and was not able to fix...
