### ISSUE TITLE
WIth version of React Native 0.61.5 Provides incorrect path to podspec

### ISSUE THREAD

**Issue by bigorangemachine** [tanersener/react-native-ffmpeg#122]
**Description**
After linking the library & `pod install` inside of the ios directory; you get an error and you have to manually change the podspec path

**Expected behavior**
pod install shouldn't error

**Current behavior**
Pod install errors out

**Logs**
``` 
No podspec found for react-native-ffmpeg in ../react-native-ffmpeg/ios/react-native-ffmpeg.podspec
```

**Environment**
React Native 0.61.5

**Other**
Had to change `Podfile` from 

```
platform :ios, '9.3'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# ...
target 'appname' do
  # ...
  pod 'react-native-ffmpeg', :path => '../node_modules/react-native-ffmpeg'
```
to
```
pod 'react-native-ffmpeg', :path => '../react-native-ffmpeg/ios/react-native-ffmpeg.podspec'
```

**Comment by tanersener** [comment]
As explained in [2.2.1 Basic](https://github.com/tanersener/react-native-ffmpeg#221-basic) section of README, `react-native link` breaks `Cocoapods` dependencies. You shouldn't be using it.

**Comment by bigorangemachine** [comment]
Oh thanks Gotcha!  Podspec not path!

I did a manual update but had the wrong hash property!
