### ISSUE TITLE
Pod install exits with Target has frameworks with conflicting names.

### ISSUE THREAD

**Issue by nishanBende** [tanersener/react-native-ffmpeg#123]
**Description**
I am trying to install two packages https and audio using below commands in pod file
```
pod 'react-native-ffmpeg/https', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec'
pod 'react-native-ffmpeg/audio', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec'
```

**Expected behavior**
Pod installation should work

**Current behavior**
Installation halts

**Logs**
```
Analyzing dependencies
Fetching podspec for `react-native-ffmpeg` from `../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec`
Downloading dependencies
Installing mobile-ffmpeg-audio (4.3)
Installing react-native-ffmpeg 0.4.0
[!] The 'Pods-QlipCast' target has frameworks with conflicting names: mobileffmpeg.framework, libavcodec.framework, libavdevice.framework, libavfilter.framework, libavformat.framework, libavutil.framework, libswresample.framework, libswscale.framework, libcharset.framework, and libiconv.framework.
```
**Environment**
 SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
      react-native: 0.59.9 => 0.59.9 

**Other**
I want to use a network URL to perform FFmpeg encoding but it requires https and audio packages, so I need to install both of them. I read the documentation but is there anything I am doing wrong?

Thanks

**Comment by tanersener** [comment]
> Pod installation should work

They can't and won't work. Can you try installing `full` package which includes both `audio` and `https` packages?

**Comment by nishanBende** [comment]
@tanersener tried that and it works. I am a bit noob in ios 😅  
Thanks
