### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by sagark1510** [tanersener/react-native-ffmpeg#124]
**What do I have to do in order to follow the license**
Hi, I saw the licensing wiki from the other library author shared. But I am new to this whole licensing procedure and can not digest what exactly it says and what should we do to comply with the terms of the license.

I have some questions/doubts.
1. What if I only use min-gpl? Do I need to do anything extra?
2. Do I have to open source my whole project if I am using full-gpl?
3. What features of this library I can use without violating the licensing terms and avoid the extra steps?

**Comment by tanersener** [comment]
This is the [wiki page](https://github.com/tanersener/mobile-ffmpeg/wiki/Using-MobileFFmpeg-in-Commercial-Applications) that explains the situation. It is written for `MobileFFmpeg` but it is the same for `react-native-ffmpeg` too.

Answers of your questions:
`1. 2.` There is not much difference between using `min-gpl` and `full-gpl` packages.  If you use a GPL licensed package, source code of your application must be available to all users using your application. It doesn't mean that your application should be open-source, it means that users should be able to access it. You can to include source code in your app or provide a link to the source code of your application.

`3.` You can choose to use one of the non-GPL packages. They have easier terms.

**Comment by sagark1510** [comment]
Ok so in the end I can not use this lib without sharing my project code.

I thought gpl/lgpl licensing conditions only apply if we change the source code of the ffmpeg.

**Comment by tanersener** [comment]
> I thought gpl/lgpl licensing conditions only apply if we change the source code of the ffmpeg.

Unfortunately no, you don't have to see/modify the source code of that library. You're linking your application to a GPL/LGPL licensed library and this is what matters here. 

It is important here to understand the difference between GPL and LGPL. Under LGPL you don't have to share the source code of your application. You can share the binary of your app but allow user to replace the LGPL licensed library by providing the instructions to do that, for example you can provide the Xcode/Android Studio project and explain the user how he/she can use another version of that LGPL licensed library.

**Comment by sagark1510** [comment]
@tanersener  okay one last question. What if I only use "min" package? do I still need to share the android/xcode project or binaries?

**Comment by tanersener** [comment]
Which platform do you use?

**Comment by sagark1510** [comment]
both android and ios

**Comment by tanersener** [comment]
> What if I only use "min" package? do I still need to share the android/xcode project or binaries?

Yes, you still need to do that. I tried to explain that in the Licensing wiki page. Also you can check [this stackoverflow post](https://stackoverflow.com/questions/10130143/gpl-lgpl-and-static-linking/10179181#10179181) too. It summarises how they will be licensed.

**Comment by sagark1510** [comment]
Okay. Thanks for quick response. :)
