### ISSUE TITLE
RNFFprobe.getMediaInformation only work first time.

### ISSUE THREAD

**Issue by bxxn7889** [tanersener/react-native-ffmpeg#131]
RNFFprobe.getMediaInformation('<file path or uri>').then(info => {
    console.log('Result: ' + JSON.stringify(info));
});

getMediaInformation only work first time.
after one exec all info is undefined.

and result is {"rawInformation":"Unknown output format with name 'default'\n"}

**Comment by tanersener** [comment]
Thanks for reporting this issue. 
Can you use `v0.4.0` until this issue is resolved?

**Comment by bxxn7889** [comment]
Thanks, 
I'll test and answer

**Comment by bxxn7889** [comment]
0.4.0  {"rawInformation":"Unknown output format with name 'default'\n"} resolved.

but MediaInformation is nothing passed.

**Comment by tanersener** [comment]
So, you have the same issue on `0.4.0`, right?

**Comment by bxxn7889** [comment]
yes right.

**Comment by tanersener** [comment]
Well, I identified the issue and I'm working on the fix but it is specific to a class introduced in `0.4.1`. In `0.4.0` there does not exist a class that prints `Unknown output format with name 'default'\n` error message.

Can you try to see which version of `mobile-ffmpeg` you are using in your app?

**Comment by tanersener** [comment]
Fixed. Clean your `gradle`/`cocoapods` caches and try again.

**Comment by bxxn7889** [comment]
Thanks. I confirmed it fixed.
