### ISSUE TITLE
[QUESTION] Can I use android_camera with this package?

### ISSUE THREAD

**Issue by livnunes** [tanersener/react-native-ffmpeg#133]
I've tried to use it this way like I read in the ffmpeg-mobile docs:

RNFFmpeg.execute("-f android_camera -i 0:0 -r 30 -pixel_format bgr0 -t 00:00:05 /storage/emulated/0/Download/test3.mp4");

Currently getting the following error, so wondering if I'm doing something wrong. Thanks in advance.

[android_camera @ 0x7498e97c00] No camera with index 0 available.
C:\React-Apps\tests\App.js:20 [android_camera @ 0x7498e97c00] Failed to open camera.
C:\React-Apps\tests\App.js:20 [android_camera @ 0x7498e97c00] Failed to open android_camera.
C:\React-Apps\tests\App.js:20 0:0: No such device or address

**Comment by tanersener** [comment]
That error means that your camera is not supported by Android NDK Native API as explained in the [Camera Support wiki page](https://github.com/tanersener/mobile-ffmpeg/wiki/Camera-Support)

`
... devices with deprecated camera HAL 1.0 implementations (camera devices that have the LEGACY hardware level) are not supported by Android NDK Native API, consequently they are not supported by MobileFFmpeg as well.
`
