### ISSUE TITLE
How to install specific package with ffmpeg?

### ISSUE THREAD

**Issue by Akeuuh** [tanersener/react-native-ffmpeg#135]
**Description**
Hi, 

Thanks for your good work with ffmpeg!

As I'm trying to convert video files to .mp4, I see that it seems to have a default level of compression that create some artifacts.

I'd like to control the level of compression and I've seen the **crf** argument could manage it. The only problem is that it is only usable with x264 lib included in gpl packages.

As my devtool returns that it doesn't know this, I assume that I don't have the right package installed.

My question is simple: How can I manage to get a specific package installed with ffmpeg lib?

Thank again!

**Logs**
Loaded react-native-ffmpeg-android-arm64-v8a.
Unknown encoder 'x264'

**Environment**
react native 0.59.4

**Comment by tanersener** [comment]
We have a section at [wiki](https://github.com/tanersener/react-native-ffmpeg#23-packages) about it. Did you try instructions listed there?

**Comment by Akeuuh** [comment]
Thank you very much for your quick answer!

After chatting with a friend about that, he showed me this section. Sorry I'm a little tired.

Thank you!
