### ISSUE TITLE
 Unknown encoder 'mpeg4'

### ISSUE THREAD

**Issue by codeverydaya** [tanersener/react-native-ffmpeg#138]
when I execute the code:
"RNFFmpeg.execute('-i file1.mp4 -c:v mpeg4 file2.mp4')"

in console,It tell me " Unknown encoder 'mpeg4'"

**Comment by RupamShaw** [comment]
Still getting this error. any updates?

**Comment by tanersener** [comment]
See [Always fill the issue template](https://github.com/tanersener/react-native-ffmpeg/issues/62).


> It is not possible to predict the cause of an error without knowing your environment, without understanding what you are trying to achieve or which steps failed for you.
>
> So, please fill the issue template provided when creating an issue. Issues which do not fill out issue template are ignored.
```
