### ISSUE TITLE
Unknown encoder 'libx264' 

### ISSUE THREAD

**Issue by manikandasankar** [tanersener/react-native-ffmpeg#14]
I am getting the following error when i trying to push a video to wowza server

Ffmpeg command:
**'-i <input_file_path> -vf scale=1280:720 -vcodec libx264 -profile:v baseline -pix_fmt yuv420p -f flv <wowza_server_path>**

Error Message:
**Unknown encoder 'libx264'
Conversion failed!**

**Comment by tanersener** [comment]
This message says that your package does not include x264 library. You need to select a package with x264 enabled as explained in README.

**Comment by issamabdelkrim** [comment]
hello @tanersener @manikandasankar
  how i can enable x264 library ?

**Comment by etsraphael** [comment]
After add : 

`pod 'react-native-ffmpeg/x264', :podspec => '../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec'`

Is still not working for me. Did I miss something ? I have the same issue.
