### ISSUE TITLE
Move image sequence into video

### ISSUE THREAD

**Issue by timvanwolfswinkel** [tanersener/react-native-ffmpeg#140]
**Description**
I have a set of images that I want to merge into a video.

**Expected behavior**
Video generated in the local documents folder of device.

**Current behavior**
Getting a `Invalid argument` error.

**Logs**
[Log](https://ghostbin.co/paste/zup2n)

**Environment**
 - 0.61.5

**Other**
This is the command I'm using: `ffmpeg -framerate 1 -pattern_type glob -i '${path}/*.jpg' -f mp4 '${path}/test.mp4'` which transforms in something like `ffmpeg -framerate 1 -pattern_type glob -i '/Users/.../Application/C060D8C8-F508-459C-9182-45D920D42700/Documents/1/*.jpg' -f mp4 '/Users/.../Application/C060D8C8-F508-459C-9182-45D920D42700/Documents/1/test.mp4'` it works when I locally run it in my terminal but not when it's fired in the app. Any idea why this could happen?

Thanks in advance for the help.

**Comment by tanersener** [comment]
As shown in the [3. Using](https://github.com/tanersener/react-native-ffmpeg#3-using) section, you don't need to include `ffmpeg` in your commands. Please try without `ffmpeg` at the start.

**Comment by timvanwolfswinkel** [comment]
@tanersener Oops, sorry for missing that part. It works, thanks. Also thanks for the package!

**Comment by timvanwolfswinkel** [comment]
@tanersener Oops sorry to have missed that part. It is working in my simulator now but the video doesn't show when I run it on a device. When logging it seems to generate the video (bit slower then simulator). Any ideas what it could be?

**Comment by tanersener** [comment]
> but the video doesn't show when I run it on a device. 

Do you mean video is not playable?

I know that some Android devices do not support a few `mp4` profiles but I don't know if this is the case. I need to see the console output to make a comment.

**Comment by timvanwolfswinkel** [comment]
Thank you @tanersener, yes I think I need to implement the x264 codec. Sorry, I'm a bit new to ffmpeg/video conversions.

**Comment by timvanwolfswinkel** [comment]
@tanersener I'm getting a `Could not build module 'mobileffmpeg'` when trying to run a release build, are you familiar with this?

**Comment by tanersener** [comment]
Unfortunately, no I didn't receive it before. But I think this is not the actual error. There should be another compilation error message that causes this.

**Comment by timvanwolfswinkel** [comment]
```
2020-03-13 14:02:18.492745+0100 PlusBricks[69727:4493563] Loaded mobile-ffmpeg-https-gpl-arm64-4.3.1-lts-20200125
2020-03-13 14:02:18.668 [error][tid:com.facebook.react.JavaScript] ReferenceError: Can't find variable: enhancer
2020-03-13 14:02:18.711 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: ReferenceError: Can't find variable: enhancer
2020-03-13 14:02:18.715 [error][tid:com.facebook.react.JavaScript] Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
2020-03-13 14:02:18.726651+0100 PlusBricks[69727:4493563] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: ReferenceError: Can't find variable: enhancer', reason: 'Unhandled JS Exception: ReferenceError: Can't find variable: enhancer, stack:
default@588:150
<unknown>@408:465
v@2:1474
<unknown>@6:70
v@2:1474
d@2:876
global code@739:4
'
*** First throw call stack:
(0x21b317180 0x21a4ef9f8 0x100826850 0x100898558 0x21b31e800 0x21b2003c0 0x21b200ff4 0x1008592f8 0x10085b408 0x10085b16c 0x102c476f4 0x102c48c78 0x102c50bf4 0x102c518b4 0x102c5b77c 0x21af36114 0x21af38cd4)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)
```

<img width="227" alt="Screenshot 2020-03-13 at 15 53 39" src="https://user-images.githubusercontent.com/5946741/76632095-f0c65c80-6542-11ea-9487-f372e869cf55.png">

Is this not related to the package you think?

**Comment by tanersener** [comment]
It looks like your actual error is `Thread-local storage is not supported for the current target`. 

`react-native-ffmpeg` requires `iOS 9.3` which supports `thread-local storage`. Can you check your project targets? I suspect one of them is lower than `9.3`.

**Comment by timvanwolfswinkel** [comment]
The target of the build is iOS 12.4, this is my podfile which I've already changed to 9.3 based on other issues:

```platform :ios, '9.3'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'PlusBricks' do
  # Pods for PlusBricks
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-ffmpeg/https-gpl-lts', :podspec => '../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec'
  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  use_native_modules!

  target 'PlusBricksTests' do
    inherit! :search_paths
    # Pods for testing
  end

end```

**Comment by tanersener** [comment]
It is not possible to run `pod install` with your `Podfile`. 

After adding `react-native-fetch-blob` with `yarn add react-native-fetch-blob`, I tried to run pod install and received the following error. 

```
[!] CocoaPods could not find compatible versions for pod "React/Core":
  In Podfile:
    react-native-fetch-blob (from `../node_modules/react-native-fetch-blob`) was resolved to 0.10.6, which depends on
      React/Core

None of your spec sources contain a spec satisfying the dependency: `React/Core`.
```

**Comment by timvanwolfswinkel** [comment]
Thanks for all the help @tanersener, you are right, I removed it now because it shouldn't have been manually linked. In the projects within xcode the deployment targets were still on low iOS versions. Upgraded them and the build succeeds. App still crashes but that must be something else not related to this package. 

I have the feeling I'm getting there step by step. You can close this issue if you want :).

**Comment by tanersener** [comment]
Okay 👍
