### ISSUE TITLE
Can not write a file, operation not permitted, read-only

### ISSUE THREAD

**Issue by y-sumanth** [tanersener/react-native-ffmpeg#145]
I am trying to convert an image into a video.
```
RNFFmpeg.execute(`-i ${image.path} -c:v mpeg4 output.mp4`).then(result =>
    console.log('FFmpeg process exited with rc ' + result.rc),
);
```
Log says 
`output.mp4: operation not permitted` in iOS and 
`output.mp4: read-only file system` in Android. 
`FFmpeg process exited with rc 1`

Please help

**Comment by tanersener** [comment]
This issue is not about the library. Why don't you ask google about it? You can find a solution faster.

**Comment by y-sumanth** [comment]
@tanersener 
It also says `FFmpeg process exited with rc 1`

It's a bit critical. I did search on google also. could not find a solution. Please help. What could be the possible cause?

**Comment by y-sumanth** [comment]
@tanersener 
in [Tips](https://github.com/tanersener/react-native-ffmpeg#6-tips), it says to give absolute paths for input. How can we control an output destination?

**Comment by tanersener** [comment]
By adding a directory name in front of your `output.mp4` file.

**Comment by y-sumanth** [comment]
Thanks :)

**Comment by chrisid** [comment]
When picking a video from the user's library this is happening for all videos.

`const outputFile = `${RNFS.CachesDirectoryPath}/video.mp4`;
const ffmpegCommand = `-i ${file} -c:v libx265 -b:v 2M -minrate 2M -preset faster ${outputFile}`;`

resulting in:
` -i file:///Users/christianpugliese/Library/Developer/CoreSimulator/Devices/50B4E81B-C640-4C8A-B2BF-22CD5AC5FCBE/data/Containers/Data/Application/8C094042-938B-4457-9B20-405632B94FAD/tmp/react-native-image-crop-picker/46F0C003-0BD4-4F34-AC3E-83F8456461F7.mp4 -c:v libx265 -b:v 2M -minrate 2M -preset faster /Users/christianpugliese/Library/Developer/CoreSimulator/Devices/50B4E81B-C640-4C8A-B2BF-22CD5AC5FCBE/data/Containers/Data/Application/8C094042-938B-4457-9B20-405632B94FAD/Library/Caches/video.mp4`

I've tried a lot of variants, always resulting in:
`FFmpeg process failed with rc=1`
