### ISSUE TITLE
[Question] Working with video stream from camera?

### ISSUE THREAD

**Issue by zocheyado** [tanersener/react-native-ffmpeg#15]
Title pretty much says it all, without doing a ton of research I am curious to know if this FFMPEG implementation would be able to encode or maybe split up an incoming video stream from the device itself. Thinking about using EXPO sdk and their camera features.

**Comment by tanersener** [comment]
Some tests were performed a while ago, let me repeat them first, then I'll let you know.

**Comment by tanersener** [comment]
The latest version `v0.2.1` supports accessing and recording video from `IOS` camera but `Android` camera is not accessible unfortunately.

Issue about `Android` camera is a little bit complicated. Initially `video4linux2` was planned and enabled to access `Android` camera but it fails to detect video devices. So it is not usable right now. `Android` camera support without `video4linux2` is planned for new releases so I'll mark this issue as `enhancement`.

**Comment by zocheyado** [comment]
So if instead I had a seperate logic / code to record the video. Could I point FFMPEG to the file location and  split / mux the live file as it is being created?

**Comment by tanersener** [comment]
What do you mean by separate logic/code?

You can use `-f avfoundation -r 30 -video_size 1280x720 -pixel_format bgr0 -i 0:0 -vcodec h264_videotoolbox -vsync 2 -f h264 -t 00:00:05 <record file path>` command to record video from IOS camera. You can set your own path as `<record file path>` and define a record duration in `-t 00:00:05` section (00:00:05 is 5 seconds). 

According to documentation, it is possible to auto-split the recording by defining a segment time in a block like `-f segment -segment_time 60 "xxx-%03d.ts"` but I didn't test it before. 

Additionally, you can select which camera and/or microphone to record in `-i 0:0` block. `-i 0:0` says video device `0`(which is back camera in my device) and audio device `0`. Other options are explained in [AVFoundation Input Device](https://www.ffmpeg.org/ffmpeg-devices.html#avfoundation) documentation.

**Comment by zocheyado** [comment]
I mean if I use a separate package / totally different module to record my video (NOT FFMPEG). But I have the file location, would there be any issue reading that file as it is being created and run FFMPEG commands on it?

**Comment by tanersener** [comment]
> I mean if I use a separate package / totally different module to record my video (NOT FFMPEG). But I have the file location, would there be any issue reading that file as it is being created and run FFMPEG commands on it?

No, there won't be any issues. You only need to give appropriate permissions to read the file and that's it.

**Comment by tanersener** [comment]
> `Android` camera support without `video4linux2` is planned for new releases so I'll mark this issue as `enhancement`.

I've done some tests on this. Unfortunately there is not a complete solution to access Android capture devices. So there won't be any enhancements on accessing Android camera unless Android Native Camera API is improved.
