### ISSUE TITLE
Is metadata and tags editable?

### ISSUE THREAD

**Issue by SpQuyt** [tanersener/react-native-ffmpeg#150]
**Description**
I'm using **react-native-ytdl** to download mp3 files from Youtube videos. But those mp3 files has no **metadata** and no **artist** and **title** tag. So those mp3 files cannot be played by default player on my phone.

**Expected behavior**
I want to ask if this library of yours can edit or modify **metadata** or add **title** and **artist** tags?
Thank you in advanced!

**Current behavior**
No tags and metadata.

**Screenshots**
![image](https://user-images.githubusercontent.com/17812909/78901123-155e1780-7aa2-11ea-8bd0-9ad7b59caf3f.png)

**Logs**

**Environment**
 - react-native v0.62.1
 - react-native-ytdl v1.0.7
 - react-native-ffmpeg v0.4.4

**Other**

**Comment by tanersener** [comment]
Please see [FFmpeg Metadata](https://wiki.multimedia.cx/index.php/FFmpeg_Metadata).

**Comment by SpQuyt** [comment]
Thank you so much!
