### ISSUE TITLE
Drastically increasing android build size

### ISSUE THREAD

**Issue by venkataluri** [tanersener/react-native-ffmpeg#153]
Hi,
After installing this package my android build size has increased from 42 mb to  75 mb.
but in NPM page this package is showing that only 1.92 Mb.
is there any thing i am doing wrong?

**Comment by tanersener** [comment]
No, you are not. Dependencies that `react-native-ffmpeg` depends are increasing the app size. If app size is a concern for you, try installing the `min` package. It is the smallest `react-native-ffmpeg` package available.

**Comment by venkataluri** [comment]
@tanersener 
Thanks for your quick response.
I tried to install Min package, but i was not successful
Can you please help me in installing min package.

**Comment by tanersener** [comment]
If you give some more detail about what you did and what failed I can try to help.

**Comment by venkataluri** [comment]
I have searched for npm package for FFMPEG-min pack, but i didn't find any.
I have gone through LTS release document, but i was not clear for me.
Please help me in installing min package

**Comment by tanersener** [comment]
Did you read [2.3 Packages](https://github.com/tanersener/react-native-ffmpeg#23-packages) in README?

**Comment by venkataluri** [comment]
thanks for quick response,
after adding following line in build.gradle
```
ext {
        reactNativeFFmpegPackage = "min"
    }
```
its working but still build size is higher only

actual build size without this package:  42 mb
full package : 75 mb
min package :  67 mb

min package is also taking 25 mb of size
am i doing any thing wrong?  or is this expected size of min package?

**Comment by tanersener** [comment]
`min` package is 25 MB. It includes native libraries for 4 architectures. It means each architecture is around 6 MBs and you application size will only grow 6 MB if you configure it correctly. To configure it correctly please refer to Android documentation, for example https://developer.android.com/studio/build/configure-apk-splits page explains some details about how that can be done.

**Comment by venkataluri** [comment]
Thank you very much @tanersener
i will go through it and implement as suggested

**Comment by enigmablue** [comment]
Hi there.

Unfortunately the size is a bit significant. Its more then 6 MB , more like 12MB. And my app is already bundled. (Perhaps Hermes is needed). It does explicitly mention LDPI armeabi-v7a which is a 61% increase. (probably 20mb to 39mb). 

I'm using https-lts. Is that expected? Wonder if theres any hints to see if the packages can be downsized it as well its quite bad to have such a big increase.

I did try min but i hit some issues for it i think on IOS, may have to retry it. I'm just using normal mpeg4 compression. 
`await RNFFmpeg.executeWithArguments(["-y","-i", uri, "-c:v", "mpeg4", newFile])`

![image](https://user-images.githubusercontent.com/35584085/83395052-33098680-a42c-11ea-9ae0-be45e37a45fc.png)


![image](https://user-images.githubusercontent.com/35584085/83395092-487eb080-a42c-11ea-864d-1135122fd0c6.png)

**Comment by tanersener** [comment]
> Unfortunately the size is a bit significant. Its more then 6 MB , more like 12MB. 

Size depends on the `react-native-ffmpeg` package you use. For `min` package it is around 6 MB. For `https-gpl` it should be higher, maybe 12 MB as you've said. Try to choose the smallest package you can use if a size is a concern for you.

> And my app is already bundled. (Perhaps Hermes is needed). 

`Hermes` is a JavaScript engine. It can't help you for native libraries coming with `react-native-ffmpeg`.

> It does explicitly mention LDPI armeabi-v7a which is a 61% increase. (probably 20mb to 39mb).

`armeabi-v7a` abi in `LTS` releases include 2 architectures `arm-v7a` and `arm-v7a-neon`. This means it has double the size of other abis.

> I'm using https-lts. Is that expected? Wonder if theres any hints to see if the packages can be downsized it as well its quite bad to have such a big increase.

You can build the parent `mobile-ffmpeg` project by yourself and choose which architectures, external libraries and ffmpeg components you want to use. In this way you can smaller native binaries. Using them in your application will decrease app size further.

**Comment by enigmablue** [comment]
Thanks for the information and tips. Does that mean i need to fork it and adjust something? sorry not familiar with that part yet :/

> You can build the parent `mobile-ffmpeg` project by yourself and choose which architectures, external libraries and ffmpeg components you want to use. In this way you can smaller native binaries. Using them in your application will decrease app size further.

**Comment by tanersener** [comment]
No, clone the library, install the prerequisites and run `android.sh` with some parameters. [How to decrease binary size](https://github.com/tanersener/mobile-ffmpeg/wiki/How-to-decrease-binary-size) wiki page explains the terminology of how binary size can be decreased.

**Comment by personapp** [comment]
> No, clone the library, install the prerequisites and run `android.sh` with some parameters. [How to decrease binary size](https://github.com/tanersener/mobile-ffmpeg/wiki/How-to-decrease-binary-size) wiki page explains the terminology of how binary size can be decreased.

Tekrar açtığım için özür dilerim ancak native kodlar hakkında yeterli bilgi sahibi olmadığım için tüm wiki'leri okumama rağmen 

- kütüphaneyi kopyalamak
- ios.sh, android.sh, ios.ffmpeg.sh and android.ffmpeg.sh dosyalarını ihtiyacıma göre değiştirmek
- gerekli flaglarla dosyaları çalıştırıp prebuild klasörü

![Screen Shot 2021-05-30 at 02 46 39](https://user-images.githubusercontent.com/26903406/120087550-9c7cad80-c0f1-11eb-9ecb-3adeed9ebcdb.png)

elde etmekten öteye gidemedim.

Klonladığım ve prebuild klasörü oluşturduğum "mobile-ffmpeg" den custom bir CocoaPods yapıp "react-native-ffmpeg" içerisinde kullanmam gerektiğini düşündüm ancak nasıl yapacağıma dair fikrim yok. En azından yol göstererek yardımcı olursanız çok sevinirim. İyi çalışmalar.

**Comment by tanersener** [comment]
See [MobileFFmpeg Project Layout](https://github.com/tanersener/mobile-ffmpeg/wiki/Project-Layout) wiki page. It lists the folders `iOS` binaries are created under. Ideally you should have an `ios-framework` or an `ios-xcframework` framework, and that folder should include the bundles you can use in an `iOS` app/library.

**Comment by fatemafreezewala** [comment]
By using min-pakage some functionality stops working
