### ISSUE TITLE
Using select between filter doesn't set the starting point

### ISSUE THREAD

**Issue by ahmetbicer** [tanersener/react-native-ffmpeg#154]
**Description**
I am trying to extract all frames between given seconds. But select filter doesn't work as expected. It doesn't change the starting time of the video.

**Expected behavior**
I am using this filter `-vf select='between(t\\,19\\,20)'` and expected behaviour is extract the frames between 19 and 20 seconds.

**Current behavior**
When i use this filter `-vf select='between(t\\,19\\,20)'` it extracts the frames between 0 to 1 seconds but according to the documentation it needs to extract the frames between 19 to 20th second. If i change the filter like this `-vf select='between(t\\,19\\,21)'` it extracts frames from 0 to 2 seconds. So it gets the duration from select statement right but doesn't change the starting point to 19th second. I also try to use -ss argument to change the starting point of the video but it doesn't affects either.

**Screenshots**

**Logs**
This is the logs when i use this code:
`RNFFmpeg.execute("-i ${this.state.videoPath} -vf select='between(t\\,19\\,21)' -vsync 0 ${RNFS.CachesDirectoryPath}/fbfCache/out%03d.jpg")`

`ffmpeg version git-2020-01-25-fd11dd500
[Mon Apr 20 2020 02:19:06.981]  LOG       Copyright (c) 2000-2020 the FFmpeg developers
[Mon Apr 20 2020 02:19:06.982]  LOG      

[Mon Apr 20 2020 02:19:06.983]  LOG        built with Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)

[Mon Apr 20 2020 02:19:06.984]  LOG        configuration: --cross-prefix=x86_64-linux-android- --sysroot=/files/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot --prefix=/home/taner/Projects/mobile-ffmpeg/prebuilt/android-x86_64/ffmpeg --pkg-config=/usr/bin/pkg-config --enable-version3 --arch=x86_64 --cpu=x86_64 --cc=x86_64-linux-android21-clang --cxx=x86_64-linux-android21-clang++ --target-os=android --disable-neon --enable-asm --enable-inline-asm --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --enable-shared --disable-v4l2-m2m --disable-outdev=v4l2 --disable-outdev=fbdev --disable-indev=v4l2 --disable-indev=fbdev --enable-small --disable-openssl --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-static --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disable
[Mon Apr 20 2020 02:19:06.985]  LOG        libavutil      56. 38.100 / 56. 38.100

[Mon Apr 20 2020 02:19:06.986]  LOG        libavcodec     58. 65.102 / 58. 65.102

[Mon Apr 20 2020 02:19:06.987]  LOG        libavformat    58. 35.101 / 58. 35.101

[Mon Apr 20 2020 02:19:06.989]  LOG        libavdevice    58.  9.103 / 58.  9.103

[Mon Apr 20 2020 02:19:06.990]  LOG        libavfilter     7. 70.101 /  7. 70.101

[Mon Apr 20 2020 02:19:06.991]  LOG        libswscale      5.  6.100 /  5.  6.100

[Mon Apr 20 2020 02:19:06.992]  LOG        libswresample   3.  6.100 /  3.  6.100

[Mon Apr 20 2020 02:19:07.300]  LOG      Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/Download/min.mp4':

[Mon Apr 20 2020 02:19:07.300]  LOG        Metadata:

[Mon Apr 20 2020 02:19:07.400]  LOG          major_brand     : 
[Mon Apr 20 2020 02:19:07.500]  LOG      mp42
[Mon Apr 20 2020 02:19:07.600]  LOG      

[Mon Apr 20 2020 02:19:07.700]  LOG          minor_version   : 
[Mon Apr 20 2020 02:19:07.800]  LOG      0
[Mon Apr 20 2020 02:19:07.800]  LOG      

[Mon Apr 20 2020 02:19:07.900]  LOG          compatible_brands: 
[Mon Apr 20 2020 02:19:07.100]  LOG      isommp42
[Mon Apr 20 2020 02:19:07.110]  LOG      

[Mon Apr 20 2020 02:19:07.110]  LOG          creation_time   : 
[Mon Apr 20 2020 02:19:07.120]  LOG      2019-02-20T16:08:57.000000Z
[Mon Apr 20 2020 02:19:07.140]  LOG      

[Mon Apr 20 2020 02:19:07.150]  LOG          encoder         : 
[Mon Apr 20 2020 02:19:07.150]  LOG      Google
[Mon Apr 20 2020 02:19:07.160]  LOG      

[Mon Apr 20 2020 02:19:07.170]  LOG        Duration: 
[Mon Apr 20 2020 02:19:07.180]  LOG      00:01:02.44
[Mon Apr 20 2020 02:19:07.180]  LOG      , start: 
[Mon Apr 20 2020 02:19:07.190]  LOG      0.000000
[Mon Apr 20 2020 02:19:07.200]  LOG      , bitrate: 
[Mon Apr 20 2020 02:19:07.200]  LOG      2131 kb/s
[Mon Apr 20 2020 02:19:07.210]  LOG      

[Mon Apr 20 2020 02:19:07.220]  LOG          Stream #0:0
[Mon Apr 20 2020 02:19:07.230]  LOG      (und)
[Mon Apr 20 2020 02:19:07.240]  LOG      : Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 2000 kb/s
[Mon Apr 20 2020 02:19:07.240]  LOG      , 
[Mon Apr 20 2020 02:19:07.250]  LOG      29.97 fps, 
[Mon Apr 20 2020 02:19:07.280]  LOG      29.97 tbr, 
[Mon Apr 20 2020 02:19:07.290]  LOG      11988 tbn, 
[Mon Apr 20 2020 02:19:07.300]  LOG      59.94 tbc
[Mon Apr 20 2020 02:19:07.310]  LOG       (default)
[Mon Apr 20 2020 02:19:07.320]  LOG      

[Mon Apr 20 2020 02:19:07.320]  LOG          Metadata:

[Mon Apr 20 2020 02:19:07.330]  LOG            creation_time   : 
[Mon Apr 20 2020 02:19:07.340]  LOG      2019-02-20T16:08:57.000000Z
[Mon Apr 20 2020 02:19:07.350]  LOG      

[Mon Apr 20 2020 02:19:07.360]  LOG            handler_name    : 
[Mon Apr 20 2020 02:19:07.360]  LOG      ISO Media file produced by Google Inc. Created on: 02/20/2019.
[Mon Apr 20 2020 02:19:07.380]  LOG      

[Mon Apr 20 2020 02:19:07.390]  LOG          Stream #0:1
[Mon Apr 20 2020 02:19:07.400]  LOG      (eng)
[Mon Apr 20 2020 02:19:07.410]  LOG      : Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s
[Mon Apr 20 2020 02:19:07.410]  LOG       (default)
[Mon Apr 20 2020 02:19:07.420]  LOG      

[Mon Apr 20 2020 02:19:07.420]  LOG          Metadata:

[Mon Apr 20 2020 02:19:07.430]  LOG            creation_time   : 
[Mon Apr 20 2020 02:19:07.440]  LOG      2019-02-20T16:08:57.000000Z
[Mon Apr 20 2020 02:19:07.450]  LOG      

[Mon Apr 20 2020 02:19:07.470]  LOG            handler_name    : 
[Mon Apr 20 2020 02:19:07.480]  LOG      ISO Media file produced by Google Inc. Created on: 02/20/2019.
[Mon Apr 20 2020 02:19:07.490]  LOG      

[Mon Apr 20 2020 02:19:07.500]  LOG      Stream mapping:

[Mon Apr 20 2020 02:19:07.510]  LOG        Stream #0:0 -> #0:0
[Mon Apr 20 2020 02:19:07.510]  LOG       (h264 (native) -> mjpeg (native))
[Mon Apr 20 2020 02:19:07.520]  LOG      

[Mon Apr 20 2020 02:19:07.520]  LOG      Press [q] to stop, [?] for help

[Mon Apr 20 2020 02:19:07.530]  LOG      frame=    0 fps=0.0 q=0.0 size=N/A time=-577014:32:22.77 bitrate=N/A speed=N/A    
[Mon Apr 20 2020 02:19:07.540]  LOG      [graph 0 input from stream 0:0 @ 0x7b46bd44a280] sws_param option is deprecated and ignored

[Mon Apr 20 2020 02:19:07.540]  LOG      [swscaler @ 0x7b46bc1bd000] deprecated pixel format used, make sure you did set range correctly

[Mon Apr 20 2020 02:19:07.550]  LOG      Output #0, image2, to '/data/user/0/com.framebyframe/cache/fbfCache/out%03d.jpg':

[Mon Apr 20 2020 02:19:07.560]  LOG        Metadata:

[Mon Apr 20 2020 02:19:07.560]  LOG          major_brand     : 
[Mon Apr 20 2020 02:19:07.570]  LOG      mp42
[Mon Apr 20 2020 02:19:07.580]  LOG      

[Mon Apr 20 2020 02:19:07.590]  LOG          minor_version   : 
[Mon Apr 20 2020 02:19:07.620]  LOG      0
[Mon Apr 20 2020 02:19:07.630]  LOG      

[Mon Apr 20 2020 02:19:07.640]  LOG          compatible_brands: 
[Mon Apr 20 2020 02:19:07.650]  LOG      isommp42
[Mon Apr 20 2020 02:19:07.660]  LOG      

[Mon Apr 20 2020 02:19:07.670]  LOG          encoder         : 
[Mon Apr 20 2020 02:19:07.670]  LOG      Lavf58.35.101
[Mon Apr 20 2020 02:19:07.680]  LOG      

[Mon Apr 20 2020 02:19:07.690]  LOG          Stream #0:0
[Mon Apr 20 2020 02:19:07.700]  LOG      (und)
[Mon Apr 20 2020 02:19:07.710]  LOG      : Video: mjpeg, yuvj420p(pc), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s
[Mon Apr 20 2020 02:19:07.720]  LOG      , 
[Mon Apr 20 2020 02:19:07.730]  LOG      29.97 fps, 
[Mon Apr 20 2020 02:19:07.740]  LOG      29.97 tbn, 
[Mon Apr 20 2020 02:19:07.750]  LOG      29.97 tbc
[Mon Apr 20 2020 02:19:07.770]  LOG       (default)
[Mon Apr 20 2020 02:19:07.770]  LOG      

[Mon Apr 20 2020 02:19:07.780]  LOG          Metadata:

[Mon Apr 20 2020 02:19:07.790]  LOG            creation_time   : 
[Mon Apr 20 2020 02:19:07.800]  LOG      2019-02-20T16:08:57.000000Z
[Mon Apr 20 2020 02:19:07.810]  LOG      

[Mon Apr 20 2020 02:19:07.820]  LOG            handler_name    : 
[Mon Apr 20 2020 02:19:07.820]  LOG      ISO Media file produced by Google Inc. Created on: 02/20/2019.
[Mon Apr 20 2020 02:19:07.830]  LOG      

[Mon Apr 20 2020 02:19:07.840]  LOG            encoder         : 
[Mon Apr 20 2020 02:19:07.850]  LOG      Lavc58.65.102 mjpeg
[Mon Apr 20 2020 02:19:07.850]  LOG      

[Mon Apr 20 2020 02:19:07.860]  LOG          Side data:

[Mon Apr 20 2020 02:19:07.870]  LOG            
[Mon Apr 20 2020 02:19:07.880]  LOG      cpb: 
[Mon Apr 20 2020 02:19:07.890]  LOG      bitrate max/min/avg: 0/0/200000 buffer size: 0 
[Mon Apr 20 2020 02:19:07.900]  LOG      vbv_delay: N/A
[Mon Apr 20 2020 02:19:07.910]  LOG      

[Mon Apr 20 2020 02:19:07.504]  LOG      frame=    0 fps=0.0 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
[Mon Apr 20 2020 02:19:08.120]  LOG      frame=   10 fps= 10 q=17.3 size=N/A time=00:00:19.35 bitrate=N/A speed=19.3x    
[Mon Apr 20 2020 02:19:08.507]  LOG      frame=   60 fps= 40 q=24.8 size=N/A time=00:00:21.02 bitrate=N/A speed=  14x    
[Mon Apr 20 2020 02:19:09.900]  LOG      frame=   60 fps= 30 q=24.8 size=N/A time=00:00:21.02 bitrate=N/A speed=10.5x    
[Mon Apr 20 2020 02:19:09.510]  LOG      frame=   60 fps= 24 q=24.8 size=N/A time=00:00:21.02 bitrate=N/A speed=8.39x    
[Mon Apr 20 2020 02:19:10.900]  LOG      frame=   60 fps= 20 q=24.8 size=N/A time=00:00:21.02 bitrate=N/A speed=6.99x    
[Mon Apr 20 2020 02:19:10.181]  LOG      
[Mon Apr 20 2020 02:19:10.182]  LOG      frame=   60 fps= 19 q=24.8 Lsize=N/A time=00:00:21.02 bitrate=N/A speed=6.61x    

[Mon Apr 20 2020 02:19:10.183]  LOG      video:1302kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 
[Mon Apr 20 2020 02:19:10.183]  LOG      unknown
`

**Environment**
 - react-native 0.62.2
- react-native-ffmpeg 0.4.4 min-lts

**Other**

**Comment by tanersener** [comment]
Can you try adding `,setpts=PTS-STARTPTS` after `select` filter?

**Comment by ahmetbicer** [comment]
I used it like this, but output doesn't change. 
`RNFFmpeg.execute("-i ${this.state.videoPath} -vf select='between(t\\,19\\,20)',setpts=PTS-STARTPTS -vsync 0 ${RNFS.CachesDirectoryPath}/fbfCache/out%03d.jpg")`

I would like to add something i don't know is this right approach to do when trying to extract all frames from x to y second. So if you have any other suggestion for doing this i would like to try it. Thank you for quick reply by the way!

**Comment by tanersener** [comment]
`t` in `between(t\\,19\\,21)` is time, for frame numbers you need to use `n`. Did you try with `n` too?

**Comment by ahmetbicer** [comment]
Yes, I use `n` too but it doesn't change the output. When i look to logs i see

`[Mon Apr 20 2020 11:23:03.675]  LOG      , start: 0.000000`

Start is set to 0, i think if i could change this time it will solve my problem.

**Comment by tanersener** [comment]
I don't agree. That log line is just statistics.

Anyway, tested your command with the latest released versions. Both `t` and `n` works as expected. You should be something wrong.

**Comment by ahmetbicer** [comment]
Can you provide the command that you used? I would like to try it.

**Comment by tanersener** [comment]
Exactly the same command as yours :) How can I validate it by running another command?

`
 -i /data/user/0/com.arthenica.reactnative.ffmpeg.test/cache/1.mp4 -vf select='between(n\,19\,20)' -vsync 0 /sdcard/Download/out%03d.jpg
`

**Comment by ahmetbicer** [comment]
Okay this was a strange one. It was a issue in the android emulator. I am deleting the cache folder that i export the frames between my tryings so i can see the last output. When you say it works as expected i tried with other video but i see the frames from the last video. I restart the android emulator and it shows me the right frames. So I am sorry about your time. This is a fantastic library!. 

I have one last question about other topic i look to the ffmpeg documentations but i couldn't find any source. Is it possible to get the frames as base64 strings? or any other solutions to get the frames without saving to filesystem?

Thank you so much!

**Comment by tanersener** [comment]
It is not possible as far as I know. If your output was a single file then I would recommend using a pipe, you can read it like a file, but for multiple output files case I don't have a solution.

**Comment by ahmetbicer** [comment]
Thank you so much for your time and support! I am closing this issue.
