### ISSUE TITLE
IOS Release Build Fails - Thread-Local storage not supported and Parse Issue

### ISSUE THREAD

**Issue by enigmablue** [tanersener/react-native-ffmpeg#163]
Hey,

Thanks for the package. It works well on debug. But when i tried to build release it failed :(
I tried it on a completely new repo: https://github.com/enigmablue/new_test_ffmpeg.git

![image](https://user-images.githubusercontent.com/35584085/82768298-c6591f80-9e60-11ea-8523-39838270cfe3.png)

The error isn't super meaningful for me and i couldn't find any other ideas.

Could you give me some tips / ideas? Thanks!

PS on a side note, a completely new install gives me an error when i build on CLI (i needed to do this because i use appcenter). I had to switch to https-lts.

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_MobileFFprobe", referenced from:
      objc-class-ref in libreact-native-ffmpeg.a(RNFFmpegModule.o)
  "_OBJC_CLASS_$_MobileFFmpeg", referenced from:
      objc-class-ref in libreact-native-ffmpeg.a(RNFFmpegModule.o)
  "_OBJC_CLASS_$_MobileFFmpegConfig", referenced from:
      objc-class-ref in libreact-native-ffmpeg.a(RNFFmpegModule.o)
  "_OBJC_CLASS_$_ArchDetect", referenced from:
      objc-class-ref in libreact-native-ffmpeg.a(RNFFmpegModule.o)
ld: symbol(s) not found for architecture armv7

**Environment**
"react-native": "0.62.2",
my IOS deployment target is on 10.0

**Comment by tanersener** [comment]
There are similar issues created before. Why don't you search for them.

**Comment by enigmablue** [comment]
oh sorry i just double checked and saw #148 
thanks
