### ISSUE TITLE
APK size

### ISSUE THREAD

**Issue by sudovijay** [tanersener/react-native-ffmpeg#17]
Hey firstly thanks for this awesome lib. but even with minimal config the apk size goes 25 MB, is there any way we could reduce that? i even tried to rebuild custom libs with android.sh you have in MobileFFmpeg but that just failed for me on step FFMPEG. it'll be great if you can help with this.

**Comment by tanersener** [comment]
I guess you mean `min` package. Unfortunately it is the smallest binary package. If you need a smaller package then you must build your own `MobileFFmpeg` package.

**Comment by sudovijay** [comment]
yes i meant `min` anyway how to use that `MobileFFmpeg` build with this? can you tell me bit more about it?

**Comment by sudovijay** [comment]
Still stuck with this, sorry for reopening this . just not able to make custom `mobile-ffmpeg.aar` work along with `react-native-ffmpeg` ,  did tried quite a things just not able to make them work together. will appreciate some help ..

**Comment by tanersener** [comment]
Is there an error somewhere?

**Comment by sudovijay** [comment]
just not able to implement it, `error: cannot find symbol import com.arthenica.RNFFmpegPackage;`, custom aar is so confusing, sorry for asking too many questions. it just all kinda new for me

**Comment by tanersener** [comment]
I'd like to help if I can, but you need to give some details.

For example at which step you get `error: cannot find symbol import com.arthenica.RNFFmpegPackage;` error? This error is about the `react-native` package and has nothing to do with `.aar` file.

**Comment by sudovijay** [comment]
will give few shots today :) probably need to get into native modules too,  you have a good weekend bud :)

**Comment by issamabdelkrim** [comment]
@sudovijay 
please you can show me the step to do this 
thanks

**Comment by relivetech** [comment]
@sudovijay
please you can show me the step to do this
thanks
