### ISSUE TITLE
Is there any way to get thumbnail from a video? I'm stuck

### ISSUE THREAD

**Issue by amanfcp** [tanersener/react-native-ffmpeg#172]

**Comment by Veuge** [comment]
I've done this with `executeWithArguments`
```
RNFFmpeg.executeWithArguments(["-i", "inputVideo.mp4", "-ss", "00:00:00.100", "-vframes", "1", "thumbnail.jpeg"])
    .then(result => console.log(result));
```

Check https://networking.ringofsaturn.com/Unix/extractthumbnail.php

**Comment by amanfcp** [comment]
> I've done this with `executeWithArguments`
> 
> ```
> RNFFmpeg.executeWithArguments(["-i", "inputVideo.mp4", "-ss", "00:00:00.100", "-vframes", "1", "thumbnail.jpeg"])
>     .then(result => console.log(result));
> ```
> 
> Check https://networking.ringofsaturn.com/Unix/extractthumbnail.php

Thanks, I'll try this. Though I was able to get it through react-native-thumbnail
