### ISSUE TITLE
How i can save video after trim?

### ISSUE THREAD

**Issue by Adigezalov** [tanersener/react-native-ffmpeg#173]
Help me please.
How i can save video after

`RNFFmpeg.execute("-i ${filePath} -vf trim=60:120")`

In general, I need to send the video after trimming to the server

**Comment by Adigezalov** [comment]
> Help me please.
> How i can save video after
> 
> `RNFFmpeg.execute(`-i ${filePath} -vf trim=60:120`)`
> 
> In general, I need to send the video after trimming to the server

**Comment by nivas412** [comment]
Hi Is it working fine now ??

**Comment by nivas412** [comment]
> Hi Is it working fine now ??

If yes please let me know how ??
