### ISSUE TITLE
How can I trim a video in time without losing its resolution?

### ISSUE THREAD

**Issue by Adigezalov** [tanersener/react-native-ffmpeg#175]
How can I trim a video in time without losing its resolution?
For example, if I discard a vertiсal video with the `trim` command, then everything is fine, but the quality is lost, if you cut it through an `-i input.mp4 -t 30 -acodec copy -vcodec copy output.mp4` the quality remains, but the video resolution is rotated

**Comment by tanersener** [comment]
You're not specifying a video codec for your output file. In those situations `ffmpeg` chooses the best encoder available. The best doesn't always mean the best in quality. 

What you need to do is:
1 - Check the video codec used in your input video using `ffprobe`
2 (Optional) - Check the video codec used in your trimmed video using `ffprobe` 
3 - Update your command to encode your video using video codec found in step 1.

**Comment by Adigezalov** [comment]
I understand this, but if I put a copy of the codec into the code
`-i input.mp4 -vf trim=0:30 -c:v copy output.mp4`
I get an error
`Filtergraph 'trim=0:30' was defined for video output stream 0:0 but codec copy was selected. Filtering and streamcopy cannot be used together.`
If i use
`-i input.mp4 -t 30 -c:v copy output.mp4`
then for some reason the video is not 1920x1080 but 1080x1920

**Comment by Codeskiin** [comment]
@Adigezalov , you can use -qscale 0 option before output.mp4
