### ISSUE TITLE
Build getting failed throwing error can someone help me please

### ISSUE THREAD

**Issue by nivas412** [tanersener/react-native-ffmpeg#178]
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.arthenica:mobile-ffmpeg-com.febbler:4.3.1.

**Comment by tanersener** [comment]
`reactNativeFFmpegPackage` should include a react native package name not your app package.

```
ext {
    reactNativeFFmpegPackage = "<react native package name>"
}
```

**Comment by nivas412** [comment]
I have added this still getting failed 

buildscript {
    ext {
        compileSdkVersion = 29
        buildToolsVersion =  "26.0.0"       
        minSdkVersion = 15        
        targetSdkVersion = 29
        reactNativeFFmpegPackage = "com.febbler"
    }
}

**Comment by tanersener** [comment]
I can't guess the error without seeing the `gradle` output.

**Comment by nivas412** [comment]
G:\Fabbler\Febbler\android>gradlew build
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

> Configure project :react-native-reanimated
WARNING: The specified Android SDK Build Tools version (26.0.0) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.5.2.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.0'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.arthenica:mobile-ffmpeg-com.febbler:4.3.1.
     Searched in the following locations:
       - file:/C:/Users/NIVAS/.m2/repository/com/arthenica/mobile-ffmpeg-com.febbler/4.3.1/mobile-ffmpeg-com.febbler-4.3.1.pom
       - file:/G:/Fabbler/Febbler/node_modules/react-native/android/com/arthenica/mobile-ffmpeg-com.febbler/4.3.1/mobile-ffmpeg-com.febbler-4.3.1.pom
       - file:/G:/Fabbler/Febbler/node_modules/jsc-android/dist/com/arthenica/mobile-ffmpeg-com.febbler/4.3.1/mobile-ffmpeg-com.febbler-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-com.febbler/4.3.1/mobile-ffmpeg-com.febbler-4.3.1.pom
       - https://jcenter.bintray.com/com/arthenica/mobile-ffmpeg-com.febbler/4.3.1/mobile-ffmpeg-com.febbler-4.3.1.pom
       - https://www.jitpack.io/com/arthenica/mobile-ffmpeg-com.febbler/4.3.1/mobile-ffmpeg-com.febbler-4.3.1.pom
     Required by:
         project :app > project :react-native-ffmpeg

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 22s

**Comment by nivas412** [comment]
After updated build version to 28.0.3 next logs :


Creating configuration testReleasePublish
Creating configuration testReleaseProvided
Creating configuration testReleaseApi
Creating configuration testReleaseImplementation
Creating configuration testReleaseRuntimeOnly
Creating configuration testReleaseCompileOnly
Creating configuration testReleaseWearApp
Creating configuration testReleaseAnnotationProcessor
All projects evaluated.
Selected primary task 'build' from project :
Resource missing. [HTTP GET: https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-com.febbler/4.3.1/mobile-ffmpeg-com.febbler-4.3.1.pom]
Resource missing. [HTTP GET: https://repo.jfrog.org/artifactory/libs-release-bintray/com/arthenica/mobile-ffmpeg-com.febbler/4.3.1/mobile-ffmpeg-com.febbler-4.3.1.pom?referrer]
Resource missing. [HTTP GET: https://www.jitpack.io/com/arthenica/mobile-ffmpeg-com.febbler/4.3.1/mobile-ffmpeg-com.febbler-4.3.1.pom]
Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/com/arthenica/mobile-ffmpeg-com.febbler/4.3.1/mobile-ffmpeg-com.febbler-4.3.1.pom]
Resource missing. [HTTP GET: https://dl.google.com/dl/android/maven2/com/arthenica/mobile-ffmpeg-com.febbler/4.3.1/mobile-ffmpeg-com.febbler-4.3.1.pom]

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-ffmpeg:compileReleaseAidl'.
> Could not resolve all task dependencies for configuration ':react-native-ffmpeg:releaseCompileClasspath'.
   > Could not find com.arthenica:mobile-ffmpeg-com.febbler:4.3.1.
     Required by:
         project :react-native-ffmpeg

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 56s   

I hope this might be help to understand whats actual issues

**Comment by tanersener** [comment]
Please read my first post. `reactNativeFFmpegPackage` should include a react native package name not your application package.

**Comment by nivas412** [comment]
Thanks for your patience, I am new t react unable to understand what exactly need to do can you please elaborated clearly.

**Comment by tanersener** [comment]
Please remove `reactNativeFFmpegPackage = "com.febbler"` from your `build.gradle`. You don't need to set `reactNativeFFmpegPackage` by default.

You only need it if you want to use another `react-native-ffmpeg` package. When you need it then use one of the `react-native-ffmpeg` packages. They are listed in the README.

```
reactNativeFFmpegPackage = "min"
reactNativeFFmpegPackage = "https"
reactNativeFFmpegPackage = "full"
```

**Comment by nivas412** [comment]
Thank you so much for your quick response, patience and finally talent. it worked for me now. Thanks a lot.
