### ISSUE TITLE
iOS Release build error: Thread-local storage is not supported for the current target

### ISSUE THREAD

**Issue by dirkpostma** [tanersener/react-native-ffmpeg#182]
**Description**
Using blank React Native project, 0.62.2 when building a Release variant iOS, a build error occurs:

`Thread-local storage is not supported for the current target`

**Expected behavior**
I would expect build to run without errors.

**Current behavior**
When

- start a blank react native project (0.62.2) and add this library, like this:

```
npx react-native init TestFfmpeg --template react-native-template-typescript
cd TestFfmpeg
yarn add react-native-ffmpeg
open ios/TestFfmpeg.xcworkspace
```

- change first line of Podfile from `platform :ios, '9.0'` to `platform :ios, '9.3'`

- run `cd ios; pod install; cd ..`

- In xCode, change build configuration to Release (CMD-SHIFT-<)

- build

Then the following build errors occurs:

```
***/TestFfmpeg/ios/Pods/mobile-ffmpeg-https/mobileffmpeg.framework/Headers/mobileffmpeg_exception.h:27:8: Thread-local storage is not supported for the current target

***/TestFfmpeg/node_modules/react-native-ffmpeg/ios/RNFFmpegModule.h:26:9: Could not build module 'mobileffmpeg'
```

**Screenshots**
Not applicable

**Logs**
See above

**Environment**

```
yarn react-native info
yarn run v1.22.4
$ ***/TestFfmpeg/node_modules/.bin/react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 590.40 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.14.2 - /var/folders/p8/lc8f03hj4glfwjx1c0_39d8w0000gn/T/yarn--1594364212507-0.1767762668618864/node
    Yarn: 1.22.4 - /var/folders/p8/lc8f03hj4glfwjx1c0_39d8w0000gn/T/yarn--1594364212507-0.1767762668618864/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/****/.gem/ruby/2.4.9/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 19, 23, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.3, 30.0.0
      System Images: android-19 | Google APIs Intel x86 Atom, android-21 | Intel x86 Atom, android-21 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
✨  Done in 3.80s.
```

**Other**
thread_local is not supported on i386 architecture. Could that be a hint to solution?

**Comment by tanersener** [comment]
There are similar issues reported before. Please search for them and try to apply solutions given there.

**Comment by dirkpostma** [comment]
The README states that this library support iOS 9.3 and above. I already tried increasing the deployment target to 9.3, include script to set deployment target of all pods to 9.3, but this appears not be be high enough. Which made me file this issue.

Is it true that the README is incorrect? Should 9.3 be changed to 10.0?

And I would also suggest to let users add this to the Podfile:

```
post_install do |installer|
   installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
     end
   end
 end
```

Do you agree?

**Comment by dirkpostma** [comment]
By coincedence, the React Native team has just published React Native 0.63.0 and the typescript template is published this our :)

If you run this:

```
npx react-native init TestFfmpeg --template react-native-template-typescript
cd TestFfmpeg
yarn add react-native-ffmpeg
cd ios; pod install; cd ..
open ios/TestFfmpeg.xcworkspace
```

...works out of the box!

Since React Native 0.63 has dropped iOS 9 support, the suggest change of Podfile is no longer necessary :)

**Comment by tanersener** [comment]
> Do you agree with these README change suggetions?

No. ` Thread-local storage is not supported for the current target` message is generated by iOS, not by `react-native-ffmpeg`. iOS generates this warning when the deployment target is not supporting thread locals. Since we know that iOS 9.3 supports thread locals, your problem should be coming from something else.

Please take a look at official test applications under the [react-native-ffmpeg-test](https://github.com/tanersener/react-native-ffmpeg-test) repository. They are all working fine with `9.3`.

**Comment by dirkpostma** [comment]
These examples use React Native 0.61.x. I could test again with React Native 0.62, but I think not worth the time as problems are solved with React Native 0.63 anyway.

Issue closed.

**Comment by dirkpostma** [comment]
Did some more testing. I think your overlook the fact that the error occurs with *release* build only.

I just tested default of react-native-ffmpeg-test

```
git clone git@github.com:tanersener/react-native-ffmpeg-test.git
cd react-native-ffmpeg-test/default
yarn
cd ios; pod install; cd ..; say ready
open ios/ReactNativeFFmpegTest.xcworkspace
```

Build *Release* configuration

=> error

So.. may be worth to look at it anyway?

**Comment by tanersener** [comment]
After publishing a new `react-native-ffmpeg` version, I'm validating that test applications can be built using both build types (debug, release). `v0.4.4` was tested and validated in the same way. Please take a look at this video, https://www.dropbox.com/s/sg4hs3696e8ammq/issue-182-screenshot-capture.mov?dl=0.

Remember that this issue occurs because `react-native` and `cocoapods` don't always generate the correct deployment target for applications. This is why so people receive `Thread-local storage is not supported for the current target` error. There is no other way than manually updating deployment targets. Using a `post_install` step works for you but doesn't work for me. Additionally, this is issue is not specific to `react-native-ffmpeg` only. There are other projects which suffer from the same issue as well.

**Comment by DISKONEKTeD** [comment]
i get this error on a fresh installation, but on react 60.6 (since I'm trying to migrate my code base on a large project, after the auto linking has failed). target is 9.3. version 0.4.4. I might just downgrade to see if that works for me instead.

**Comment by tanersener** [comment]
@DISKONEKTeD I believe I explained why this error happens and what must be done to fix it.

**Comment by JerakRus** [comment]
@tanersener 
This does not work. I am using react-native 0.63.2. Target everywhere 10.0. If the "Release" mod is set to "run" in the assembly scheme, the application is not going to. If the "Debug" mod is okay. Why does the error depend on the build mode?

**Comment by blobrfish** [comment]
@DISKONEKTeD I'm having  the same issue. Did you manage suceed with the build release?

**Comment by pheuter** [comment]
A solution for the problem of Release configuration builds breaking while Debug working was to make sure you set **Build Active Architecture Only=YES** for the **Pods** project:

<img width="1070" alt="Screen Shot 2021-09-03 at 9 51 07 AM" src="https://user-images.githubusercontent.com/92698/132016834-e78c70de-1613-4c70-8bdf-6682a2a4523e.png">
