### ISSUE TITLE
Failed to build when running ./gradlew assembleAndroidTest on task :react-native-ffmpeg:mergeDebugAndroidTestNativeLibs

### ISSUE THREAD

**Issue by scottbass47** [tanersener/react-native-ffmpeg#187]
**Description**
When running the `gradlew` target `assembleAndroidTest`, the build failed on task `:react-native-ffmpeg:mergeDebugAndroidTestNativeLibs`

**Expected behavior**
The build should succeed.

**Current behavior**
The build fails.

**Logs**
```
> Task :react-native-ffmpeg:mergeDebugAndroidTestNativeLibs FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-ffmpeg:mergeDebugAndroidTestNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'lib/x86/libc++_shared.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake
```

**Environment**
Not sure what to include here.

I will happily update the issue with more details including environment info. I'm sorry if this isn't the right spot to post the issue, I'm new to RN and RN-ffmpeg.

**Comment by tanersener** [comment]
See [Tips](https://github.com/tanersener/react-native-ffmpeg#6-tips).

**Comment by scottbass47** [comment]
Hmmm I see what tip you're referring to, it looks like I already had those `pickFirst` statements in my `build.gradle`. I'm wondering if the gradle target `assembleAndroidTest` is looking elsewhere to do the building, but that doesn't make sense. I'll keep digging but if you have any ideas I'd love to hear them!

**Comment by iansielecki** [comment]
Hi @scottbass47 have you fixed this? I'm having the same scenario as you
