### ISSUE TITLE
[Android] Unable to record Screen in android using ffmpeg

### ISSUE THREAD

**Issue by manikandasankar** [tanersener/react-native-ffmpeg#19]
I am getting the following error when trying to record android screen, it works fine when the command is executed from the shell.

Command: **-f fbdev -i /dev/graphics/fb0 -f flv <rtmp_server_addr>**

Could not open framebuffer device **'/dev/graphics/fb0': Permission denied**

**Comment by manikandasankar** [comment]
I connected to the android device using adb and used adb shell command to land on the android shell.

**Comment by tanersener** [comment]
It looks like a permission error. 

What happens when you run `ffmpeg -f fbdev -i /dev/graphics/fb0 -f flv <rtmp_server_addr>` command inside an application without `react-native-ffmpeg`.

**Comment by manikandasankar** [comment]
I am getting the same permission error

**Comment by tanersener** [comment]
This shows that, at least, error is not caused by `react-native-ffmpeg`. 

Well, I don't have an answer right now. Let me search this issue in Android documentation.

**Comment by manikandasankar** [comment]
Thanks!. I would be great if you find any solution for this.

**Comment by tanersener** [comment]
According to [Android documentation](https://developer.android.com/reference/android/Manifest.permission), an application needs `android.permission.READ_FRAME_BUFFER` permission to access frame buffer data (`/dev/graphics/fb0`). 

Unfortunately `android.permission.READ_FRAME_BUFFER` is `Not for use by third-party applications`. You can't add it to your `AndroidManifest.xml` and you'll get `Permission is only granted to system apps` error if you try. That means your application must be signed by the same key as the Android system ROM.

As far as I understand, another option to access `/dev/graphics/fb0` is running application as `root`. I think this why you were successful when you run `ffmpeg -f fbdev -i /dev/graphics/fb0 -f flv <rtmp_server_addr>` command from adb shell. Maybe if you run your application on a rooted devices then it will work. But this is not an acceptable solution for this issue.

So I think it is not possible to access frame buffer data from an application.

Other references I found about this issue:
https://stackoverflow.com/questions/12462944/how-to-take-a-screenshot-of-other-app-programmatically-without-root-permission
https://techicraze.wordpress.com/2016/05/27/access-your-android-framebuffer/
https://groups.google.com/forum/#!topic/android-platform/8Mg3gsF92xo
