### ISSUE TITLE
permission is denied using Android Q ffmpeg": error=13, Permission denied

### ISSUE THREAD

**Issue by nivas412** [tanersener/react-native-ffmpeg#190]
**Description**
Google doesn't allow apps to run binary files from /data/user directory.

One bad solution that I know is to change compileSdkVersion and targetSdkVersion to 28 or below and re-release my application which is not recommended.

**Expected behavior**
it should execute without permission denied error

**Current behavior**
permission denied  error getting

**Screenshots**

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
"react-native": "0.63.1",
"react-native-ffmpeg": "^0.4.4",

**Other**
only for android 10 having the issue when the app in target SDK 29

**Comment by ahmadzahidglixen** [comment]
@nivas412 Hey!

Can you explain this part:
Moved FFmpeg binary to the libs folder 

Thanks
