### ISSUE TITLE
ffmpeg - Not working on IOS project but working on new project

### ISSUE THREAD

**Issue by JeyShah** [tanersener/react-native-ffmpeg#191]
Hi, i tried this library to run on Android and iOS devices, on Android its working fine but on iOS its giving me error like 
**WARNING: library configuration mismatch** and **rc:1** and also showing this error at the end of the log
"**Unable to find a suitable output format for**"

NOTE: 
Its working fine on android but not on iOS. and when i create new project and try to run same command it works fine. 

Command:
let directoryName = 'videoTest';

const DirectoryPath = RNFS.CachesDirectoryPath + '/' + directoryName;

let videoToFilter = "file:///Users/frs/Library/Developer/CoreSimulator/Devices/5DDB9176-7127-4275-8B92-DD98C75A8C4D/data/Containers/Data/Application/DE162C1D-A9DE-4781-B8E1-2005A65F66F1/Documents/videos/trim.957EAA96-1F36-46AE-A83E-EA81BF6F010E.MOV"

let startTime = 1;
let stopTime = 10;

let outputFile = 'file://' + `${DirectoryPath}` + '/' + new Date().getTime() + 'output.mp4';

RNFFmpeg.executeWithArguments(["-i", videoToFilter, "-ss", `${startTime}`, "-t", `${stopTime}`, `${outputFile}`, "-y", "-c", "copy"]).then(result => {

Here are the logs: 

ffmpeg version git-2020-01-25-fd11dd500
[Mon Aug 24 2020 11:17:38.180]  LOG       Copyright (c) 2000-2020 the FFmpeg developers
[Mon Aug 24 2020 11:17:38.183]  LOG      

[Mon Aug 24 2020 11:17:38.217]  LOG        built with Apple clang version 11.0.0 (clang-1100.0.33.17)

[Mon Aug 24 2020 11:17:38.265]  LOG        configuration: --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk --prefix=/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-apple-darwin/ffmpeg --enable-version3 --arch=x86_64 --cpu=x86_64 --target-os=darwin --ar=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar --cc=clang --cxx=clang++ --as='clang -arch x86_64 -target x86_64-ios-darwin -march=x86-64 -msse4.2 -mpopcnt -m64 -mtune=intel -DMOBILE_FFMPEG_X86_64 -Wno-unused-function -Wno-deprecated-declarations -fstrict-aliasing -DIOS -DMOBILE_FFMPEG_BUILD_DATE=20200125 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -O2 -mios-simulator-version-min=12.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/include' --ranlib=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib --strip=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip --disable-neon --enable-cross-compile --enable-pic --enable-asm --enable-inline-asm --enable-optimizations --enable-swscale --enable-static --disable-shared --enable-small --disable-v4l2-m2m --disable-outdev=v4l2 --disable-outdev=fbdev --disable-indev=v4l2 --disable-indev=fbdev --disable-openssl --disable-xmm-clobber-test --disable-debug --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --disable-appkit --disable-alsa --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --enable-gmp --enable-gnutls --disable-sdl2 --enable-zlib --enable-audiotoolbox --enable-coreimage --enable-bzlib --enable-videotoolbox --enable-avfoundation --enable-iconv

[Mon Aug 24 2020 11:17:38.271]  LOG        WARNING: library configuration mismatch

[Mon Aug 24 2020 11:17:38.273]  LOG        avutil      configuration: NodeMedia Build 1

[Mon Aug 24 2020 11:17:38.276]  LOG        avcodec     configuration: NodeMedia Build 1

[Mon Aug 24 2020 11:17:38.277]  LOG        avformat    configuration: NodeMedia Build 1

[Mon Aug 24 2020 11:17:38.278]  LOG        swscale     configuration: NodeMedia Build 1

[Mon Aug 24 2020 11:17:38.279]  LOG        swresample  configuration: NodeMedia Build 1

[Mon Aug 24 2020 11:17:38.286]  LOG        libavutil      56. 38.100 / 56. 22.100

[Mon Aug 24 2020 11:17:38.287]  LOG        libavcodec     58. 65.102 / 58. 35.100

[Mon Aug 24 2020 11:17:38.287]  LOG        libavformat    58. 35.101 / 58. 20.100

[Mon Aug 24 2020 11:17:38.288]  LOG        libavdevice    58.  9.103 / 58.  9.103

[Mon Aug 24 2020 11:17:38.289]  LOG        libavfilter     7. 70.101 /  7. 70.101

[Mon Aug 24 2020 11:17:38.307]  LOG        libswscale      5.  6.100 /  5.  3.100

[Mon Aug 24 2020 11:17:38.309]  LOG        libswresample   3.  6.100 /  3.  3.100

[Mon Aug 24 2020 11:17:38.310]  LOG      Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:///Users/frs/Library/Developer/CoreSimulator/Devices/5DDB9176-7127-4275-8B92-DD98C75A8C4D/data/Containers/Data/Application/DE162C1D-A9DE-4781-B8E1-2005A65F66F1/Documents/videos/trim.957EAA96-1F36-46AE-A83E-EA81BF6F010E.MOV':

[Mon Aug 24 2020 11:17:38.310]  LOG        Metadata:

[Mon Aug 24 2020 11:17:38.311]  LOG          major_brand     : 
[Mon Aug 24 2020 11:17:38.312]  LOG      qt  
[Mon Aug 24 2020 11:17:38.314]  LOG      

[Mon Aug 24 2020 11:17:38.316]  LOG          minor_version   : 
[Mon Aug 24 2020 11:17:38.318]  LOG      0
[Mon Aug 24 2020 11:17:38.321]  LOG      

[Mon Aug 24 2020 11:17:38.344]  LOG          compatible_brands: 
[Mon Aug 24 2020 11:17:38.352]  LOG      qt  
[Mon Aug 24 2020 11:17:38.353]  LOG      

[Mon Aug 24 2020 11:17:38.354]  LOG          creation_time   : 
[Mon Aug 24 2020 11:17:38.354]  LOG      2020-08-24T06:16:33.000000Z
[Mon Aug 24 2020 11:17:38.355]  LOG      

[Mon Aug 24 2020 11:17:38.356]  LOG        Duration: 
[Mon Aug 24 2020 11:17:38.357]  LOG      00:00:30.36
[Mon Aug 24 2020 11:17:38.367]  LOG      , start: 
[Mon Aug 24 2020 11:17:38.369]  LOG      0.000000
[Mon Aug 24 2020 11:17:38.374]  LOG      , bitrate: 
[Mon Aug 24 2020 11:17:38.374]  LOG      752 kb/s
[Mon Aug 24 2020 11:17:38.381]  LOG      

[Mon Aug 24 2020 11:17:38.382]  LOG          Stream #0:0
[Mon Aug 24 2020 11:17:38.384]  LOG      (und)
[Mon Aug 24 2020 11:17:38.387]  LOG      : Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 2 kb/s
[Mon Aug 24 2020 11:17:38.390]  LOG       (default)
[Mon Aug 24 2020 11:17:38.391]  LOG      

[Mon Aug 24 2020 11:17:38.392]  LOG          Metadata:

[Mon Aug 24 2020 11:17:38.393]  LOG            creation_time   : 
[Mon Aug 24 2020 11:17:38.396]  LOG      2020-08-24T06:16:33.000000Z
[Mon Aug 24 2020 11:17:38.397]  LOG      

[Mon Aug 24 2020 11:17:38.398]  LOG            handler_name    : 
[Mon Aug 24 2020 11:17:38.399]  LOG      Core Media Audio
[Mon Aug 24 2020 11:17:38.403]  LOG      

[Mon Aug 24 2020 11:17:38.404]  LOG          Stream #0:1
[Mon Aug 24 2020 11:17:38.405]  LOG      (eng)
[Mon Aug 24 2020 11:17:38.406]  LOG      : Video: h264 (avc1 / 0x31637661), yuv420p(tv, smpte170m/smpte170m/bt709), 224x480 [SAR 1:1 DAR 7:15], 745 kb/s
[Mon Aug 24 2020 11:17:38.407]  LOG      , 
[Mon Aug 24 2020 11:17:38.407]  LOG      24.97 fps, 
[Mon Aug 24 2020 11:17:38.408]  LOG      25 tbr, 
[Mon Aug 24 2020 11:17:38.416]  LOG      25k tbn, 
[Mon Aug 24 2020 11:17:38.417]  LOG      50k tbc
[Mon Aug 24 2020 11:17:38.418]  LOG       (default)
[Mon Aug 24 2020 11:17:38.418]  LOG      

[Mon Aug 24 2020 11:17:38.419]  LOG          Metadata:

[Mon Aug 24 2020 11:17:38.432]  LOG            creation_time   : 
[Mon Aug 24 2020 11:17:38.433]  LOG      2020-08-24T06:16:33.000000Z
[Mon Aug 24 2020 11:17:38.439]  LOG      

[Mon Aug 24 2020 11:17:38.441]  LOG            handler_name    : 
[Mon Aug 24 2020 11:17:38.450]  LOG      Core Media Video
[Mon Aug 24 2020 11:17:38.457]  LOG      

[Mon Aug 24 2020 11:17:38.458]  LOG            encoder         : 
[Mon Aug 24 2020 11:17:38.459]  LOG      H.264
[Mon Aug 24 2020 11:17:38.460]  LOG      

[Mon Aug 24 2020 11:17:38.463]  LOG      Unable to find a suitable output format for 'file://Users/frs/Library/Developer/CoreSimulator/Devices/5DDB9176-7127-4275-8B92-DD98C75A8C4D/data/Containers/Data/Application/DE162C1D-A9DE-4781-B8E1-2005A65F66F1/Library/Caches/videoTest/1598249858129output.mp4'

[Mon Aug 24 2020 11:17:38.464]  LOG      file://Users/frs/Library/Developer/CoreSimulator/Devices/5DDB9176-7127-4275-8B92-DD98C75A8C4D/data/Containers/Data/Application/DE162C1D-A9DE-4781-B8E1-2005A65F66F1/Library/Caches/videoTest/1598249858129output.mp4: Invalid argument

**Comment by tanersener** [comment]
You have multiple `ffmpeg` implementations in your app. The other one is `NodeMedia` I guess. They're clashing with each other. That's why you have `library configuration mismatch` warning. Your application may not work as expected.

Besides, you can try removing `file://` schema to resolve other errors.

**Comment by JeyShah** [comment]
Hi @tanersener , Thank you so much, its working after removing react-native-nodemediaclient from the project. But is there anyway i can use react-native-nodemediaclient and react-native-ffmpeg both? Thank you again for your quick response.

**Comment by tanersener** [comment]
I don't know. `react-native-nodemediaclient` doesn't tell anything about `ffmpeg` on their project page. It's hard to tell what they're doing.

**Comment by JeyShah** [comment]
Thank you so much. You saved my day. Have a good day. Cheers
