### ISSUE TITLE
Convert .m4a file to .mp3

### ISSUE THREAD

**Issue by kecsou** [tanersener/react-native-ffmpeg#193]
I am looking for a way to convert an .m4a file to .mp3
**Expected behavior**
What you expected to happen.

What happened.
I got "for option 'vn': Option not found" trying this command
RNFFprobe.executeWithArguments([ '-i', uri, '-b:a', '192k', '-vn', mp3Uri]);

And I got  " Failed to set value 'libmp3lame' for option 'acodec': Option not found" using this one
RNFFprobe.executeWithArguments([ '-i', uri, '-acodec', 'libmp3lame', '-aq', 2, mp3Uri]);

 - React Native Environment Info
Using react-native sdk 28 on android

**Comment by tanersener** [comment]
`lame` is not enabled in the default `react-native-ffmpeg` package. 

See which packages include `lame` from [1. Features](https://github.com/tanersener/react-native-ffmpeg#1-features) and use one of those packages using instructions given in [2.3 Packages](https://github.com/tanersener/react-native-ffmpeg#23-packages).
