### ISSUE TITLE
[Questions] How to install ffmpeg ver 4.3?

### ISSUE THREAD

**Issue by Rotemy** [tanersener/react-native-ffmpeg#194]
Hi, love this library!

I have 2 questions:

1. I see on the docs that this library supports v4.1, v4.2 and v4.3-dev releases. How do I choose which version to install? Can I install an LTS version but with v4.3?
2. When are you planning to support ver 4.3.1 which is the latest and stable version of ffmpeg?

Thanks

**Comment by tanersener** [comment]
[4.1 Releases](https://github.com/tanersener/react-native-ffmpeg#41-releases) section lists which `FFmpeg` branches are supported by each plugin line. Unfortunately, it doesn't include `ffmpeg` version details for each plugin version. I'll try to add them in the next doc update.

Current version `v0.4.4` is already based on `ffmpeg v4.3.x`. But it is different than the `4.3.1` version released on `ffmpeg.org`. Its exact version is `4.3-dev-1944`. `react-native-ffmpeg` does not depend on point releases published. It uses the source code published on `ffmpeg` master branch. It is the version supported by `ffmpeg` developers.

The plan is to release the next version before `October`.

**Comment by Rotemy** [comment]
@tanersener thansk!
