### ISSUE TITLE
Documentation - Video Compression & Trimming

### ISSUE THREAD

**Issue by ahmadzahidglixen** [tanersener/react-native-ffmpeg#195]
**Issue**
Hi all, is there any documentation available on how to use this library to compress & trim a video?

**Comment by NooruddinLakhani** [comment]
This will trim the input video from start and cut 2.5 seconds

```
const qScale = 5;
RNFFmpeg.execute(
        `-y -i input.mkv -ss 00:00:02.500 -vcodec mpeg4 -acodec aac -qscale:v ${qScale} -q:a 4 -filter:v "hflip" -ac 2 output.mkv`,
      ).then(result => {
        console.log(`FFmpeg process exited withgivity rc: ${result.rc}`);

        if (result.rc === 0) {
          // output.mkv
        }
});
```
Some reference I got [A quick guide to using FFmpeg to convert media files](https://opensource.com/article/17/6/ffmpeg-convert-media-file-formats)

**Comment by ahmadzahidglixen** [comment]
@NooruddinLakhani  For video compression?

**Comment by ahmadzahidglixen** [comment]
Using this package now:
https://www.npmjs.com/package/react-native-audio-video-tools
It is also using ffmpeg at the core but gives a simpler way to execute command.
