### ISSUE TITLE
Invalid data found when processing input - moov atom not found

### ISSUE THREAD

**Issue by nino-moreton** [tanersener/react-native-ffmpeg#199]
**Description**
Trying to [follow this SO](https://stackoverflow.com/questions/34786669/extract-all-video-frames-as-images-with-ffmpeg) in order for me to extract frames from an mp4 video taken with react-native-camera. 

```js
cameraRef.current.recordAsync().then(data => {
  console.log('done recording: ', data);
  RNFFmpeg.executeWithArguments(['-i', data.uri, '%03d.jpg']).then(
    result => {
      console.log('FFmpeg process exited with result: ', result);
     },
  );
});
```

It can find the file but can't process it.
![image](https://user-images.githubusercontent.com/48229482/95275702-d7d51e00-087b-11eb-829c-515fc6546672.png)

**Expected behavior**
Frames of the mp4 video taken by rncamera will have the frames extracted

**Current behavior**
Outputs `Invalid data found when processing input`.

**Logs**
[View logs here](https://ghostbin.co/paste/of23)

**Environment**
 - react-native: "0.63.2"
 - react-native-ffmpeg: "^0.4.4"

**Other**
I don't have any other FFmpeg packages installed. Just the base package. When I save the video to camera roll, the video isn't corrupted and I can view it so it doesn't have anything to do with corrupt mp4 file.

**Comment by elleryfamilia** [comment]
@nino-moreton  Where you ever able to figure this out? I'm running into the same. Only way around it is to wait for 1.5 seconds after camera finishes before having FFMPEG use the file.
