### ISSUE TITLE
ffmpeg filter option

### ISSUE THREAD

**Issue by webmasterdragon** [tanersener/react-native-ffmpeg#2]
Hi,
I am exciting on this package.
Now I feel need to know if it supports FFmpeg filter option like this.
`-filter_complex '[0:v][1:v] overlay'`
It's not a issue, just confirm to you possible/impossible.
Regards,

**Comment by tanersener** [comment]
Yes it supports using complex filter, there is an example in test-app [VideoUtil.js](https://github.com/tanersener/react-native-ffmpeg/blob/master/test-app/src/VideoUtil.js) file.

**Comment by webmasterdragon** [comment]
Thanks for your quick reply.
[IT](https://github.com/tanersener/react-native-ffmpeg/blob/master/test-app/src/VideoUtil.js) seems supprt filter option but on above code I have got this error.
`No such filter: '[0:v][1:v]'
Error initializing complex filters.
Invalid argument
`
Let me know if I have wrong ffmpeg format.
Thanks.

**Comment by tanersener** [comment]
> No such filter: '[0:v][1:v]' Error initializing complex filters. Invalid argument

Actually you don't need quotes, can you test it like `[0:v][1:v]`?

**Comment by webmasterdragon** [comment]
Yes,
In this case 
`No such filter: ''
 Error initializing complex filters.
Invalid argument`

**Comment by tanersener** [comment]
> No such filter: '' Error initializing complex filters. Invalid argument

Generally, a new line, an unnecessary space character or using two space characters cause this. Can you double check your filter chain?

Btw, I can find the error for you if you can share your complex filter.

**Comment by webmasterdragon** [comment]
OK.
Basically sample ffmpeg filter_complex command is working.
`-filter_complex "[1:v]colorkey=0x3BBD1E:0.3:0.2[ckout];[0:v][ckout]overlay[out]" -map "[out]"`
It seems my command error.
I will test again.

**Comment by tanersener** [comment]
> -filter_complex "[1:v]colorkey=0x3BBD1E:0.3:0.2[ckout];[0:v][ckout]overlay[out]" -map "[out]"

It works in the following format;

`RNFFmpeg.execute('... -filter_complex [1:v]colorkey=0x3BBD1E:0.3:0.2[ckout];[0:v][ckout]overlay[out] -map [out] ...')`

**Comment by webmasterdragon** [comment]
Yes, It's working on my project.
Thanks.
