### ISSUE TITLE
Keep getting the unable to open file in target ...

### ISSUE THREAD

**Issue by ingviso** [tanersener/react-native-ffmpeg#20]
**Description**
Keep getting the unable to open file in target ... despite having gone through all the recommended setups and running pod install again. Have run
```
rm -rf ios/Pods ios/build ios/Podfile.lock
cd ios
pod install
```

I did previously install mobile-ffmpeg and intended to use that but removed it and all its dependencies I think. 
If I remove react-native-ffmpeg from podfile and do pod install to remove it, the error still comes up when I try to build.

The error comes both when installing with https package and as I intend to use the full-gpl package.

My podfile
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'App' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for App
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  #pod 'Firebase/Database'


  pod 'react-native-ffmpeg', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec'

  target 'AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'App-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for App-tvOS

  target 'App-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

```

**Expected behavior**
Being able to build react-native app and us react-native-ffmpeg

**Current behavior**
I get the following error
`error: /Users/user/repositories/App/node_modules/react-native-ffmpeg/ios/Pods/Target Support Files/Pods-ReactNativeFFmpeg/Pods-ReactNativeFFmpeg.debug.xcconfig: unable to open file (in target "ReactNativeFFmpeg" in project "ReactNativeFFmpeg") (in target 'ReactNativeFFmpeg')`

**Environment**
 - React Native 0.55.2
 - React-native-ffmpeg: ^0.2.1

**Comment by tanersener** [comment]
What is the output `pod install`?

**Comment by ingviso** [comment]
I had in my Libraries folder under the project in Xcode the react-native-ffmpeg.xcodepoj, probably had before manual added it and forgot about it, removed it and then I'm able to build.
