### ISSUE TITLE
能出个react-native-ffmpeg教程吗？还有就是例子demo能多一点吗？

### ISSUE THREAD

**Issue by txatxp** [tanersener/react-native-ffmpeg#201]
**Description**
Description of what the issue is about.

**Expected behavior**
What you expected to happen.

**Current behavior**
What happened.

**Screenshots**

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
 - React Native Environment Info

**Other**

**Comment by tanersener** [comment]
There will be a more detailed example app soon, I'm esting the latest changes in the development branch. But I don't have time for something like a training.
