### ISSUE TITLE
Filter_Complex only return audio and blank video

### ISSUE THREAD

**Issue by Hugogsalas** [tanersener/react-native-ffmpeg#204]
**Description**
I tried to add a watermark to mp4 video, but the result output is in blank, in FFMPEG desktop version my command works, but i cant make this works in mobile

My comand is ;

```
RNFFmpeg.executeAsync(`-i ${VideoToMark} -i ${RNFS.DocumentDirectoryPath}/images/watermark.png -filter_complex "overlay=20:20" -c:a copy ${destiny}`, (cmpltExecution) => {
            if (cmpltExecution.returnCode == 0)
                res(destiny)

            rej()
        })
```

**Expected behavior**
Receive a output video with my watermark

**Current behavior**
Only received a blank video with audio

**Logs**
ffmpeg version v4.4-dev-416
[Tue Oct 27 2020 07:46:54.144]  LOG       Copyright (c) 2000-2020 the FFmpeg developers
[Tue Oct 27 2020 07:46:54.144]  LOG      

[Tue Oct 27 2020 07:46:54.144]  LOG        built with Apple clang version 11.0.3 (clang-1103.0.32.62)

[Tue Oct 27 2020 07:46:54.144]  LOG        configuration: --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.6.sdk --prefix=/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-arm64/ffmpeg --enable-version3 --arch=aarch64 --cpu=armv8 --target-os=darwin --ar=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar --cc=clang --cxx=clang++ --as='/Users/taner/Projects/mobile-ffmpeg/.tmp/gas-preprocessor.pl -arch aarch64 -- clang -arch arm64 -target aarch64-ios-darwin -march=armv8-a+crc+crypto -mcpu=generic -DMOBILE_FFMPEG_ARM64 -Wno-unused-function -Wno-deprecated-declarations -fstrict-aliasing -fembed-bitcode -DIOS -DMOBILE_FFMPEG_BUILD_DATE=20200725 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.6.sdk -Oz -miphoneos-version-min=12.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.6.sdk/usr/include' --ranlib=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib --strip=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip --enable-neon --enable-cross-compile --enable-pic --enable-asm --enable-inline-asm --enable-optimizations --enable-swscale --enable-static --disable-shared --enable-small --disable-v4l2-m2m --disable-outdev=v4l2 --disable-outdev=fbdev --disable-outdev=audiotoolbox --disable-indev=v4l2 --disable-indev=fbdev --disable-openssl --disable-xmm-clobber-test --disable-debug --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --disable-appkit --disable-alsa --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --enable-gmp --enable-gnutls --disable-sdl2 --enable-zlib --enable-audiotoolbox --enable-bzlib --enable-videotoolbox --enable-avfoundation --enable-iconv

[Tue Oct 27 2020 07:46:54.145]  LOG        libavutil      56. 55.100 / 56. 55.100

[Tue Oct 27 2020 07:46:54.145]  LOG        libavcodec     58. 96.100 / 58. 96.100

[Tue Oct 27 2020 07:46:54.145]  LOG        libavformat    58. 48.100 / 58. 48.100

[Tue Oct 27 2020 07:46:54.145]  LOG        libavdevice    58. 11.101 / 58. 11.101

[Tue Oct 27 2020 07:46:54.146]  LOG        libavfilter     7. 87.100 /  7. 87.100

[Tue Oct 27 2020 07:46:54.146]  LOG        libswscale      5.  8.100 /  5.  8.100

[Tue Oct 27 2020 07:46:54.146]  LOG        libswresample   3.  8.100 /  3.  8.100

[Tue Oct 27 2020 07:46:54.147]  LOG      Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:///var/mobile/Containers/Data/Application/E85CA25D-7F8B-4D76-88C8-6D1A484C9CB3/Library/Caches/Camera/1603806413919.mp4':

[Tue Oct 27 2020 07:46:54.147]  LOG        Metadata:

[Tue Oct 27 2020 07:46:54.147]  LOG          major_brand     : 
[Tue Oct 27 2020 07:46:54.148]  LOG      isom
[Tue Oct 27 2020 07:46:54.148]  LOG      

[Tue Oct 27 2020 07:46:54.148]  LOG          minor_version   : 
[Tue Oct 27 2020 07:46:54.148]  LOG      512
[Tue Oct 27 2020 07:46:54.149]  LOG      

[Tue Oct 27 2020 07:46:54.149]  LOG          compatible_brands: 
[Tue Oct 27 2020 07:46:54.149]  LOG      isomiso2mp41
[Tue Oct 27 2020 07:46:54.149]  LOG      

[Tue Oct 27 2020 07:46:54.150]  LOG          encoder         : 
[Tue Oct 27 2020 07:46:54.150]  LOG      Lavf58.48.100
[Tue Oct 27 2020 07:46:54.150]  LOG      

[Tue Oct 27 2020 07:46:54.150]  LOG        Duration: 
[Tue Oct 27 2020 07:46:54.151]  LOG      00:00:06.22
[Tue Oct 27 2020 07:46:54.151]  LOG      , start: 
[Tue Oct 27 2020 07:46:54.151]  LOG      0.000000
[Tue Oct 27 2020 07:46:54.151]  LOG      , bitrate: 
[Tue Oct 27 2020 07:46:54.153]  LOG      11911 kb/s
[Tue Oct 27 2020 07:46:54.154]  LOG      

[Tue Oct 27 2020 07:46:54.154]  LOG          Stream #0:0
[Tue Oct 27 2020 07:46:54.154]  LOG      (und)
[Tue Oct 27 2020 07:46:54.155]  LOG      : Video: hevc (hvc1 / 0x31637668), yuv420p(tv, bt709), 1920x1080, 11898 kb/s
[Tue Oct 27 2020 07:46:54.155]  LOG      , 
[Tue Oct 27 2020 07:46:54.155]  LOG      29.97 fps, 
[Tue Oct 27 2020 07:46:54.156]  LOG      29.97 tbr, 
[Tue Oct 27 2020 07:46:54.156]  LOG      19200 tbn, 
[Tue Oct 27 2020 07:46:54.156]  LOG      19200 tbc
[Tue Oct 27 2020 07:46:54.157]  LOG       (default)
[Tue Oct 27 2020 07:46:54.157]  LOG      

[Tue Oct 27 2020 07:46:54.157]  LOG          Metadata:

[Tue Oct 27 2020 07:46:54.157]  LOG            rotate          : 
[Tue Oct 27 2020 07:46:54.158]  LOG      90
[Tue Oct 27 2020 07:46:54.158]  LOG      

[Tue Oct 27 2020 07:46:54.158]  LOG            handler_name    : 
[Tue Oct 27 2020 07:46:54.158]  LOG      Core Media Video
[Tue Oct 27 2020 07:46:54.158]  LOG      

[Tue Oct 27 2020 07:46:54.159]  LOG          Side data:

[Tue Oct 27 2020 07:46:54.159]  LOG            
[Tue Oct 27 2020 07:46:54.161]  LOG      displaymatrix: rotation of -90.00 degrees
[Tue Oct 27 2020 07:46:54.161]  LOG      

[Tue Oct 27 2020 07:46:54.161]  LOG          Stream #0:1
[Tue Oct 27 2020 07:46:54.162]  LOG      (und)
[Tue Oct 27 2020 07:46:54.163]  LOG      : Audio: aac (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 90 kb/s
[Tue Oct 27 2020 07:46:54.163]  LOG       (default)
[Tue Oct 27 2020 07:46:54.163]  LOG      

[Tue Oct 27 2020 07:46:54.163]  LOG          Metadata:

[Tue Oct 27 2020 07:46:54.163]  LOG            handler_name    : 
[Tue Oct 27 2020 07:46:54.164]  LOG      Core Media Audio
[Tue Oct 27 2020 07:46:54.164]  LOG      

[Tue Oct 27 2020 07:46:54.164]  LOG      Input #1, png_pipe, from '/var/mobile/Containers/Data/Application/E85CA25D-7F8B-4D76-88C8-6D1A484C9CB3/Documents/images/watermark.png':

[Tue Oct 27 2020 07:46:54.164]  LOG        Duration: 
[Tue Oct 27 2020 07:46:54.165]  LOG      N/A
[Tue Oct 27 2020 07:46:54.165]  LOG      , bitrate: 
[Tue Oct 27 2020 07:46:54.165]  LOG      N/A
[Tue Oct 27 2020 07:46:54.165]  LOG      

[Tue Oct 27 2020 07:46:54.166]  LOG          Stream #1:0
[Tue Oct 27 2020 07:46:54.166]  LOG      : Video: png, rgba(pc), 100x31 [SAR 11811:11811 DAR 100:31]
[Tue Oct 27 2020 07:46:54.166]  LOG      , 
[Tue Oct 27 2020 07:46:54.166]  LOG      25 tbr, 
[Tue Oct 27 2020 07:46:54.167]  LOG      25 tbn, 
[Tue Oct 27 2020 07:46:54.167]  LOG      25 tbc
[Tue Oct 27 2020 07:46:54.167]  LOG      

[Tue Oct 27 2020 07:46:54.167]  LOG      Stream mapping:

[Tue Oct 27 2020 07:46:54.168]  LOG        Stream #0:0 (hevc) -> overlay:main
[Tue Oct 27 2020 07:46:54.168]  LOG      

[Tue Oct 27 2020 07:46:54.168]  LOG        Stream #1:0 (png) -> overlay:overlay
[Tue Oct 27 2020 07:46:54.168]  LOG      

[Tue Oct 27 2020 07:46:54.171]  LOG        overlay
[Tue Oct 27 2020 07:46:54.172]  LOG       -> Stream #0:0 (mpeg4)

[Tue Oct 27 2020 07:46:54.173]  LOG        Stream #0:1 -> #0:1
[Tue Oct 27 2020 07:46:54.173]  LOG       (copy)
[Tue Oct 27 2020 07:46:54.173]  LOG      

[Tue Oct 27 2020 07:46:54.174]  LOG      Press [q] to stop, [?] for help

[Tue Oct 27 2020 07:46:54.376]  LOG      sws_param option is deprecated and ignored

[Tue Oct 27 2020 07:46:54.379]  LOG      sws_param option is deprecated and ignored

[Tue Oct 27 2020 07:46:54.380]  LOG      Output #0, mp4, to 'file:///var/mobile/Containers/Data/Application/E85CA25D-7F8B-4D76-88C8-6D1A484C9CB3/Library/Caches/Camera/1603806414016.mp4':

[Tue Oct 27 2020 07:46:54.381]  LOG        Metadata:

[Tue Oct 27 2020 07:46:54.381]  LOG          major_brand     : 
[Tue Oct 27 2020 07:46:54.382]  LOG      isom
[Tue Oct 27 2020 07:46:54.383]  LOG      

[Tue Oct 27 2020 07:46:54.383]  LOG          minor_version   : 
[Tue Oct 27 2020 07:46:54.386]  LOG      512
[Tue Oct 27 2020 07:46:54.387]  LOG      

[Tue Oct 27 2020 07:46:54.387]  LOG          compatible_brands: 
[Tue Oct 27 2020 07:46:54.388]  LOG      isomiso2mp41
[Tue Oct 27 2020 07:46:54.388]  LOG      

[Tue Oct 27 2020 07:46:54.389]  LOG          encoder         : 
[Tue Oct 27 2020 07:46:54.389]  LOG      Lavf58.48.100
[Tue Oct 27 2020 07:46:54.389]  LOG      

[Tue Oct 27 2020 07:46:54.390]  LOG          Stream #0:0
[Tue Oct 27 2020 07:46:54.392]  LOG      : Video: mpeg4 (mp4v / 0x7634706D), yuv420p, 1080x1920, q=2-31, 200 kb/s
[Tue Oct 27 2020 07:46:54.393]  LOG      , 
[Tue Oct 27 2020 07:46:54.393]  LOG      29.97 fps, 
[Tue Oct 27 2020 07:46:54.394]  LOG      30k tbn, 
[Tue Oct 27 2020 07:46:54.394]  LOG      29.97 tbc
[Tue Oct 27 2020 07:46:54.395]  LOG       (default)
[Tue Oct 27 2020 07:46:54.395]  LOG      

[Tue Oct 27 2020 07:46:54.396]  LOG          Metadata:

[Tue Oct 27 2020 07:46:54.396]  LOG            encoder         : 
[Tue Oct 27 2020 07:46:54.396]  LOG      Lavc58.96.100 mpeg4
[Tue Oct 27 2020 07:46:54.397]  LOG      

[Tue Oct 27 2020 07:46:54.397]  LOG          Side data:

[Tue Oct 27 2020 07:46:54.399]  LOG            
[Tue Oct 27 2020 07:46:54.400]  LOG      cpb: 
[Tue Oct 27 2020 07:46:54.401]  LOG      bitrate max/min/avg: 0/0/200000 buffer size: 0 
[Tue Oct 27 2020 07:46:54.401]  LOG      vbv_delay: N/A
[Tue Oct 27 2020 07:46:54.402]  LOG      

[Tue Oct 27 2020 07:46:54.403]  LOG          Stream #0:1
[Tue Oct 27 2020 07:46:54.403]  LOG      (und)
[Tue Oct 27 2020 07:46:54.404]  LOG      : Audio: aac (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 90 kb/s
[Tue Oct 27 2020 07:46:54.404]  LOG       (default)
[Tue Oct 27 2020 07:46:54.405]  LOG      

[Tue Oct 27 2020 07:46:54.405]  LOG          Metadata:

[Tue Oct 27 2020 07:46:54.406]  LOG            handler_name    : 
[Tue Oct 27 2020 07:46:54.406]  LOG      Core Media Audio
[Tue Oct 27 2020 07:46:54.407]  LOG      

[Tue Oct 27 2020 07:46:54.613]  LOG      frame=    8 fps=0.0 q=13.2 size=     512kB time=00:00:00.43 bitrate=9539.2kbits/s speed=0.94x    
[Tue Oct 27 2020 07:46:55.195]  LOG      frame=   25 fps=0.0 q=24.8 size=     512kB time=00:00:01.02 bitrate=4111.5kbits/s speed=1.04x    
[Tue Oct 27 2020 07:46:55.622]  LOG      frame=   43 fps= 29 q=31.0 size=     768kB time=00:00:01.60 bitrate=3930.6kbits/s speed=1.07x    
[Tue Oct 27 2020 07:46:56.219]  LOG      frame=   60 fps= 30 q=31.0 size=     768kB time=00:00:02.18 bitrate=2884.5kbits/s speed=1.09x    
[Tue Oct 27 2020 07:46:56.631]  LOG      frame=   79 fps= 31 q=31.0 size=     768kB time=00:00:02.80 bitrate=2240.5kbits/s speed=1.12x    
[Tue Oct 27 2020 07:46:57.243]  LOG      frame=   98 fps= 32 q=31.0 size=    1024kB time=00:00:03.43 bitrate=2442.1kbits/s speed=1.14x    
[Tue Oct 27 2020 07:46:57.657]  LOG      frame=  116 fps= 33 q=31.0 size=    1024kB time=00:00:04.03 bitrate=2077.1kbits/s speed=1.14x    
[Tue Oct 27 2020 07:46:58.267]  LOG      frame=  134 fps= 33 q=31.0 size=    1024kB time=00:00:04.64 bitrate=1807.0kbits/s speed=1.15x    
[Tue Oct 27 2020 07:46:58.684]  LOG      frame=  153 fps= 34 q=31.0 size=    1280kB time=00:00:05.29 bitrate=1981.2kbits/s speed=1.16x    
[Tue Oct 27 2020 07:46:59.291]  LOG      frame=  170 fps= 33 q=31.0 size=    1280kB time=00:00:05.84 bitrate=1792.5kbits/s speed=1.15x    
[Tue Oct 27 2020 07:46:59.597]  LOG      frame=  185 fps= 34 q=31.0 Lsize=    1441kB time=00:00:06.15 bitrate=1918.6kbits/s speed=1.13x    

[Tue Oct 27 2020 07:46:59.602]  LOG      video:1365kB audio:69kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 
[Tue Oct 27 2020 07:46:59.602]  LOG      0.455578%

**Environment**
 - React Native 0.63.0

**Comment by Hugogsalas** [comment]
Someone know where is the problem??

**Comment by namitvatsal7** [comment]
Has anyone figured out how to get around the blank video issue on iOS?
