### ISSUE TITLE
Specs satisfying the `react-native-ffmpeg/https (= 0.5.0)` dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by donghuiqiu** [tanersener/react-native-ffmpeg#206]
![图片](https://user-images.githubusercontent.com/73329146/98429346-0ba49d00-20e1-11eb-8ed6-7b48afb945fa.png)

**Comment by Satya5614** [comment]
Having the same issue!

**Comment by Satya5614** [comment]
@donghuiqiu I solved the above issue by adding 

`pod 'react-native-ffmpeg/<package name>', :podspec => '../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec'` before `use_native_modules!` in Podfile

Also, change `platform :ios, '10.0'` to `platform :ios, '11.0'`

**Comment by donghuiqiu** [comment]
ok,thank you very much
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Satya Prakash Goyal"<notifications@github.com&gt;; 
发送时间: 2020年11月7日(星期六) 下午2:51
收件人: "tanersener/react-native-ffmpeg"<react-native-ffmpeg@noreply.github.com&gt;; 
抄送: "北斗"<1746572766@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [tanersener/react-native-ffmpeg] [!] CocoaPods could not find compatible versions for pod &quot;react-native-ffmpeg/https&quot;:   In Podfile:     react-native-ffmpeg (from `../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec`) was resolved to 0.5.0, which depends on       react-native-ffmpeg/https (= 0.5.0)  Specs satisfying the `react-native-ffmpeg/https (= 0.5.0)` dependency were found, but they required a higher minimum deployment target. (#206)





 
@donghuiqiu I solved the above issue by adding
 
pod 'react-native-ffmpeg/<package name&gt;', :podspec =&gt; '../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec' before use_native_modules! in Podfile
 
Also, change platform :ios, '10.0' to platform :ios, '11.0'

**Comment by donghuiqiu** [comment]
Hi! I follow the step to change platform :ios, '9.0' to platform :ios, '11.0', and then pod install success,but it show me clang: error: linker command failed with exit code 1 (use -v to see invocation) when I run the project again in Xcode,do you have this problem

**Comment by donghuiqiu** [comment]
![图片](https://user-images.githubusercontent.com/73329146/99631380-75745d80-2a76-11eb-8cba-9203d4614722.png)
have any idea to solve this problem,issue after change platform :ios, '9.0' to platform :ios, '11.0'

**Comment by mattgle** [comment]
I fixed this issue adding the following line codes:

```
config = use_native_modules!
platform :ios, '11.0'
```

and then running `pod install --repo-update`
