### ISSUE TITLE
In .../ios/Pods/mobile-ffmpeg-full-gpl/libavcodec.framework/libavcodec(aacencdsp.o), building for iOS Simulator, but linking in object file built for free standing

### ISSUE THREAD

**Issue by tungtrana3** [tanersener/react-native-ffmpeg#207]
**Description**
I'm trying to install full-gpl package to compress video, so I get this error when built my project on Xcode.
**Screenshots**
<img width="872" alt="Screen Shot 2020-11-09 at 11 25 13" src="https://user-images.githubusercontent.com/52845932/98500148-3f68f980-227e-11eb-8cf1-9f7dd3db5fbe.png">

**Comment by NoumanSakhawat** [comment]
Hi, @tungtrana3 
Did you find the solution?

**Comment by tungtrana3** [comment]
hi, i'm downgrade xcode to version 11

Vào Th 4, 25 thg 11, 2020 vào lúc 14:48 Nouman Sakhawat <
notifications@github.com> đã viết:

**Comment by ronaldocpontes** [comment]
XCode 12.3 has just been released. Is it possible that this version has a fix for this issue?

**Comment by tanersener** [comment]
Note that this issue is marked with `missing-issue-template`. It doesn't include enough information to make a comment.

**Comment by tungtrana3** [comment]
I updated my xcode to version 12.3 and the problem got resolved. Sorry for missing information for this issue
