### ISSUE TITLE
Live Streaming ffmpeg

### ISSUE THREAD

**Issue by JeyShah** [tanersener/react-native-ffmpeg#211]
Hi @tanersener,

How can i open camera and do live streaming through ffmpeg and on the meanwhile other users can view the live stream and also can we switch camera's while doing live streaming through ffmpeg. 

I know i can use react-native-video to show the live stream by giving RTMP link as source. Can you guide me about how can i open up the camera and do live stream and set output url as RTMP.

Please help. Thank you in advance

React Native: 0.62.2

**Comment by JeyShah** [comment]
@DaleWebb @tanersener Please help

**Comment by tanersener** [comment]
It's hard to suggest something. `react-native-ffmpeg` doesn't support viewing a stream or a file. You need to find a player that supports streaming.

**Comment by JeyShah** [comment]
I know react-native-video can play live stream. I am talking about publishing rtmp video stream through ffmpeg.

**Comment by tanersener** [comment]
Have you read this guide, https://trac.ffmpeg.org/wiki/StreamingGuide?

**Comment by TalhaArshad** [comment]
> I know react-native-video can play live stream. I am talking about publishing rtmp video stream through ffmpeg.

Have you found any solution?

**Comment by alekh1stzoom** [comment]
> I know react-native-video can play live stream. I am talking about publishing rtmp video stream through ffmpeg.

Any solution till now?
