### ISSUE TITLE
Android release build crash

### ISSUE THREAD

**Issue by damiandizeo** [tanersener/react-native-ffmpeg#213]
Hi @tanersener, since updated to v0.5.0, build crash on release mode on Android, debug mode is fine!!. The crash happens when app start, before splash . Do you know what could be happening? Thanks in advance

System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Memory: 622.36 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.1
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    react: 17.0.1 => 17.0.1 
    react-native: 0.63.3 => 0.63.3

**Comment by damiandizeo** [comment]
FYI, i'm using package min-gpl

**Comment by jspryl** [comment]
We encounter the same problem.

**Comment by tanersener** [comment]
This issue is marked as "missing-issue-template". See #62.

**Comment by fluoxe7ine** [comment]
Same issue

**Comment by cuongvoong** [comment]
Temp fix was posted in #216

**Comment by tanersener** [comment]
Please use the solution given under the [Tips](https://github.com/tanersener/react-native-ffmpeg#5-tips) section if you encounter Android release mode crashes.
