### ISSUE TITLE
Could not invoke RNFFmpegModule.enableLogEvents

### ISSUE THREAD

**Issue by krishnagujjjar** [tanersener/react-native-ffmpeg#216]
**Description**
I have duplicate one of my last project with same gradle config. It's work fine on first project but in new project debug build work fine but when i create release build, it's crash on start.
I have tried clear gradle cache & rebuild project again & again.
I try ffmpeg-test-app config but no luck.

**Current behavior**
it's crash on start with **Could not invoke RNFFmpegModule.enableLogEvents**

**Logs**
Sentry log: 
java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/com.klips-rTIQnrMMoKHGLsmtJV7jtQ==/base.apk!/lib/arm64-v8a/libmobileffmpeg.so": 0
    at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
    at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
    at java.lang.System.loadLibrary(System.java:1667)
    at com.arthenica.mobileffmpeg.Config.<clinit>
    at com.arthenica.mobileffmpeg.Config.c
    at com.arthenica.reactnative.RNFFmpegModule.enableLogEvents
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke
    at com.facebook.react.bridge.JavaModuleWrapper.invoke
    at com.facebook.react.bridge.queue.NativeRunnable.run
    at android.os.Handler.handleCallback(Handler.java:914)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage
    at android.os.Looper.loop(Looper.java:224)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run
    at java.lang.Thread.run(Thread.java:919)

java.lang.reflect.InvocationTargetException: null
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke
    at com.facebook.react.bridge.JavaModuleWrapper.invoke
    at com.facebook.react.bridge.queue.NativeRunnable.run
    at android.os.Handler.handleCallback(Handler.java:914)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage
    at android.os.Looper.loop(Looper.java:224)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run
    at java.lang.Thread.run(Thread.java:919)

java.lang.RuntimeException: Could not invoke RNFFmpegModule.enableLogEvents
    at com.facebook.react.bridge.JavaMethodWrapper.invoke
    at com.facebook.react.bridge.JavaModuleWrapper.invoke
    at com.facebook.react.bridge.queue.NativeRunnable.run
    at android.os.Handler.handleCallback(Handler.java:914)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage
    at android.os.Looper.loop(Looper.java:224)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run
    at java.lang.Thread.run(Thread.java:919)

**Environment**
 - react-native: "0.63.2"
 - react-native-ffmpeg: "^0.5.0"
 - gradle: "6.7"
 - ndkVersion: "21.3.6528147"
 - buildToolsVersion: "29.0.2"
 - minSdkVersion: "24"
 - compileSdkVersion: "29"
 - targetSdkVersion: "29"

**Comment by akug17** [comment]
same issue did you find any solution? Btw I tried the same with react-native-ffmpeg-test project getting the same error.

**Comment by tanersener** [comment]
There is an issue about the binaries published on `jcenter()`. The versions published on `jcenter()` are not up-to-date. 

You can use the following workaround while I'm working on the fix.

- Add the following entries into your `proguard-rules.pro` file.

```
-keep class com.arthenica.mobileffmpeg.Config {
    native <methods>;
    void log(long, int, byte[]);
    void statistics(long, int, float, float, long , int, double, double);
}

-keep class com.arthenica.mobileffmpeg.AbiDetect {
    native <methods>;
}
```

**Comment by krishnagujjjar** [comment]
> There is an issue about the binaries published on `jcenter()`. The versions published are not up-to-date.
> 
> You can use the following workaround while I'm working on the fix.
> 
> * Add the following entries into your `proguard-rules.pro` file.
> 
> ```
> -keep class com.arthenica.mobileffmpeg.Config {
>     native <methods>;
>     void log(long, int, byte[]);
>     void statistics(long, int, float, float, long , int, double, double);
> }
> 
> -keep class com.arthenica.mobileffmpeg.AbiDetect {
>     native <methods>;
> }
> ```

It's work well for me. thanks @tanersener

**Comment by mattgle** [comment]
> There is an issue about the binaries published on `jcenter()`. The versions published are not up-to-date.
> 
> You can use the following workaround while I'm working on the fix.
> 
> * Add the following entries into your `proguard-rules.pro` file.
> 
> ```
> -keep class com.arthenica.mobileffmpeg.Config {
>     native <methods>;
>     void log(long, int, byte[]);
>     void statistics(long, int, float, float, long , int, double, double);
> }
> 
> -keep class com.arthenica.mobileffmpeg.AbiDetect {
>     native <methods>;
> }
> ```

Worked for me too @tanersener u just saved my project 🥇

**Comment by tanersener** [comment]
I posted a solution under the [Tips](https://github.com/tanersener/react-native-ffmpeg#5-tips) section for Android release mode crashes. Please use it if you encounter this issue.

`If react-native-ffmpeg release builds on Android fail with the following exception, make sure that mavenCentral() is defined as a repository in your build.gradle and it is listed before jcenter().`

**Comment by hossein-zare** [comment]
Hello @tanersener
Your solution didn't work for me.

```
Could not invoke RNFFmpegModule.enableLogEvents

null

dlopen failed: cannot locate symbol "av_gcd_q" referenced by "/data/app/com.acshop/lib/arm/libavfilter.so"...
```
