### ISSUE TITLE
Xcode 12, building for iOS Simulator, but linking in object file built for iOS, for architecture x86_64

### ISSUE THREAD

**Issue by ronaldocpontes** [tanersener/react-native-ffmpeg#219]
**Description**
Cant build a project for simulator running on Macbook Pro - Intel
Processor: 2.2 GHz 6-Core Intel Core i7
Memory: 16 GB 2400 MHz DDR4
Graphics: Intel UHD Graphics 630 1536 MB

XCode Version 12.3 (12C33)
https://stackoverflow.com/questions/64003107/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios

**Expected behavior**
The app to be built and run on the iPhone 12 simulator.

**Current behavior**
ld: in '..../ios/Pods/mobile-ffmpeg-https/libavcodec.framework/libavcodec(aacencdsp.o), building for iOS Simulator, but linking in object file built for free standing, file '..../ios/Pods/mobile-ffmpeg-https/libavcodec.framework/libavcodec' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Environment**
 - React Native Environment Info
System:
    OS: macOS 11.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 200.50 MB / 16.00 GB
    Shell: 5.0.17 - /usr/local/bin/bash
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.7 - /Users/.jenv/shims/javac
    Python: 3.7.6 - /Users/miniconda3/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by tanersener** [comment]
Xcode 12 changed some settings about simulator architectures. Can you please have a look at the settings of the test application, https://github.com/tanersener/react-native-ffmpeg-test and update your settings accordingly?

**Comment by ronaldocpontes** [comment]
HI,

I can build the tester project but not run it.

![image](https://user-images.githubusercontent.com/3316428/102722874-0cde0200-42fc-11eb-90f8-d8a96ae256ec.png)

**Comment by ronaldocpontes** [comment]
Hi,

The settings application is running OK.
![image](https://user-images.githubusercontent.com/3316428/102775980-da78e700-4385-11eb-93a0-ad7ee73ba0ac.png)


How do I compare with the settings from my project so I can make the necessary changes?

**Comment by SMKH-PRO** [comment]
> Hi,
> 
> The settings application is running OK.
> ![image](https://user-images.githubusercontent.com/3316428/102775980-da78e700-4385-11eb-93a0-ad7ee73ba0ac.png)
> 
> How do I compare with the settings from my project so I can make the necessary changes?

Hello, did you find any solution? I am having the same problem.
