### ISSUE TITLE
converting mov to mp4

### ISSUE THREAD

**Issue by nicolasp123** [tanersener/react-native-ffmpeg#221]
**Description**
Hi, i just picked up react native and was wondering how i convert mov files (ios videos) to MP4 files in react native

thank you so much!

**Comment by ktayah** [comment]
FFmpeg is a large library outside of just this npm package. So to understand the commands needed to do any type of command you are better off looking for outside sources. You can check this out to get your answer on how to use Ffmpeg: https://opensource.com/article/17/6/ffmpeg-convert-media-file-formats
