### ISSUE TITLE
'mobileffmpeg/ExecuteDelegate.h' file not found 

### ISSUE THREAD

**Issue by RaviDhakad** [tanersener/react-native-ffmpeg#222]
Xcode 12.2, building failed with "react-native-ffmpeg" 'mobileffmpeg/ExecuteDelegate.h' file not found.
react: 16.13.1 => 16.13.1
react-native: 0.63.4 => 0.63.4
react-native-ffmpeg: 0.4.4 => 0.4.4 And 
react-native-ffmpeg: 0.5.0 => 0.5.0 
macOS Version : Big Sur 11.0.1

I have tried both version react-native-ffmpeg: 0.4.4 and react-native-ffmpeg: 0.5.0 but still getting 'mobileffmpeg/ExecuteDelegate.h' file not found in xcode 12.2 
From the last week RND with this issue but still not resolved this please help.

**Comment by tanersener** [comment]
There are similar issues reported. Please have a look at them.

**Comment by duckanhb** [comment]
I run my application with schema Release on IOS simulator and get this same issue
react: 16.13.1 => 16.13.1
react-native: 0.63.4 => 0.63.4
react-native-ffmpeg:  0.5.1
macOS Version: Catalina 10.15.4
xcode: 12
simulator: ios14.3
![image](https://user-images.githubusercontent.com/31836289/103254738-27c60b80-49b9-11eb-87c5-183a256afb22.png)

**Comment by alinchiosa** [comment]
i have the same issue

**Comment by nazabalm** [comment]
Getting the same issue while trying to build as release

**Comment by dayze** [comment]
Experimenting the same issue, and unfortunately solutions proposed in https://github.com/tanersener/react-native-ffmpeg/issues/203 didn't solve it 

react: 16.13.1
react-native: 0.63.3
react-native-ffmpeg: 0.5.1
macOS Version: Big Sur 11.1
xcode: 12.3

**Comment by doranteseduardo** [comment]
I get the same problem when trying to build a release, not in debug.

**Comment by damiandizeo** [comment]
Same issue here, can't build using iOS Simulator

**Comment by Moosieboy** [comment]
Not stale - the same issue happens for me. Not being able to test your app in a simulator is extremely annoying.
