### ISSUE TITLE
react-native init / pod install / build issues - xcode 10

### ISSUE THREAD

**Issue by MobileAppVault** [tanersener/react-native-ffmpeg#23]
**Description**
Hi,

I get the following error with a blank project when I try to build and run my react-native app.

`/Users/user/Desktop/ffmpegTest/ios/Pods/react-native-ffmpeg/ios/RNFFmpegModule.h:26:9: 'mobileffmpeg/MobileFFmpegConfig.h' file not found`

**Expected behavior**
Build should work

**Current behavior**
Error: 
`/Users/user/Desktop/ffmpegTest/ios/Pods/react-native-ffmpeg/ios/RNFFmpegModule.h:26:9: 'mobileffmpeg/MobileFFmpegConfig.h' file not found`

**Environment**
- React Native 0.57
- XCode: 10.1
- Command Lines Tools: 10.1

**Steps to reproduce the issue**

`$ react-native init ffmpegTest --template typescript`

`$ cd ffmpegTest && yarn add react-native-ffmpeg`

`$ cd ios && pod init`

*pod file content*

```
platform :ios, '9.0'

use_frameworks! # already tried it with and without "use_frameworks!"

target "ffmpegTest" do

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'jschelpers',
    'cxxreact',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTWebSocket', # needed for debugging
  ]

  # To use CocoaPods with React Native, you need to add this specific Yoga spec as well
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  # Third party deps
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'

  pod 'react-native-ffmpeg', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec'

end
```

`$ pod install`

*pod install output*

```
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `react-native-ffmpeg` from `../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga`
Downloading dependencies
Installing DoubleConversion (1.1.6)
Installing Folly (2016.10.31.00)
Installing React (0.57.8)
Installing boost-for-react-native (1.63.0)
Installing glog (0.3.5)
Installing mobile-ffmpeg-https (2.0)
Installing react-native-ffmpeg (0.2.1)
Installing yoga (0.57.8.React)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `ffmpegTest.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There are 16 dependencies from the Podfile and 8 total pods installed.
```

`$ open ffmpegTest.xcworkspace`

`xcode IDE -> product -> build`

Can you help me?

Many thanks & regards 
Marcus

**Comment by tanersener** [comment]
I can't reproduce this error. I repeated all the steps but didn't receive any errors, application was build successfully.

There is a similar issue #11 . Can you try these two solutions posted on that issue.

- `i resolved the issue by removing ios dir, next react-native eject and pod install again`
 
- `doing 'pod update [react-native-ffmpeg package]' after 'pod install' added all the missing files (turns out there's more missing than just MediaInformation.h).`

**Comment by MobileAppVault** [comment]
Many thanks!

’pod update react-native-ffmpeg’ fixed my issue. 

Don‘t know why I didn‘t found the issue report #11
