### ISSUE TITLE
Bundle size hugely increased after using FFMPEG

### ISSUE THREAD

**Issue by bekatd** [tanersener/react-native-ffmpeg#238]
**Description**
After adding ffmpeg library to my rn project (which I use only for video trimming) bundle size for android is increased drastically - by 100mb. It's not acceptable. Is there any way to reduce size somehow, consider that I am only using video trimming functionality

**Expected behavior**
Bundle size should not increase by 100 mb

**Current behavior**
Bundle size increased by 100 mb for only simple video trim functionality

**Screenshots**
![image](https://user-images.githubusercontent.com/6948919/115054682-917b0e80-9ef1-11eb-9382-6d6cc27e76cf.png)

**Logs**
N/A

**Environment**
 - "react-native": "0.63.4",
 - "react-native-ffmpeg": "^0.5.1",

**Other**
N/A

**Comment by mertbuldur** [comment]
I have this problem, did you solve it?

**Comment by bekatd** [comment]
Yes I used min package, but it did not help so eventually I am distributing bundles for each architecture, which reduced budle size from 130 mb to 20 mb

**Comment by mertbuldur** [comment]
hmm i use audio package , my bundle size 68 mb :/

**Comment by bekatd** [comment]
Link for [multiple apk building](https://developer.android.com/studio/build/configure-apk-splits)

**Comment by mertbuldur** [comment]
@bekatd  It makes sense, I would do it that way, wouldn't it be a problem?
