### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by stoner2497** [tanersener/react-native-ffmpeg#239]
**Description**
React-native-ffmpeg performance issues.

**Expected behavior**
I want to run the computation on native os instead of js thread .

**Current behavior**
run all computation on js thread.

**Screenshots**

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.co) and insert the link here.

**Environment**
 - React Native v0.63.4

**Other**
Please help me out how can i improve performance because if i take 20 sec video then too its taking 5 min to get things done.

**Comment by Richi2293** [comment]
Do you have these problems on Android right?
I have noticed that on Android it is really too slow and at moment I am only using it on iOS.
But at the moment on Android with the targetSdkVersion 29 this library does not work for me and goes into "Permission denied" error

**Comment by eliottguillaumin** [comment]
On android when exporting high bitrate files it's not uncommon for my app to outright crash while RNFFmpeg does its thing, it's a real pain and it's probably due to that.
