### ISSUE TITLE
Pod can't find files 

### ISSUE THREAD

**Issue by flyandi** [tanersener/react-native-ffmpeg#24]
I am getting the error

` error: /<path?/node_modules/react-native-ffmpeg/ios/Pods/Target Support Files/Pods-ReactNativeFFmpeg/Pods-ReactNativeFFmpeg.debug.xcconfig: unable to open file (in target "ReactNativeFFmpeg" in project "ReactNativeFFmpeg") (in target 'ReactNativeFFmpeg')
`

The file is actually not there and also using all the described tips, etc - are not helping.

Any other ideas?

Latest react version.

**Comment by flyandi** [comment]
i did multiple times.

**Comment by tanersener** [comment]
Did you try cleaning you pod cache? 

Additionally [issue #23](https://github.com/tanersener/react-native-ffmpeg/issues/23) has some solutions.

**Comment by flyandi** [comment]
Ok - so it seems it has something to do with `react-native link` - I tried a vanilla installation without running `link` and it  is fine but as soon I execute `react-native link` it keeps spitting out the above error. A `pod install` or `pod update` does not resolve the issue either.

**Comment by flyandi** [comment]
Ok - so running `react-native unlink react-native-ffmpeg` and re-running `pod install` seems to restore the proper references in the vanilla app. Let me try in my main app and see if I have success.

**Comment by flyandi** [comment]
and that did it for me.

So the key is don't use `react-native link` and if you did, ensure you remove the ffmpeg module again.

**Comment by flyandi** [comment]
Well it linked now properly but now I get the message `NativeModule can't be null` when importing ffmpeg....

**Comment by flyandi** [comment]
So it seems that ffmpeg has it's own `time.h` in the header and modules that importing `time.h` are being redirected to the ffmpeg implementation. hmmm....
