### ISSUE TITLE
Android Permission denied

### ISSUE THREAD

**Issue by Richi2293** [tanersener/react-native-ffmpeg#240]
**Description**
I am trying to start the function "getMediaInformation" but it keeps giving me this error: "Permission denied".

**Expected behavior**
It should give me the result of the informations given the path of the input video.

**Current behavior**
It goes in error telling me "Permission denied"

**Logs**
https://ghostbin.co/paste/77qo

**Environment**
 - React Native: 0.63.4
 - react-native-ffmpeg: 0.5.1
 
**Other**
- build.gradle -->  reactNativeFFmpegPackage = "full-gpl"
- targetSdkVersion --> 29
- Looking in the logs for "mobile-ffmpeg" shows the error
- the code: 
```
 RNFFprobe.getMediaInformation(videoPath).then(information => {
                    console.log('Result: ' + JSON.stringify(information));
                    Alert.alert(
                        'Result test',
                        JSON.stringify(information),
                        [
                            { text: 'OK', onPress: () => console.log('OK Pressed') },
                        ],
                        { cancelable: false },
                    );
                });
```
- I have already applied a permission request before doing this process. Using PermissionsAndroid, requesting permission "PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE"

**Comment by tanersener** [comment]
Try setting `requestLegacyExternalStorage` to `true` as explained in [Android storage use cases and best practices](https://developer.android.com/training/data-storage/use-cases).

**Comment by Richi2293** [comment]
Okok I'll try to put that setting, but from what I understand it is a temporary solution because then on devices running Android 11 the problem will recur, right?
Do you have a library update in mind or will I have to do something myself?
Just to get an idea, thank you so much for the super fast response :)

**Comment by tanersener** [comment]
Yes, there is an update in the parent native library about scoped storage. I plan to use that feature for API Level 30 (Android 11).

**Comment by Richi2293** [comment]
I confirm that it now works correctly! Thanks so much!
Okok sounds great to me, thank you very much for your effort :)

**Comment by subinsuresh** [comment]
> Yes, there is an update in the parent native library about scoped storage. I plan to use that feature for API Level 30 (Android 11).

Any updates on this?

**Comment by eliottguillaumin** [comment]
> 
> 
> Yes, there is an update in the parent native library about scoped storage. I plan to use that feature for API Level 30 (Android 11).

bump
Still no way to use the SAF with RNFFmpeg on Android 11 projects, would there be an easy way to implement a function like the one on [this page](https://github.com/tanersener/mobile-ffmpeg/wiki/Storage-Access-Framework) ?

**Comment by tanersener** [comment]
@eliottguillaumin I'm working on it but I couldn't find a stable widget for `react-native` to open files from Photos/Gallery yet. Tried `react-native-image-picker` but it has issues for videos.

**Comment by eliottguillaumin** [comment]
Thanks for getting back, I'll submit a small bounty for this issue because you are doing God's work man!
Our app is a video editing app that needs to be able to run FFMpeg and FFprobe commands on files stored on OTG storage without copying them to internal storage so currently Android 11 support is not really possible as it stands but thanks to your library we're able to do all sorts of things with video.

Téléchargez Outlook pour Android<https://aka.ms/ghei36>

________________________________
