### ISSUE TITLE
Please update react-native peer dependency 🙏

### ISSUE THREAD

**Issue by fabyeah** [tanersener/react-native-ffmpeg#241]
When trying to install, I get this error:

```
Found: react-native@0.64.1
npm ERR! node_modules/react-native
npm ERR!   react-native@"^0.64.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.56.0" from react-native-ffmpeg@0.5.1
npm ERR! node_modules/react-native-ffmpeg
npm ERR!   react-native-ffmpeg@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by eliottguillaumin** [comment]
Same problem, I can't work on my project anymore it's a real pain

**Comment by sumitsk1** [comment]
use-> npm install --legacy-peer-deps react-native-ffmpeg

**Comment by Aarvis** [comment]
I tried installing using both ---legacy-peer-deps and --force. Both of them did not work and returned an error quoted below.

`npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path A:\Frames\Frames-Android\node_modules\applicationinsights
npm ERR! dest A:\Frames\Frames-Android\node_modules\.applicationinsights-WWcQkKdY
npm ERR! errno -4048
mes-Android\node_modules\.applicationinsights-WWcQkKdY'
npm ERR!  [Error: EPERM: operation not permitted, rename 'A:\Frames\Frames-Android\node_modules\applicationinsights' -> 'A:\Frames\Frames-Android\node_modules\.applicationinsights-WWcQkKdY'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'A:\\Frames\\Frames-Android\\node_modules\\applicationinsights',
npm ERR!   dest: 'A:\\Frames\\Frames-Android\\node_modules\\.applicationinsights-WWcQkKdY'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aakas\AppData\Local\npm-cache\_logs\2021-08-02T19_50_44_712Z-debug.log`


I also tried giving full control to authenticated users for the project folder and also relaxed my antivirus, but I end up getting the same error.

Could anyone please help me to install react-native-ffmpeg until the peer dependencies are updated for latest versions?

**Comment by sumitsk1** [comment]
Have you tried with sudo command?

**Comment by Aarvis** [comment]
Okay, I got it installed. 
All I did was remove the node_modules folder and the package-lock.json file from my project, then I ran the command 

npm i react-native-ffmpeg --legacy-peer-deps

thereby installing react-native-ffmpeg and all other required node_modules for my project


> I tried installing using both ---legacy-peer-deps and --force. Both of them did not work and returned an error quoted below.
> 
> `npm ERR! code EPERM
> npm ERR! syscall rename
> npm ERR! path A:\Frames\Frames-Android\node_modules\applicationinsights
> npm ERR! dest A:\Frames\Frames-Android\node_modules.applicationinsights-WWcQkKdY
> npm ERR! errno -4048
> mes-Android\node_modules.applicationinsights-WWcQkKdY'
> npm ERR! [Error: EPERM: operation not permitted, rename 'A:\Frames\Frames-Android\node_modules\applicationinsights' -> 'A:\Frames\Frames-Android\node_modules.applicationinsights-WWcQkKdY'] {
> npm ERR! errno: -4048,
> npm ERR! code: 'EPERM',
> npm ERR! syscall: 'rename',
> npm ERR! path: 'A:\Frames\Frames-Android\node_modules\applicationinsights',
> npm ERR! dest: 'A:\Frames\Frames-Android\node_modules\.applicationinsights-WWcQkKdY'
> npm ERR! }
> npm ERR!
> npm ERR! The operation was rejected by your operating system.
> npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
> npm ERR! or that you lack permissions to access it.
> npm ERR!
> npm ERR! If you believe this might be a permissions issue, please double-check the
> npm ERR! permissions of the file and its containing directories, or try running
> npm ERR! the command again as root/Administrator.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\aakas\AppData\Local\npm-cache_logs\2021-08-02T19_50_44_712Z-debug.log`
> 
> I also tried giving full control to authenticated users for the project folder and also relaxed my antivirus, but I end up getting the same error.
> 
> Could anyone please help me to install react-native-ffmpeg until the peer dependencies are updated for latest versions?

**Comment by tanersener** [comment]
This project will be retired. Please consider switching to [FFmpegKit](https://github.com/tanersener/ffmpeg-kit).
