### ISSUE TITLE
[Android] No such file or directory

### ISSUE THREAD

**Issue by DavidCow** [tanersener/react-native-ffmpeg#25]
Hi I am trying trim a video with the code below in an Android emulator. 

I have installed the latest version of react-native-ffmpeg but it can't seem to find the file. I put it right under /bin/videofile.mp4 (relative to the root folder of the project). 

The only log output I get is 
` 12-29 01:09:17.804  9229 12551 I ReactNativeJS: ./bin/videofile.mp4: No such file or directory `

I also tried it without the "bin" folder. I tried using the "file:///" prefix but nothing so far has worked its wonders. 

I can't find anything else online either. Does anyone know where to put the file? Or how the path needs to look like in order to be found by the ffmpeg module?

Thanks!

-root
--bin
---videofile.mp4

```
componentWillMount(){
    console.log("START");

    RNFFmpeg.enableLogCallback(this.logCallback);
    RNFFmpeg.enableStatisticsCallback(this.statisticsCallback);

    RNFFmpeg.execute('-i ./bin/videofile.mp4 -ss 00:00:00.000 -to 00:00:02.500 ./bin/output.mp4');
    console.log("AFTER EXECUTE");

    RNFFmpeg.getLastReturnCode().then(result => {
      console.log("Last return code: " + result.lastRc);
    });

    RNFFmpeg.getLastCommandOutput().then(result => {
      console.log("Last command output: " + result.lastCommandOutput);
    });
    console.log("END");
  }
```

Versions
```
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-ffmpeg": "^0.2.1",
    "react-native-video": "^4.2.0"
```

**Comment by tanersener** [comment]
Can you access that file without using `react-native-ffmpeg`? As far as I know you need to put media files under `res` folder in order to access them in `Android`.

**Comment by DavidCow** [comment]
Hi tanersener, 
thanks for your quick reply. 
Yes, I can access that file without react-native-ffmpeg. For example with react-native-video by using require("./bin/videofile.mp4"). 
I have tried to put it under res as well, but no success so far. It still shows the "No such file or directory" log message.

Appreciate any help and ideas!

**Comment by tanersener** [comment]
The problem here is `require("./bin/videofile.mp4")` works for `react-native` but does not represent an accessible uri for `react-native-ffmpeg`. "./bin/videofile.mp4" is a relative path. `require` directive knows the project root path and can transform relative path to absolute path, then access it. But `react-native-ffmpeg` can't do that. You need to convert this relative path to absolute path. As far as I know it is not easy to do. I recommend using `react-native-fs` package. I'm using it in my [test-applications](https://github.com/tanersener/react-native-ffmpeg-test).

**Comment by DavidCow** [comment]
Hi again.
I've been trying to make it work with react-native-fs for the entire day but still no luck. I tried to put the video file in the "res" folder, "assets" folder in Android. It just can't seem to find its way to the file.

I tried it similarly to this piece of code (and a lot of alternatives with different folder paths etc.)
`RNFFmpeg.execute('-i file://'+ RNFS.DocumentDirectoryPath  +'/videofile.mp4 -ss 00:00:00.000 -to 00:00:02.500 file://'+ RNFS.DocumentDirectoryPath  +'/outnow.mp4');`

I tried looking into your test application but I can't seem to find an example where you access an existing videofile by path. 

Do you have any suggestions?

Thanks! :)

**Comment by AKclown** [comment]
> Tahnks I copied the video from the assets to RNFS.DocumentDirectoryPath + "/file.mp4" und now ffmpeg has been able to locate the video.
> 
> Thanks for your help!!!

Hi, how about moving the local video file to the RNFS.DocumentDirectoryPath location you mentioned? Can you give me some hints

**Comment by AKclown** [comment]
Let me answer my question, hoping to help people who have the same problem。
We need to put our local files into the corresponding directory, as shown in the figure below, you can refer to the test demo
![image](https://user-images.githubusercontent.com/33648653/125200926-960c5480-e29f-11eb-940f-2af0ddcf6a04.png)

Note that you need to restart the project, and then write the following code in the project to use it

`
RNFS.copyFileAssets('ak.mp4', `${RNFS.DocumentDirectoryPath}/ak.mp4`)
        RNFFmpeg.execute(`-i ${RNFS.DocumentDirectoryPath}/ak.mp4 -vf fps=0.3 ${RNFS.DocumentDirectoryPath}/out%d.png`)
        .then(result => console.log(result,'result---'));
`
