### ISSUE TITLE
Working only on debug mode in Android

### ISSUE THREAD

**Issue by Shahanshah87** [tanersener/react-native-ffmpeg#257]
**Description**
I am using `full-gpl` and command is `-y -i ${inputVideo} -c:v libx264 -crf 28 -preset ultrafast  ${finalVideo}`

**Expected behavior**
It should also work in development mode(while debug is not on) and release mode in Android.

**Current behavior**
Working only on development(while debug is on)

**Environment**
 - React Native 0.64

**Comment by zchwyng** [comment]
+1

**Comment by Shahanshah87** [comment]
@tanersener @DaleWebb please help as I need this to be fixed asap. Please help if you get time.

**Comment by DaleWebb** [comment]
> @tanersener @DaleWebb please help as I need this to be fixed asap. Please help if you get time.

Hello,

I don't work on this project.

Given the number of open issues without response from the maintainer and lack of recent commits, this project looks abandoned and it seems unlikely that this issue will be resolved.

I'd advise either:
- Look for another module to replace this
- or, fix the problem yourself

**Comment by tanersener** [comment]
This project is maintained. I read all the messages. Unfortunately, I don't have time to respond to all of them. I'm mostly responding to critical issues about the library.

We also have some rules in place, see #62. It is pinned at the top. Issues that don't follow that guideline are ignored as it is said in it.

If you have an urgent issue see the sponsorship options. I helped a lot of people who reached out to me through them.

Regarding this issue, it was reported many times before and it was fixed. So, if you use the search option you can find the solution in them. By the way, the solution was added in the [Tips](https://github.com/tanersener/react-native-ffmpeg#5-tips) as well.

**Comment by k1195453766** [comment]
I also encountered this problem. Has it been solved？

**Comment by zchwyng** [comment]
I initially had the same problem. Not entirely sure what solved it, but I added write permissions to the Android manifest, and copied the temp file to the OS temp dir. Hope it helps!

**Comment by k1195453766** [comment]
my project is solved;
modify file:android/app/build.gradle => def enableProguardInReleaseBuilds = false

**Comment by tanersener** [comment]
I suggest reading all messages in this thread. The solution was already given here. Disabling `proguard` is just a workaround.
