### ISSUE TITLE
moov atom not found

### ISSUE THREAD

**Issue by BalramY** [tanersener/react-native-ffmpeg#262]
When executing ffmpeg conversion get "moov atom not found" issue on Android version 6, 7, though it work fine on greater versions
            
Console: -
  libavutil      56. 55.100 / 56. 55.100
 LOG    libavcodec     58. 96.100 / 58. 96.100
 LOG    libavformat    58. 48.100 / 58. 48.100
 LOG    libavdevice    58. 11.101 / 58. 11.101
 LOG    libavfilter     7. 87.100 /  7. 87.100
 LOG    libswscale      5.  8.100 /  5.  8.100
 LOG    libswresample   3.  8.100 /  3.  8.100
 LOG  [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f4d1a8200] moov atom not found    <----
 LOG  file:///data/user/0/com.dellainfotech/cache/Camera/df60cb3f-b1cc-47bb-b122-6369f31ded4c.mp4: Invalid data found when processing input

any solution for this..

**Comment by kevinstubbs** [comment]
Hi, have you seen this thread on Reddit? Seems like there might be a solution to your problem there.
https://www.reddit.com/r/ffmpeg/comments/ih0hf7/ffmpeg_moov_atom_not_found/

**Comment by tanersener** [comment]
This project will be retired. Please consider switching to [FFmpegKit](https://github.com/tanersener/ffmpeg-kit).
