### ISSUE TITLE
Large APK size after installing package

### ISSUE THREAD

**Issue by Tymofiev** [tanersener/react-native-ffmpeg#266]
**Description**
After adding package to project Android APK size increases from ~90 MB to ~146 MB. Does not depend on external libraries as I am using "min" pack.

**Expected behavior**
Bundle size should only grow by couple MB instead of ~50 providing zero external libraries are used.

**Screenshots**
Without package
![image](https://user-images.githubusercontent.com/44410158/133271300-5613104c-b340-4115-af9a-63f8d4f69f08.png)
After installing it
![image](https://user-images.githubusercontent.com/44410158/133271216-a1240ad1-ffb3-4a2b-bdc0-211be6a8f101.png)
Comparing these two APKs
![image](https://user-images.githubusercontent.com/44410158/133272317-3b53b9ae-1690-49c0-ab5e-3d28597e03b9.png)

**Other**
As I understand it's because of this shared objects, but can I decrease the size somehow?
![image](https://user-images.githubusercontent.com/44410158/133272486-64698426-d554-4281-908f-315fc071d307.png)

**Comment by tanersener** [comment]
`min` package is around `25 MB`. It cannot increase the size that much. I suggest you check logcat output and find the `mobile-ffmpeg` package loaded. It will tell you which package is loaded.

**Comment by ursNj** [comment]
Same for me as well, it increased almost 25 Mb than previous version:

Before My APK size: 20Mb

After update to 0.5.2 : 45Mb

**Comment by Tymofiev** [comment]
> `min` package is around `25 MB` and each architecture takes ~ 6 MB. It cannot increase the size that much. I suggest you check logcat output and find the `mobile-ffmpeg` package loaded. It will tell you where your app uses `min` package or not.

Thanks for answering, so there is no way to decrease the size, exclude some files etc.? As you see on the screenshot, libs take a bit space for every architecture 

P.S. Building Android App Bundle seems to resolve this issue for now, results with around 60-70MB in my case

**Comment by tanersener** [comment]
If `min` package is not small enough for you then you can try building your own `.so` libraries. They come from `mobile-ffmpeg` project. There is a wiki page called [How to decrease binary size](https://github.com/tanersener/mobile-ffmpeg/wiki/How-to-decrease-binary-size) under the project which explains how the binary size can be decreased further.

**Comment by Tymofiev** [comment]
I thought there is a list of those I can't exclude this way, but if I am able to do that - will try it as soon as `.aab` file gets too large. Thank you!
