### ISSUE TITLE
[IOS] Adding PNG image overlay on a video, JPEG is working, but PNG is not working.

### ISSUE THREAD

**Issue by hamzashahbaz** [tanersener/react-native-ffmpeg#30]
Hey
I am trying to overlay png image on a video. JPEG is working and PNG is not working. I tried everything to fix it but can you please help me fix this bug. The errors I am getting is as follow: 
inflate returned error -3
Error while decoding stream #1:0: Generic error in an external library
`Running FFmpeg command: -i /Users/hamza/Library/Developer/CoreSimulator/Devices/5A28216E-119E-4B74-A28F-15F47E4EC9C7/data/Containers/Data/Application/461F6E56-0E16-45D8-A44E-3D3732E8FE77/Library/Caches/input.mp4 -i /Users/hamza/Library/Developer/CoreSimulator/Devices/5A28216E-119E-4B74-A28F-15F47E4EC9C7/data/Containers/Data/Application/461F6E56-0E16-45D8-A44E-3D3732E8FE77/Library/Caches/watermark.png -filter_complex overlay=10:10 /Users/hamza/Library/Developer/CoreSimulator/Devices/5A28216E-119E-4B74-A28F-15F47E4EC9C7/data/Containers/Data/Application/461F6E56-0E16-45D8-A44E-3D3732E8FE77/Library/Caches/input2.mp4 with delimiter  .

index.js:70 ffmpeg version v4.1-dev-1517
index.js:70  Copyright (c) 2000-2018 the FFmpeg developers
index.js:70 

index.js:70   built with Apple LLVM version 7.3.0 (clang-703.0.31)

index.js:70   configuration: --sysroot=/Applications/Xcode-v7.3.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk --prefix=/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/ffmpeg --extra-cflags='-arch x86_64 -target x86_64-ios-darwin -march=x86-64 -msse4.2 -mpopcnt -m64 -mtune=intel -Wno-unused-function -DPIC -fstrict-aliasing -DIOS -isysroot /Applications/Xcode-v7.3.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -O2 -Wno-ignored-optimization-argument -mios-simulator-version-min=8.0 -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/fontconfig/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/freetype/include/freetype2 -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libpng/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libuuid/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/expat/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libiconv/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/freetype/include/freetype2 -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libpng/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/fribidi/include/fribidi -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/gmp/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/gnutls/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/nettle/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/lame/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libass/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/fontconfig/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libuuid/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/expat/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libiconv/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/fribidi/include/fribidi -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/freetype/include/freetype2 -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libpng/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libiconv/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libtheora/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libogg/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libvorbis/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libogg/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libvpx/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libwebp/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libxml2/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libxml2/include/libxml2 -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libiconv/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/opencore-amr/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/opencore-amr/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/shine/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/speex/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/wavpack/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/kvazaar/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libilbc/include/ -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/opus/include/opus -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/snappy/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/soxr/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libaom/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/chromaprint/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/twolame/include -D_THREAD_SAFE -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/sdl/include/SDL2 -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/tesseract/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/leptonica/include/leptonica -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/giflib/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libogg/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libpng/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/li
index.js:70   libavutil      56. 19.101 / 56. 19.101

index.js:70   libavcodec     58. 33.102 / 58. 33.102

index.js:70   libavformat    58. 19.102 / 58. 19.102

index.js:70   libavdevice    58.  4.106 / 58.  4.106

index.js:70   libavfilter     7. 37.100 /  7. 37.100

index.js:70   libswscale      5.  2.100 /  5.  2.100

index.js:70   libswresample   3.  2.100 /  3.  2.100

index.js:70 Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/hamza/Library/Developer/CoreSimulator/Devices/5A28216E-119E-4B74-A28F-15F47E4EC9C7/data/Containers/Data/Application/461F6E56-0E16-45D8-A44E-3D3732E8FE77/Library/Caches/input.mp4':

index.js:70   Metadata:

index.js:70     major_brand     : 
index.js:70 isom
index.js:70 

index.js:70     minor_version   : 
index.js:70 512
index.js:70 

index.js:70     compatible_brands: 
index.js:70 isomiso2mp41
index.js:70 

index.js:70     encoder         : 
index.js:70 Lavf58.19.102
index.js:70 

index.js:70   Duration: 
index.js:70 00:00:35.01
index.js:70 , start: 
index.js:70 0.000000
index.js:70 , bitrate: 
index.js:70 382 kb/s
index.js:70 

index.js:70     Stream #0:0
index.js:70 (eng)
index.js:70 : Video: mpeg4 (mp4v / 0x7634706D), yuv420p, 360x360 [SAR 1:1 DAR 1:1], 246 kb/s
index.js:70 , 
index.js:70 30 fps, 
index.js:70 30 tbr, 
index.js:70 15360 tbn, 
index.js:70 30 tbc
index.js:70  (default)
index.js:70 

index.js:70     Metadata:

index.js:70       handler_name    : 
index.js:70 Mainconcept Video Media Handler
index.js:70 

index.js:70     Stream #0:1
index.js:70 (eng)
index.js:70 : Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 129 kb/s
index.js:70  (default)
index.js:70 

index.js:70     Metadata:

index.js:70       handler_name    : 
index.js:70 #Mainconcept MP4 Sound Media Handler
index.js:70 

index.js:70 inflate returned error -3

index.js:70 Input #1, png_pipe, from '/Users/hamza/Library/Developer/CoreSimulator/Devices/5A28216E-119E-4B74-A28F-15F47E4EC9C7/data/Containers/Data/Application/461F6E56-0E16-45D8-A44E-3D3732E8FE77/Library/Caches/watermark.png':

index.js:70   Duration: 
index.js:70 N/A
index.js:70 , bitrate: 
index.js:70 N/A
index.js:70 

index.js:70     Stream #1:0
index.js:70 : Video: png, rgba(pc), 2559x731 [SAR 72:72 DAR 2559:731]
index.js:70 , 
index.js:70 25 tbr, 
index.js:70 25 tbn, 
index.js:70 25 tbc
index.js:70 

index.js:70 Stream mapping:

index.js:70   Stream #0:0 (mpeg4) -> overlay:main
index.js:70  (graph 0)
index.js:70 

index.js:70   Stream #1:0 (png) -> overlay:overlay
index.js:70  (graph 0)
index.js:70 

index.js:70   overlay
index.js:70  (graph 0)
index.js:70  -> Stream #0:0 (mpeg4)

index.js:70   Stream #0:1 -> #0:1
index.js:70  (aac (native) -> aac (native))
index.js:70 

index.js:70 Press [q] to stop, [?] for help

index.js:70 frame=    0 fps=0.0 q=0.0 size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A    
index.js:70 inflate returned error -3

index.js:70 Error while decoding stream #1:0: Generic error in an external library

index.js:70 Output #0, mp4, to '/Users/hamza/Library/Developer/CoreSimulator/Devices/5A28216E-119E-4B74-A28F-15F47E4EC9C7/data/Containers/Data/Application/461F6E56-0E16-45D8-A44E-3D3732E8FE77/Library/Caches/input2.mp4':

index.js:70   Metadata:

index.js:70     major_brand     : 
index.js:70 isom
index.js:70 

index.js:70     minor_version   : 
index.js:70 512
index.js:70 

index.js:70     compatible_brands: 
index.js:70 isomiso2mp41
index.js:70 

index.js:70     encoder         : 
index.js:70 Lavf58.19.102
index.js:70 

index.js:70     Stream #0:0
index.js:70 : Video: mpeg4 (mp4v / 0x7634706D), yuv420p, 360x360 [SAR 1:1 DAR 1:1], q=2-31, 200 kb/s
index.js:70 , 
index.js:70 30 fps, 
index.js:70 15360 tbn, 
index.js:70 30 tbc
index.js:70  (default)
index.js:70 

index.js:70     Metadata:

index.js:70       encoder         : 
index.js:70 Lavc58.33.102 mpeg4
index.js:70 

index.js:70     Side data:

index.js:70       
index.js:70 cpb: 
index.js:70 bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
index.js:70 

index.js:70     Stream #0:1
index.js:70 (eng)
index.js:70 : Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s
index.js:70  (default)
index.js:70 

index.js:70     Metadata:

index.js:70       handler_name    : 
index.js:70 #Mainconcept MP4 Sound Media Handler
index.js:70 

index.js:70       encoder         : 
index.js:70 Lavc58.33.102 aac
index.js:70 

index.js:70 frame=  196 fps=0.0 q=6.9 size=     256kB time=00:00:06.61 bitrate= 317.2kbits/s speed=13.2x    
index.js:70 frame=  496 fps=494 q=13.0 size=     768kB time=00:00:16.59 bitrate= 379.1kbits/s speed=16.5x    
index.js:70 frame=  792 fps=527 q=10.6 size=    1024kB time=00:00:26.49 bitrate= 316.6kbits/s speed=17.6x    
index.js:70 frame= 1044 fps=521 q=9.4 size=    1536kB time=00:00:34.90 bitrate= 360.5kbits/s speed=17.4x    
index.js:70 
index.js:70 frame= 1049 fps=518 q=8.5 Lsize=    1640kB time=00:00:34.98 bitrate= 384.1kbits/s speed=17.3x    

index.js:70 video:1059kB audio:550kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 
index.js:70 1.938645%
index.js:70 

index.js:70 Qavg: 2084.625

index.js:70 
RCTLog.js:47 FFmpeg exited with rc: 0`

**Comment by tanersener** [comment]
Can you check your `Build Settings` in `Xcode` and see if at least one of the following two settings is set to YES? Settings both of them to NO should fix your issue.

<img width="850" alt="png_settings" src="https://user-images.githubusercontent.com/10158439/45798948-794c9f80-bcb4-11e8-8881-8c61789b283c.png">

**Comment by hamzashahbaz** [comment]
Thank you for a quick response! I am trying it and will let you know if it worked or not!

**Comment by hamzashahbaz** [comment]
Thanks! it worked like a charm!

**Comment by rafaismyname** [comment]
> Can you check your `Build Settings` in `Xcode` and see if at least one of the following two settings is set to YES? Settings both of them to NO should fix your issue.
> 
> <img alt="png_settings" width="850" src="https://user-images.githubusercontent.com/10158439/45798948-794c9f80-bcb4-11e8-8881-8c61789b283c.png">

This should be pinned into README.md!!!!

**Comment by tanersener** [comment]
> This should be pinned into README.md!!!!

Done
