### ISSUE TITLE
No usable fontconfig configuration file found, using fallback.

### ISSUE THREAD

**Issue by hamzashahbaz** [tanersener/react-native-ffmpeg#31]
I am trying to burn subtitles on a video. I am getting this error below:
`Running FFmpeg command: -i /Users/hamza/Library/Developer/CoreSimulator/Devices/5A28216E-119E-4B74-A28F-15F47E4EC9C7/data/Containers/Data/Application/8BF1314A-F6D1-4C43-994E-F94EE40921DA/Library/Caches/input-caption.mp4 -filter_complex subtitles=/Users/hamza/Library/Developer/CoreSimulator/Devices/5A28216E-119E-4B74-A28F-15F47E4EC9C7/data/Containers/Bundle/Application/83068106-391B-46A3-8598-6BE7A8A11077/AwesomeProject.app/test.srt:force_style='PrimaryColour=#000000,OutlineColour=None,Outline=0,Shadow=0,BorderStyle=0' -y /Users/hamza/Library/Developer/CoreSimulator/Devices/5A28216E-119E-4B74-A28F-15F47E4EC9C7/data/Containers/Data/Application/8BF1314A-F6D1-4C43-994E-F94EE40921DA/Library/Caches/input-caption.mp4 with delimiter  .

index.js:70 ffmpeg version v4.1-dev-1517
index.js:70  Copyright (c) 2000-2018 the FFmpeg developers
index.js:70 

index.js:70   built with Apple LLVM version 7.3.0 (clang-703.0.31)

index.js:70   configuration: --sysroot=/Applications/Xcode-v7.3.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk --prefix=/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/ffmpeg --extra-cflags='-arch x86_64 -target x86_64-ios-darwin -march=x86-64 -msse4.2 -mpopcnt -m64 -mtune=intel -Wno-unused-function -DPIC -fstrict-aliasing -DIOS -isysroot /Applications/Xcode-v7.3.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -O2 -Wno-ignored-optimization-argument -mios-simulator-version-min=8.0 -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/fontconfig/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/freetype/include/freetype2 -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libpng/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libuuid/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/expat/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libiconv/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/freetype/include/freetype2 -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libpng/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/fribidi/include/fribidi -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/gmp/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/gnutls/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/nettle/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/lame/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libass/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/fontconfig/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libuuid/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/expat/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libiconv/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/fribidi/include/fribidi -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/freetype/include/freetype2 -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libpng/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libiconv/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libtheora/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libogg/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libvorbis/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libogg/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libvpx/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libwebp/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libxml2/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libxml2/include/libxml2 -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libiconv/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/opencore-amr/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/opencore-amr/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/shine/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/speex/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/wavpack/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/kvazaar/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libilbc/include/ -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/opus/include/opus -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/snappy/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/soxr/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libaom/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/chromaprint/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/twolame/include -D_THREAD_SAFE -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/sdl/include/SDL2 -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/tesseract/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/leptonica/include/leptonica -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/giflib/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libogg/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/libpng/include -I/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/li
index.js:70   libavutil      56. 19.101 / 56. 19.101

index.js:70   libavcodec     58. 33.102 / 58. 33.102

index.js:70   libavformat    58. 19.102 / 58. 19.102

index.js:70   libavdevice    58.  4.106 / 58.  4.106

index.js:70   libavfilter     7. 37.100 /  7. 37.100

index.js:70   libswscale      5.  2.100 /  5.  2.100

index.js:70   libswresample   3.  2.100 /  3.  2.100

index.js:70 Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/hamza/Library/Developer/CoreSimulator/Devices/5A28216E-119E-4B74-A28F-15F47E4EC9C7/data/Containers/Data/Application/8BF1314A-F6D1-4C43-994E-F94EE40921DA/Library/Caches/input-caption.mp4':

index.js:70   Metadata:

index.js:70     major_brand     : 
index.js:70 isom
index.js:70 

index.js:70     minor_version   : 
index.js:70 512
index.js:70 

index.js:70     compatible_brands: 
index.js:70 isomiso2mp41
index.js:70 

index.js:70     encoder         : 
index.js:70 Lavf58.19.102
index.js:70 

index.js:70   Duration: 
index.js:70 00:00:34.97
index.js:70 , start: 
index.js:70 0.000000
index.js:70 , bitrate: 
index.js:70 259 kb/s
index.js:70 

index.js:70     Stream #0:0
index.js:70 (und)
index.js:70 : Video: mpeg4 (mp4v / 0x7634706D), yuv420p, 360x360 [SAR 1:1 DAR 1:1], 258 kb/s
index.js:70 , 
index.js:70 30 fps, 
index.js:70 30 tbr, 
index.js:70 15360 tbn, 
index.js:70 30 tbc
index.js:70  (default)
index.js:70 

index.js:70     Metadata:

index.js:70       handler_name    : 
index.js:70 VideoHandler
index.js:70 

index.js:70 Shaper: FriBidi 1.0.5 (SIMPLE)
index.js:70 

index.js:70 No usable fontconfig configuration file found, using fallback.
index.js:70 

index.js:70 Using font provider fontconfig
index.js:70 

index.js:70 Output /Users/hamza/Library/Developer/CoreSimulator/Devices/5A28216E-119E-4B74-A28F-15F47E4EC9C7/data/Containers/Data/Application/8BF1314A-F6D1-4C43-994E-F94EE40921DA/Library/Caches/input-caption.mp4 same as Input #0 - exiting

index.js:70 FFmpeg cannot edit existing files in-place.

index.js:70 Conversion failed!`

**Comment by tanersener** [comment]
You need to provide a `fontconfig` configuration to burn subtitles. You can either register your own configuration with `RNFFmpeg.setFontconfigConfigurationPath()` function or register the directory including your font with `RNFFmpeg.setFontDirectory()`, which will build a configuration based on font directory.

**Comment by hamzashahbaz** [comment]
Do you have an example?

**Comment by hamzashahbaz** [comment]
It worked!!! Thank you!!! 👍
