### ISSUE TITLE
[ios] ffmpeg conflicting with opencv

### ISSUE THREAD

**Issue by ingviso** [tanersener/react-native-ffmpeg#35]
**Description**
I'm trying to use react-native-ffmpeg on ios, works well on android. I use opencv for some image processing, code written in C++, soon as I include react-native-ffmpeg in the project it renders the imread function of opencv useless. Just get empty images width and height are zero.

I have tried to use all three different setups stated in react-native-ffmpeg-test but setup nr.2 does give me some error so that did not work.
This is the error:
`[!] The 'Pods-App' target has transitive dependencies that include static binaries: (/Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/mobileffmpeg.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libavcodec.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libavdevice.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libavfilter.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libavformat.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libavutil.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libswresample.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libswscale.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/expat.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/fontconfig.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/freetype.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/fribidi.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/giflib.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/gmp.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/gnutls.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/jpeg.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/kvazaar.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/lame.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libaom.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libass.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libcharset.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libhogweed.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libiconv.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libilbc.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libnettle.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libogg.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libopencore-amrnb.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libopencore-amrwb.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libpng.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libsndfile.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libtheora.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libtheoradec.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libtheoraenc.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libuuid.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libvorbis.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libvorbisenc.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libvorbisfile.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libvpx.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libwebp.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libwebpdecoder.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libwebpdemux.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libxml2.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/opus.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/shine.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/snappy.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/soxr.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/speex.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/tiff.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/twolame.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/wavpack.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/libvidstab.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/x264.framework, /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/x265.framework, and /Users/ingvi/repositories/App/ios/Pods/mobile-ffmpeg-full-gpl/xvidcore.framework)`

Not sure if I got that working that it would do the trick.

Any idea why react-native-ffmpeg is conflicting with my opencv. I'm using opencv 3.4.2 ios opencv2.framework. OpenCV works well if react-native-ffmpeg is not included.

**Comment by tanersener** [comment]
I did some tests on example 2 from `react-native-ffmpeg-test`. It looks like `use_frameworks!` statement is causing some problems when `mobile-ffmpeg v4.2` is used. Solution is to add a `s.static_framework = true`  line inside `../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec` file used. This will fix build errors for example 2.

I think your tests confirm that there is conflict between `OpenCV` and `mobile-ffmpeg` dependencies. Most probably `opencv` and `mobile-ffmpeg` both include different versions of the same external library. I don't know what are `opencv2.framework` dependencies but as it can be seen in your first post that `full-gpl` package of `mobile-ffmpeg` has many dependencies. Any of them can cause this conflict. I'd recommend to look for `opencv` dependencies first and search for a common external library.

**Comment by ingviso** [comment]
I did work setting `s.static_framework = true` but I'm using firebase and that does not support `use_frameworks!`. I'm able to use react-native-ffmpeg using only `https-gpl` that doesn't create conflict and still do what I need todo.

**Comment by tanersener** [comment]
How can I reproduce the error using `opencv` and `react-native-ffmpeg`? Importing both of them won't be enough I guess.

**Comment by ingviso** [comment]
You could use this [app](https://github.com/yenshih/Dehaze) to test this out, only need to add react-native-ffmpeg to the podfile and then you should see if the imread works in `dehaze_impl.cpp`. It does use djinni so you would have to set that up as well. `run_djinni.sh` should set that mostly up

**Comment by tanersener** [comment]
> It does use djinni so you would have to set that up as well. run_djinni.sh should set that mostly up

How that works? run_djinni.sh fails for me.

```
./run_djinni.sh 
./run_djinni.sh: line 14: thirdparty/djinni/src/run: No such file or directory
```

**Comment by ingviso** [comment]
have you set that as executable `chmod +x run_djinni.sh`

**Comment by tanersener** [comment]
Yes I did. The problem is I don't have a `thirdparty` folder.

**Comment by ingviso** [comment]
put this [into](https://github.com/dropbox/djinni/tree/master/src) that folder

**Comment by tanersener** [comment]
> put this [into](https://github.com/dropbox/djinni/tree/master/src) that folder

thanks, it builds now

**Comment by tanersener** [comment]
Executing `react-native run-ios` without integrating `react-native-ffmpeg` fails with the following error. How do you add `opencv` to this project?

```
/Users/taner/Projects/Dehaze/src/cpp/dehaze_impl.hpp:4:10: fatal error: 'opencv2/core.hpp' file not found
#include <opencv2/core.hpp>
         ^~~~~~~~~~~~~~~~~~
```

**Comment by ingviso** [comment]
just download the ios package from opencv.org and drag that opencv2.framework to the project folder, can also add it using Linked Frameworks and Libraries

**Comment by tanersener** [comment]
Did you receive these errors at some point?
```
Undefined symbols for architecture x86_64:
  "djinni::ProxyCache<djinni::CppProxyCacheTraits>::get(std::__1::type_index const&, std::__1::shared_ptr<void> const&, std::__1::pair<objc_object* __strong, void*> (*)(std::__1::shared_ptr<void> const&))", referenced from:
      OCDehaze* djinni::get_cpp_proxy_impl<OCDehaze, dehaze::Dehaze>(std::__1::shared_ptr<dehaze::Dehaze> const&) in OCDehaze+Private.o
  "djinni::ProxyCache<djinni::CppProxyCacheTraits>::cleanup(std::__1::shared_ptr<djinni::ProxyCache<djinni::CppProxyCacheTraits>::Pimpl> const&, std::__1::type_index const&, void*)", referenced from:
      djinni::ProxyCache<djinni::CppProxyCacheTraits>::Handle<std::__1::shared_ptr<dehaze::Dehaze>, std::__1::shared_ptr<dehaze::Dehaze> >::~Handle() in OCDehaze+Private.o
  "djinni::ProxyCache<djinni::CppProxyCacheTraits>::get_base()", referenced from:
      djinni::ProxyCache<djinni::CppProxyCacheTraits>::Handle<std::__1::shared_ptr<dehaze::Dehaze>, std::__1::shared_ptr<dehaze::Dehaze> >::Handle<>() in OCDehaze+Private.o
  "djinni::throwNSExceptionFromCurrent(char const*)", referenced from:
      +[OCDehaze create] in OCDehaze+Private.o
      -[OCDehaze dehaze:media:] in OCDehaze+Private.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 
```

**Comment by tanersener** [comment]
I finally fixed it.

**Comment by tanersener** [comment]
Some frameworks included in `video`, `full` and `full-gpl` packages is causing this error. Solution is not to link these conflicting frameworks.

In [Dehaze](https://github.com/yenshih/Dehaze) sample application, if you open `Pods-Dehaze.debug.xcconfig` file and remove `-framework "jpeg"` from `OTHER_LDFLAGS` then this error will be resolved.

Additionally you can remove the following frameworks too. They do not cause conflicts in Dehaze, but may do in other applications.

```
-framework "giflib" 
-framework "jpeg" 
-framework "libwebp" 
-framework "libwebpdecoder" 
-framework "libwebpdemux" 
-framework "libpng" 
-framework "tiff"
```
