### ISSUE TITLE
how to make a sound into a video

### ISSUE THREAD

**Issue by wang777777** [tanersener/react-native-ffmpeg#37]
i am an weber developer with js，i was the first time coding react native。now i have a question，how to make a sound into a video，is there anyone can tell me？how to writing the coding？thanks

**Comment by tanersener** [comment]
Can you explain `make a sound`? Do you mean sound synthesis or copying audio from another file?

FFmpeg [wiki](https://trac.ffmpeg.org) includes very good examples about using ffmpeg. Also, If you have a question which is not documented you can ask your question in [ffmpeg-user](https://ffmpeg.org/mailman/listinfo/ffmpeg-user) mailing list. There are many experts on that mailing list.

**Comment by tanersener** [comment]
I'm closing this issue, you can re-open it if you still need help.
