### ISSUE TITLE
how to push video live stream with react native ffmpeg

### ISSUE THREAD

**Issue by thinh185** [tanersener/react-native-ffmpeg#39]
I catch data stream from react native camera then I want use react native ffmpeg to pubish video stream to rtmp server. React native ffmpeg support it ?
Please send me example ?

**Comment by tanersener** [comment]
I didn't test it myself but there is an example in issue #12. Can you check that?

**Comment by thinh185** [comment]
thanks your answer. From issue #12, i have new question. How to add external library enabled in project react native. Please help me

**Comment by thinh185** [comment]
I want add external library `https-gpl` that you recommend in issue #12

**Comment by tanersener** [comment]
Section [2.3](https://github.com/tanersener/react-native-ffmpeg#23-packages) in README explains how a package can be enabled for both Android and IOS. Did you try that?
