### ISSUE TITLE
archive : linker command failed with exit code 1

### ISSUE THREAD

**Issue by teilala** [tanersener/react-native-ffmpeg#4]
XCODE version: 9.4.1
**"dependencies": 
"react": "16.5.0",
"react-native": "0.57.1",
"react-native-ffmpeg": "^0.1.1",**

1.my podfiles:
```
pod 'react-native-ffmpeg-min-gpl', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg-min-gpl.podspec'
 pod 'Firebase'
 pod 'Firebase/Messaging'
```
![2018-09-27 6 09 35](https://user-images.githubusercontent.com/4106105/46139223-8e12cf80-c280-11e8-9928-fbc9e5417c32.png)

2.my podfiles
```
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'react-native-ffmpeg-min-gpl', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg-min-gpl.podspec'
  pod 'Firebase'
  pod 'Firebase/Messaging'
```
**on debug mode it is all good.
but when i archive , i got an error
linker command failed with exit code 1**

**Comment by tanersener** [comment]
@teilala v0.1.1 releases are built with Xcode 10 and I think it is causing the your issue. 
I'm working on supporting older Xcode versions but it will take time.

**Comment by tanersener** [comment]
> linker command failed with exit code 1

> Unfortunately, I have upgrade Xcode v10, but still has same above issue.

It is hard to understand the error above. Can you help me understand?

Editor shows that `React/RCTBridgeModule.h` file is not found. But this is a compile time error and will not generate a linker error.

Additionally, `linker command failed with exit code 1` errors include detail about what went wrong in the previous lines. Can you please share it?

**Comment by tanersener** [comment]
Having `use_frameworks!` in `Podfile` causes some the errors above? Do you have `use_frameworks!` in your `Podfile`?

**Comment by webmasterdragon** [comment]
I have commented this line.
# use_frameworks!

**Comment by teilala** [comment]
I upgrade to xcode version 10
but it's fail , even build on debug mode 
could you upload your pure ios project sample?

**Comment by webmasterdragon** [comment]
Hi @tanersener ,
Could you please share some update?

**Comment by tanersener** [comment]
> I upgrade to xcode version 10
> but it's fail , even build on debug mode
> could you upload your pure ios project sample?
>
> thanks~

Sorry for being late. I don't have a pure ios project. I created a new one for you but I'm still testing. Build process is slow and it takes time to fix items one by one. I'll post an update as soon as it works.

**Comment by tanersener** [comment]
@webmasterdragon 
Be sure that I'm giving my best to find a solution. But it is not easy to understand the errors or status on your environment; ie I don't understand what is meant with 'I have commented this line.'. Was the line already commented out when the tests were performed, or commenting this line didn't make an impact and the build process still fails with the same error?
Additionally I wait @teilala s response on some posts. I'm still not sure whether you have the same error or not.

**Comment by webmasterdragon** [comment]
Same on both case.

**Comment by teilala** [comment]
when I archive on xcode 9 , i got a error is **linker command failed with exit code 1** ,
and previous line is "**ld: 410 duplicate symbols for architecture armv7**"
however , i upgrade xcode 10 , and I create a new project With react native , and It's pure , just for ffmpeg, the podFile like above ..
1.
```
target 'zfii' do
  pod 'react-native-ffmpeg-min-gpl', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg-min-gpl.podspec'

end
```
**got same issue , React/RCTBridgeModule.h file not found**
2.
```
target 'zfii' do
   pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-ffmpeg-min-gpl', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg-min-gpl.podspec'

end
```
this is good , but last night I got a Pod install fail (@@?) 
anyway, it is work on debug mode.
and then build on archive  , got a error `Xcode 10 Error: Multiple commands produce` , 
my solution is `Go to Xcode -> File ->Workspace Settings. Select "Legacy Build System" from Build System tag. Press on "Done` , it seems to be solved , 
but I got another error ,that was the error I got on xocde 9 .
 "clang: error: linker command failed with exit code 1 (use -v to see invocation)"

![2018-09-28 3 40 00](https://user-images.githubusercontent.com/4106105/46194890-44d08780-c335-11e8-84f6-685c602eb7f7.png)

**Comment by tanersener** [comment]
It looks like two `React` libraries (libReact.a, libRTCWebsocket.a) define the same symbol and this is causing an error. One of them should be transitive I guess. Looking at it.

**Comment by tanersener** [comment]
Can you open `ReactNativeFFmpeg.xcodeproj` from `../node_modules/react-native-ffmpeg/ios` and delete `React` project inside. Then try to build your app again?

**Comment by teilala** [comment]
same issue , 
![2018-09-28 4 46 30](https://user-images.githubusercontent.com/4106105/46198061-1c00c000-c33e-11e8-9acf-0ac1d3b2e5e3.png)

**Comment by tanersener** [comment]
Tried several things but none of them worked. I don't thing `Legacy Build System` should be used to overcome this error.

I reverted back to the new build system, now trying to fix your first error `React/RCTBridgeModule.h not found`. This error should be fixed when `React` is added inside `Target Dependencies` of `react-native-ffmpeg`. Can you try that?

**Comment by teilala** [comment]
> This error should be fixed when React is added inside Target Dependencies of react-native-ffmpeg.

how to do ? 
add ../node_modules/react-native-ffmpeg/ios/ReactNativeFFmpeg.xcodeproj to Libraries ,and choose it , and then in Build Phases ,add React , but I dont know how to do this ?

**Comment by webmasterdragon** [comment]
Same here how to do this?

**Comment by tanersener** [comment]
I mean this

<img width="907" alt="linking" src="https://user-images.githubusercontent.com/10158439/46205197-71ca6d80-c328-11e8-93f1-7afe5210562c.png">

**Comment by webmasterdragon** [comment]
![reactnative](https://user-images.githubusercontent.com/29256561/46205450-d3033880-c34a-11e8-863b-ea925f9132b2.PNG)

**Comment by tanersener** [comment]
Do you get this error after adding `React` dependency? This error looks unrelated to my recommendation, error message says `unable to open file` for `.xcconfig`.

**Comment by webmasterdragon** [comment]
Yes. After added.

**Comment by webmasterdragon** [comment]
![react](https://user-images.githubusercontent.com/29256561/46206264-a1d83780-c34d-11e8-8fce-396c7a8fa950.PNG)
And on other project using react-native-ffmpeg, I cannot find React link.

**Comment by tanersener** [comment]
> And on other project using react-native-ffmpeg, I cannot find React link.

React is added to workspace when `pod install` is run. Did you run `pod install`?

**Comment by webmasterdragon** [comment]
Yes.
My pod file.

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'iosbrivvio' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iosbrivvio
  pod 'react-native-ffmpeg', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec'

end

target 'iosbrivvio-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iosbrivvio-tvOS

  target 'iosbrivvio-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

**Comment by tanersener** [comment]
I see that you have `-tvOS` postfix in your targets. I didn't do anything so support `tvOS` yet and I didn't make any tests on this platform either. Are you sure it is not causing an error?

**Comment by webmasterdragon** [comment]
I will try without `-tvOS`.

**Comment by webmasterdragon** [comment]
Result is same .

**Comment by tanersener** [comment]
I made some changes on [development branch](https://github.com/tanersener/react-native-ffmpeg/tree/development). You can apply them if you want to see my current development effort.

Some of the changes are;
- Using `test-app` from the project repository is causing linking errors. So I moved into another repository [react-native-ffmpeg-test](https://github.com/tanersener/react-native-ffmpeg-test). 
- There are two versions there, `default` is working for me, but `ios-frameworks` is not. I'm working on `ios-frameworks` right now, because it gives similar errors to yours. I believe fixing it will help fixing your errors.

**Comment by teilala** [comment]
oh~~~my dear, I can run it on simlator and physical device, but I need release build with archive
![2018-09-28 9 05 10](https://user-images.githubusercontent.com/4106105/46210048-351b6800-c362-11e8-8e65-bc60a998237e.png)

**Comment by webmasterdragon** [comment]
@teilala  Great.
Could you please share react-native dev info and details about how to fix issue ?
Thanks.

**Comment by tanersener** [comment]
> oh~~~my dear, I can run it on simlator and physical device, but I need release build with archive , and it will be fail like this, **linker command failed with exit code 1**
> 

OK, that `archive` 👍 

Well, it works for me, can you share the screenshot of the linker error window?

**Comment by webmasterdragon** [comment]
**Using react-native run-ios**

```
** BUILD FAILED **


The following build commands failed:
        CompileC /Users/webbusiness/Sites/iosbrivvio/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-ffmpeg.build/Objects-normal/x86_64/RNFFmpegModule.o /Users/webbusiness/Sites/iosbrivvio/ios/Pods/react-native-ffmpeg/ios/RNFFmpegModule.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Using Xcode build.**
![1](https://user-images.githubusercontent.com/29256561/46211634-41052b00-c35e-11e8-9b51-771cfb2fd2b5.PNG)
![2](https://user-images.githubusercontent.com/29256561/46211635-41052b00-c35e-11e8-91b7-dd8b3c7c5e4d.PNG)

**My dev info.**

> React Native Environment Info:
>     System:
>       OS: macOS High Sierra 10.13.6
>       CPU: x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
>       Memory: 120.02 MB / 8.00 GB
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 8.11.4 - /usr/local/bin/node
>       npm: 5.6.0 - /usr/local/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     SDKs:
>       iOS SDK:
>         Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
>       Android SDK:
>         Build Tools: 23.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2
>         API Levels: 23, 25, 26, 27, 28
>     IDEs:
>       Android Studio: 3.1 AI-173.4907809
>       Xcode: 10.0/10A255 - /usr/bin/xcodebuild
>     npmPackages:
>       react: 16.5.0 => 16.5.0 
>       react-native: 0.57.1 => 0.57.1 
>     npmGlobalPackages:
>       create-react-native-app: 1.0.0
>       react-native-cli: 2.0.1

**Comment by tanersener** [comment]
@teilala Could you please share the screenshot of your linker error too?

**Comment by teilala** [comment]
> @teilala Could you please share the screenshot of your linker error too?

I have shared it with you before.
like this.
![2018-09-28 4 46 30](https://user-images.githubusercontent.com/4106105/46212559-db6a6c00-c368-11e8-822d-5b5c320bbdcd.png)

**Comment by teilala** [comment]
> **Using react-native run-ios**
> 
> ```
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
>         CompileC /Users/webbusiness/Sites/iosbrivvio/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-ffmpeg.build/Objects-normal/x86_64/RNFFmpegModule.o /Users/webbusiness/Sites/iosbrivvio/ios/Pods/react-native-ffmpeg/ios/RNFFmpegModule.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
> ```
> **Using Xcode build.**
> ![1](https://user-images.githubusercontent.com/29256561/46211634-41052b00-c35e-11e8-9b51-771cfb2fd2b5.PNG)
> ![2](https://user-images.githubusercontent.com/29256561/46211635-41052b00-c35e-11e8-91b7-dd8b3c7c5e4d.PNG)
> 
> **My dev info.**
> 
> ### React Native Environment Info:
> ```
> System:
>   OS: macOS High Sierra 10.13.6
>   CPU: x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
>   Memory: 120.02 MB / 8.00 GB
>   Shell: 3.2.57 - /bin/bash
> Binaries:
>   Node: 8.11.4 - /usr/local/bin/node
>   npm: 5.6.0 - /usr/local/bin/npm
>   Watchman: 4.9.0 - /usr/local/bin/watchman
> SDKs:
>   iOS SDK:
>     Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
>   Android SDK:
>     Build Tools: 23.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2
>     API Levels: 23, 25, 26, 27, 28
> IDEs:
>   Android Studio: 3.1 AI-173.4907809
>   Xcode: 10.0/10A255 - /usr/bin/xcodebuild
> npmPackages:
>   react: 16.5.0 => 16.5.0 
>   react-native: 0.57.1 => 0.57.1 
> npmGlobalPackages:
>   create-react-native-app: 1.0.0
>   react-native-cli: 2.0.1
> ```

PODFIle add below
```
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
```

**Comment by webmasterdragon** [comment]
Great. After added this pod, I can build on Xcode. A++
So this error is related pod file?

**Comment by tanersener** [comment]
Can you add the following block to your `Podfile` and try again?

```
# do not allow Cocoapods to manage React dependencies
post_install do |installer|
    installer.pods_project.targets.each do |target|
      targets_to_ignore = %w(React yoga)
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
    end
end
```

**Comment by webmasterdragon** [comment]
I tried also before add pod @teilala 's comment.
But same issue was there.

**Comment by tanersener** [comment]
> Can you add the following block to your `Podfile` and try again?
> 
> ```
> # do not allow Cocoapods to manage React dependencies
> post_install do |installer|
>     installer.pods_project.targets.each do |target|
>       targets_to_ignore = %w(React yoga)
>       if targets_to_ignore.include? target.name
>         target.remove_from_project
>       end
>     end
> end
> ```

@teilala this block fixed `archive` errors for one of my test-applications, I hope you haven't already tried it ?

**Comment by teilala** [comment]
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'zfii' do
   pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-ffmpeg', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      targets_to_ignore = %w(React yoga)
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
    end
end
```
Archive result , no fix pod 
![2018-09-28 11 15 45](https://user-images.githubusercontent.com/4106105/46217450-9815fa80-c374-11e8-9a3e-238f0d49d9e9.png)

**Comment by teilala** [comment]
wow, I Just run pod install , 
NO other ways
no Add  ReactNativeFFmpeg.xcodeproj from ../node_modules/react-native-ffmpeg/ios to Library.
no Add react to Pods Target Dependencies 

And then , it SUCCESS ! thank you,  next i Will try it on my work project.

**Comment by webmasterdragon** [comment]
@teilala , Could you please share latest pod file?
I got archive error on Xcode, but debug is fine.

**Comment by webmasterdragon** [comment]
My pod is like this.
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosbrivvio' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iosbrivvio
  pod 'react-native-ffmpeg', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'


  pod 'react-native-video', :path => '../node_modules/react-native-video'

end
```

> wow, I Just run pod install ,
> NO other ways
> no Add ReactNativeFFmpeg.xcodeproj from ../node_modules/react-native-ffmpeg/ios to Library.
> no Add react to Pods Target Dependencies
> 
> And then , it SUCCESS ! thank you, next i Will try it on my work project.

How do I this?

**Comment by webmasterdragon** [comment]
![3](https://user-images.githubusercontent.com/29256561/46224428-92bead00-c380-11e8-887d-4a9da82089d7.PNG)

Now I have two issue during achieve.

**Comment by tanersener** [comment]
@webmasterdragon 
as I posted before, the following block fixes your latest errors.

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
      targets_to_ignore = %w(React yoga)
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
    end
end
```

**Comment by teilala** [comment]
> @teilala , Could you please share latest pod file?
> I got archive error on Xcode, but debug is fine.
```# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'zfii' do
   pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-ffmpeg', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      targets_to_ignore = %w(React yoga)
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
    end
end
```
my test project is fine ,
but my original  project is fail , at pod install ,can't find "react core" ~~~
anyway ,i create new project , and now it's good .

**Comment by tanersener** [comment]
@teilala do you still have errors, can we close this issue?

**Comment by ingviso** [comment]
Is there a fix for this, I think I have tried the solutions that are in this conversion but still getting the 'React/RCTBridgeModule.h' file not found

**Comment by ingviso** [comment]
I did add this to my podfile not sure if that is necessary
```
pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
```

But that led to alot of different issues.

I tried the comment below and that did not do the trick
`watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf node_modules/ && npm cache verify && yarn install && npm start -- --reset-cache`

I'm going to test with default-test-application

**Comment by tanersener** [comment]
> But that led to alot of different issues.

There are different ways to do it. I preferred to use this way as described in [Integration with Existing Apps](https://facebook.github.io/react-native/docs/integration-with-existing-apps) documentation.

**Comment by ingviso** [comment]
The issue I get when I have this podfile
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!

target 'App' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for App
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  #pod 'Firebase/Database'

  # pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'
  # pod 'react-native-ffmpeg', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec'
  # pod 'react-native-version-check', :path => '../node_modules/react-native-version-check'



  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'jschelpers',
    'cxxreact',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTWebSocket', # needed for debugging
  ]

  # To use CocoaPods with React Native, you need to add this specific Yoga spec as well
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  # Third party deps
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'

  pod 'react-native-ffmpeg', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'kulaScopeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

My RNCamera fails, I get 

`/ios/Pods/Folly/folly/string.h:20:10: 'exception' file not found`

`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: Could not build module 'Darwin'`

`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:10: Could not build module 'CoreFoundation'`

Any thoughts ?

**Comment by tanersener** [comment]
> /ios/Pods/Folly/folly/string.h:20:10: 'exception' file not found

It happens sometimes. You need to ask google about it. One of the recommendations is `This happens when your pod cache is corrupted. Try cleaning the Xcode project, then the build folder, then the DerivedData folder, then the pod cache, then run again pod install.`.

The following block is important. I always recommend including it.

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
      targets_to_ignore = %w(React yoga)
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
    end
end
```

**Comment by ingviso** [comment]
I fixed it, I was originaly was manually linking RNcamera and had added the xcodeproj to libraries, deleted that and just use the pod. Now that is resolved do get now:
```
/usr/bin/codesign --force --sign EA9661AF05AC1D4E26EEF54C260125388BECC966  --preserve-metadata=identifier,entitlements '/var/root/Library/Developer/Xcode/DerivedData/kulaScope-epenpjkzvrczlebtuzycribmdyfq/Build/Products/Debug-iphoneos/App.app/Frameworks/mobileffmpeg.framework'
error: The specified item could not be found in the keychain.
```
Have you seen this before?
Probably something on my part that is causing thisæ

**Comment by tanersener** [comment]
> Have you seen this before?
> Probably something on my part that is causing thisæ

I was getting a similar error when my developer profile has expired. Renewing it fixed it for me. It should be something similar.
