### ISSUE TITLE
How can I use custom fonts?

### ISSUE THREAD

**Issue by fedefloris** [tanersener/react-native-ffmpeg#40]
Hello,
I've got some problems while using `RNFFmpeg.setFontDirectory`.
I need to use my custom fonts that I linked to the app with **react-native-asset**.
The fonts are located inside **assets/fonts** folder.

On Android for example it works when I'm using the system fonts folder and the default font **DroidSans**:
`RNFFmpeg.setFontDirectory(['/system/fonts/']);`
I also noticed that on Android `setFontDirectory` seems to take an array and not a single string.

On FFmpeg I'm using the **drawtext** ffmpeg filter, an example could be:
`...drawtext=fontcolor=white:fontsize=50:x=150:y=150:font=Roboto-Thin:text='Hi!'...`
with **Roboto-Thin** located in `assets/fonts/Roboto-Thin.ttf`
With this example I'm getting this error: **Cannot find a valid font for the family Roboto-Thin**

**Comment by tanersener** [comment]
> I also noticed that on Android `setFontDirectory` seems to take an array and not a single string.

In fact, Android module is designed to take two parameters. But the second parameter is not exposed in the Javascript interface. Let met make some tests to see if it will be possible to use `Roboto-Thin` font without changing the interface.

**Comment by fedefloris** [comment]
Sure, thanks a lot!

**Comment by tanersener** [comment]
`RNFFmpeg.setFontDirectory` accepts the full path of a custom font directory but the behavior  is unpredicted when a relative path is used. `RNFFmpeg` module is not aware of project root, so it can't build the full path using a relative path. I recommend using full path of your assets directory. Unfortunately I don't know how to do that on `react-native-asset`, I use `react-native-fs` for similar tasks.

**Comment by fedefloris** [comment]
I see, I'm gonna try to use `react-native-fs` next week.
I'll let you know how it goes.

**Comment by fedefloris** [comment]
Okay, apparently it works on Android.
I have my assets loaded with `react-native-asset`, so I can use `RNFS.copyFileAssets` to copy the fonts inside `RNFS.DocumentDirectoryPath`.
Then I call `RNFFmpeg.setFontDirectory(RNFS.DocumentDirectoryPath, null)`
The problem now is supporting iOS, I didn't find a way to access the assets folder.
Do you have any ideas?

**Comment by tanersener** [comment]
Resources/assets can be accessed without using an `RNFS.copyFileAssets` step on IOS. You just need to find the relative path of your asset. 

I don't know how `react-native-asset` packages assets. But you can find it yourself by browsing your application directory under `CoreSimulator`. On my machine it has a path like `~/Library/Developer/CoreSimulator/Devices/UUID/data/Containers/Bundle/Application/UUID/MyTest.app`. Find your asset under application directory and build the full path with `RNFS.MainBundlePath`.

It should be something like `RNFS.MainBundlePath + '/assets/' + assetName`.
