### ISSUE TITLE
How to increase Android ffmpeg convert speed?

### ISSUE THREAD

**Issue by webmasterdragon** [tanersener/react-native-ffmpeg#48]
**Description**
Android FFmpeg convert takes longer than iOS.

**Expected behavior**
Increase convert speed as much as iOS.

**Current behavior**
Took 2~3 times than iOS

**Logs**
Convert logs: https://ghostbin.com/paste/2zcp6
Emulator info: https://ghostbin.com/paste/bcytg

**Environment**
 - React Native Environment Info
```
System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-4570S CPU @ 2.90GHz
      Memory: 707.80 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.0.0 => 16.6.0 
      react-native: ^0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Other**
I have tried android devices and emulator. Both are taken long time.
When I am trying to convert 1 mins video, it took 4~5 mins. so not good. Please check logs.
Also trying to convert on iOS, it is really fast. I know it is depends on device performance(maybe CPU or RAM), but initially need to how to optimize conversion time. Thanks.

**Comment by tanersener** [comment]
Comparing `Android Emulator` vs. `IOS Simulator` is not a good idea. One of them is `Emulator` and the other one is `Simulator`. It is accepted by everyone that `IOS Simulator` is faster.

I don't know whether there is a performance difference between `Android` and `IOS` binaries or not. It is necessary to perform the same test on two physical devices with near or identical CPU & RAM configurations to say one of them is faster. Can you provide logs for the same command on similar Android & IOS architectures?

**Comment by relivetech** [comment]
Facing same issue is anyone there too solve this.

**Comment by Richi2293** [comment]
Hi,
nothing new? Me on Android it takes a mess of time even for videos under a minute

**Comment by leandroromano** [comment]
I have already tested compression with a lot of Android phones, which have good specs and the video compression is still very slow (avg from 2 min to 3 min, in a 15 sec video). Will it be fixed ?

**Comment by tanersener** [comment]
I agree that the speed of encode/decode operations on Android is awful. But I don't have any ideas to improve the speed. 

There is a performance hit in using `react-native`. If performance is an issue for you then I suggest calling those methods natively using `mobile-ffmpeg`.
