### ISSUE TITLE
Did not receive output

### ISSUE THREAD

**Issue by JayricMok** [tanersener/react-native-ffmpeg#49]
I using react-native-image-picker to pick the video and get the file path, however i cannot find any output when the execution done, following below is my code

      ImagePicker.showImagePicker(options, (response) => {
        let outputpath = response.path.replace('myvideo.mp4','output.mp4');
        RNFFmpeg.executeWithArguments(["-i", response.path , "-filter:v", "setpts=0.05*PTS", "-an", outputpath]).then(result => console.log("FFmpeg process exited with rc " + result.rc));
      });

**Comment by tanersener** [comment]
Can you provide the console logs of this test?

**Comment by JayricMok** [comment]
This is the whole screenshot console log when the ffmpeg start running, it seem like run properly, however can't find any output in my phone

**01**
![01](https://user-images.githubusercontent.com/6957533/53282958-fd321880-3779-11e9-8ca5-f987dc091e18.PNG)
**02**
![02](https://user-images.githubusercontent.com/6957533/53282961-0a4f0780-377a-11e9-90f1-361997757011.PNG)
**03**
![03](https://user-images.githubusercontent.com/6957533/53282963-12a74280-377a-11e9-8cb6-9561540147f5.PNG)
**04**
![04](https://user-images.githubusercontent.com/6957533/53282965-19ce5080-377a-11e9-8835-8424397215cd.PNG)
**05**
![05](https://user-images.githubusercontent.com/6957533/53282969-205cc800-377a-11e9-8834-5896d1b099ec.PNG)
**06**
![06](https://user-images.githubusercontent.com/6957533/53282973-28b50300-377a-11e9-8edf-970d0f2ece2a.PNG)
**07**
![07](https://user-images.githubusercontent.com/6957533/53282977-2f437a80-377a-11e9-89cc-d03ab736d781.PNG)

**Comment by JayricMok** [comment]
i know why no receiving output

**Comment by HemanthSurimani** [comment]
@callmejm 

could you please mention detailed answer

**Comment by issamabdelkrim** [comment]
@callmejm could you please mention how you fixed this bug 
i have the same bug
