### ISSUE TITLE
react-native run-android failed

### ISSUE THREAD

**Issue by AlexandruVoica** [tanersener/react-native-ffmpeg#5]
Hello. This package looks very promising.

Unfortunately I ran into a problem right from the get-go!

Order of operations: 

```
npm i react-native-ffmpeg

react-native link react-native-ffmpeg

react-native run-android
```

This is the error message: 

```
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/alexandru.voica/Projects/Kidgarten/app/node_modules/react-native-ffmpeg/android/build.gradle' line: 6

* What went wrong:
A problem occurred evaluating project ':react-native-ffmpeg'.
> Could not find method google() for arguments [] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.
```

**Comment by AlexandruVoica** [comment]
Deleting the google() from inside react-native-ffmpeg/android/build.gradle yielded the following error:
 
```
react-native-ffmpeg'.
      > Could not resolve all dependencies for configuration ':react-native-ffmpeg:classpath'.
         > Could not find com.android.tools.build:gradle:3.1.4.
           Searched in the following locations:
               https://jcenter.bintray.com/com/android/tools/build/gradle/3.1.4/gradle-3.1.4.pom
               https://jcenter.bintray.com/com/android/tools/build/grAAAA\[At-nati
```

**Comment by tanersener** [comment]
Unfortunately `google()` is needed to successfully build `Android`.

Could you please try building with `gradle 4.x`, `google()` method was added in `v4.x` as far as I remember?

**Comment by AlexandruVoica** [comment]
Indeed, I am using `gradle 3.1.4`, but all other packages work as expected. Strange.

Unfortunately, I think I am unable to update gradle because of other version constraints. 

I think you can close this issue. 

Regardless, thank you for your response.

**Comment by tanersener** [comment]
`google()` method is just a shortcut to add google's `maven` repository. If you can't update your gradle, it is possible to replace `google()` with the following block. It is actually what `google()` does.

```
maven {
    url 'https://maven.google.com'
}
```

**Comment by tanersener** [comment]
I'm closing this issue, you can re-open it if you need help.

**Comment by AKclown** [comment]
Hello, I also encountered the same problem. This has been confusing me for a day. Can you give me some suggestions?
![image](https://user-images.githubusercontent.com/33648653/125009985-3a23af00-e098-11eb-88ae-d6a3e014d3e7.png)
