### ISSUE TITLE
Help Needed in Converting ffmpeg cli code to react-native-ffmpeg code

### ISSUE THREAD

**Issue by renganatha10** [tanersener/react-native-ffmpeg#51]
**Description**

Hi Thanks for the Repo. This is not issue related to this repo. I need your help in converting this `ffmpeg -i input.avi -vcodec libx264 -x264-params crf=18 -preset veryslow -acodec copy out.mp4` to command understands by react-native-ffmpeg. I am using packagename `full` to do this. but i get error `-x264-params not found`

**Comment by tanersener** [comment]
`x264` is included in `gpl` packages. Can you try with `full-gpl` package?
