### ISSUE TITLE
Queries on FFMPEG and FFMPEG on mobile

### ISSUE THREAD

**Issue by renganatha10** [tanersener/react-native-ffmpeg#53]
**Description**

I am trying to understand FFMPEG and FFMPEG on Mobile. Maybe this is a stupid issue. 

1). I am reducing the volume of mp3 file but FFmpeg uses `libmp3lame` but I am not sure which package has `libmp3lame` library. I have to use `full-GPL`.

2). What is your stand on the IOS app using frameworks or libraries having GPL licenses?. I have read that Apple rejects app using GPL license framework.

3). Using libx264 on IOS crashes the App due to a lot of Memory. Any tips or hack to make libx264 work on ios without crash.

Happy to have a discussion here As a JS developer these terminologies and techniques are confusing.

**Comment by tanersener** [comment]
> 1). I am reducing the volume of mp3 file but FFmpeg uses `libmp3lame` but I am not sure which package has `libmp3lame` library. I have to use `full-GPL`.
>

[Section 1](https://github.com/tanersener/react-native-ffmpeg#1-features) in README lists all packages and external libraries inside them. `lame` is included in `audio`, `full` and `full-gpl` packages.

> 2). What is your stand on the IOS app using frameworks or libraries having GPL licenses?. I have read that Apple rejects app using GPL license framework.
> 

I don't present a different view about licensing with this project. Conditions of LGPL and GPL are clear. You can publish your application in App Store if your application meets those conditions. I summarized those conditions on [this wiki page](https://github.com/tanersener/mobile-ffmpeg/wiki/Using-MobileFFmpeg-in-Commercial-Applications) for another project but they are valid for `react-ffmpeg` too.
 
> 3). Using libx264 on IOS crashes the App due to a lot of Memory. Any tips or hack to make libx264 work on ios without crash.
> 

There are a lot of options in [FFmpeg h264 Guide](https://trac.ffmpeg.org/wiki/Encode/H.264). You can try some of them.
