### ISSUE TITLE
Build Failed : More than one file was found with OS independent path 'lib/x86/libc++_shared.so'

### ISSUE THREAD

**Issue by c1ngular** [tanersener/react-native-ffmpeg#54]
**Description**
> Task :app:transformNativeLibsWithMergeJniLibsForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> More than one file was found with OS independent path 'lib/x86/libc++_shared.so'

`
React Native Environment Info:
    System:
      OS: macOS 10.14.2
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 592.43 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash

    Binaries:
      Node: 11.9.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman

    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1

      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 27.0.3, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64

    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild

    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1 

    npmGlobalPackages:
      react-native-cli: 2.0.1`

 a totally new project , no other packages/plugin installed other than react-native-ffmpeg, no idea why, i remember it was working perfectly when i tried this project last time , is it related to react-native version ?  and i assume there will be more such error other than "lib/x86/libc++_shared.so" ?

**Comment by c1ngular** [comment]
i added :  
`
    packagingOptions {
        exclude 'lib/x86/libc++_shared.so'
        exclude 'lib/arm64-v8a/libc++_shared.so'
        exclude 'lib/x86_64/libc++_shared.so'        
        exclude 'lib/armeabi-v7a/libc++_shared.so'           
    }
`
to build.gradle file , it builds , but app crashed on start up , android studio shows : 
`
31839-31954/com.hls2mp4 E/SoLoader: Error when loading lib: dlopen failed: library "libc++_shared.so" not found lib hash: 52bef5aa0fb455a23735042f417edc9a search path is /data/app/com.hls2mp4-vAWXk1fv9rTP7_wVw2LuNw==/lib/arm64

31839-31954/com.hls2mp4 E/SoLoader: couldn't find DSO to load: libreactnativejni.so caused by: dlopen failed: library "libc++_shared.so" not found

31839-31954/com.hls2mp4 E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.hls2mp4, PID: 31839
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so caused by: dlopen failed: library "libc++_shared.so" not found
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:31)
        at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:19)
        at com.facebook.react.jscexecutor.JSCExecutorFactory.create(JSCExecutorFactory.java:25)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:944)
        at java.lang.Thread.run(Thread.java:764)
`

**Comment by c1ngular** [comment]
not sure if related , i was prompted by Android studio to update NDK version to 19.2.5345600, before that , i remember this package is working pretty well .

**Comment by c1ngular** [comment]
@tanersener 
 i tried to downgrade NDK to r18b version, not working
i tried to downgrade React Native version to 0.58.0 and 0.58.6 , problem seems resolved , it builds and runs , so i guess it is caused by RN ? 
 from change log of 0.59.0 : 

> Soloader is now at v0.6.0 (07d1075 by @dulmandakh)

**Comment by dulmandakh** [comment]
React Native was using gnustl before, but now it uses libc++ and bundles it
in. That's why you are having this issue. Solution would remove libc++ from
the bundle and release a new version.

**Comment by c1ngular** [comment]
@dulmandakh  thank you for help  !

**Comment by tanersener** [comment]
I can safely say that it is not related to NDK version. It looks like something new in `react-native` is causing this as @dulmandakh pointed out. I need to perform some tests before confirming this.

**Comment by tanersener** [comment]
as @dulmandakh pointed out, `libgnustl_shared.so` is replaced with `libc++_shared.so` in `react-native 0.59`. `react-native-ffmpeg` already includes `libc++_shared.so` so using `react-native 0.59` causes the `More than one file was found with OS independent path 'lib/x86/libc++_shared.so'` error.

In short term, sticking

**Comment by tanersener** [comment]
This issue will be fixed it in the next release which is planned to be published in the first week of April.

**Comment by c1ngular** [comment]
any update ?

**Comment by tanersener** [comment]
It looks like it won't be possible to remove `libc++_shared.so` library from the package. 

So official workaround to use `RN 0.59` is to add this block in `build.gradle` for Android.

```
packagingOptions {
    pickFirst 'lib/x86/libc++_shared.so'
    pickFirst 'lib/x86_64/libc++_shared.so'
    pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    pickFirst 'lib/arm64-v8a/libc++_shared.so'
}
```

**Comment by c1ngular** [comment]
@tanersener thanks

**Comment by c1ngular** [comment]
@tanersener  it builds and runs , but it failed packaging with error below :
> Task :react-native-ffmpeg:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-ffmpeg:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/s1ngular/Projects/RNative/webvideo/node_modules/react-native-ffmpeg/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/s1ngular/Projects/RNative/webvideo/node_modules/react-native-ffmpeg/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/s1ngular/Projects/RNative/webvideo/node_modules/react-native-ffmpeg/android/build/intermediates/res/merged/release/values/values.xml:2724: error: resource android:attr/fontVariationSettings not found.
  /Users/s1ngular/Projects/RNative/webvideo/node_modules/react-native-ffmpeg/android/build/intermediates/res/merged/release/values/values.xml:2725: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

**Comment by tanersener** [comment]
Can you share your `package.json` and `build.gradle`? So I can test your case locally?

**Comment by c1ngular** [comment]
package.json:
  "dependencies": {
    "i18n-js": "^3.2.1",
    "lodash.memoize": "^4.1.2",
    "react": "16.8.3",
    "react-native": "0.59.1",
    "react-native-ffmpeg": "^0.3.1",
    "react-native-firebase": "^5.2.3",
    "react-native-fs": "^2.13.3",
    "react-native-keep-awake": "^4.0.0",
    "react-native-localize": "^1.1.1",
    "react-native-progress": "^3.6.0",
    "react-native-safe-area-view": "^0.13.1",
    "react-native-vector-icons": "^6.3.0",
    "react-native-video": "^4.4.0",
    "react-native-webview": "git+https://github.com/c1ngular/react-native-webview.git"
  }

build.gradle:

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
        classpath 'com.google.gms:google-services:4.0.2'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

**Comment by c1ngular** [comment]
@tanersener 

when i tried to build first time , it give two errors:
1. android:allowBackup="true/false" conflict , i changed my AndroidManifest.xml , **android:allowBackup=true**
2. minsdk version conflict ,i changed minSdkVersion from 16 to 21 

besides changes above , i added **lintOption** and **packagingOption** to build.gradle,
please take a look , thanks !

**Comment by tanersener** [comment]
Do you have `AndroidX` enabled in `gradle.properties`?

**Comment by c1ngular** [comment]
@tanersener  no , just release key store configurations , nothing more

**Comment by c1ngular** [comment]
@tanersener  i was able to package after i changed compileSdkVersion and targetSdkVersion to 28 from ~/node_modules/react-native-ffmpeg/android/build.gradle

**Comment by tanersener** [comment]
Well, editing files under `~/node_modules` is not a good practice but today or tomorrow a new `react-native-ffmpeg` release will be published with compileSdkVersion and targetSdkVersion set to 28. So I can say it is OK temporarily.

**Comment by tanersener** [comment]
`v0.3.2` is released and the fix for this issue is documented in [Tips](https://github.com/tanersener/react-native-ffmpeg#6-tips) section.
