### ISSUE TITLE
[Feature] Better control over binary selection

### ISSUE THREAD

**Issue by erandagan** [tanersener/react-native-ffmpeg#55]
**Description**
Currently, in order to change the FFMpeg (binary) version, you have to manually edit files under the `node_modules` folder. This is a problematic approach as:
- Your changes will be lost every time you re-install your modules (say, on a CI server or a new dev machine)
- Node modules are never under git, so you can't share the project configuration with other team members.

**Suggested approach**
- For android: Read the FFMpeg version from `rootProject.ext.ffmpegVersion`, similar to how other popular React Native libraries get their configuration. This is a much more "native" approach, and leverages Gradle properly.

The user configuration will look like this:
```gradle
ext {
  ffmpegVersion: 'example-version-4.12-full'
  ...
  ...
}
```
- For iOS: I'm not too familiar with Cocoapods, but I've had some luck by simply pointing to the podspec I want to use rather than the root podspec. Maybe it's worth updating the README or providing a more "official" way of doing that.

**Comment by tanersener** [comment]
I'm not a fan of the current approach either but there are multiple versions and packages defined in this library. It's really hard to separate them without creating a confusion for users.

Which libraries use your approach, can you give me an example? I tried to define something similar to [react-native-fs](https://github.com/itinance/react-native-fs).

**Comment by erandagan** [comment]
Sure. There are many libraries which do that, but here are 3 very popular libraries which that use the `ext` approach:

[react-native-lottie uses ext to get the SDK versions](https://github.com/react-native-community/lottie-react-native/blob/7e891ef2cda23f62356d51787ac835612e6571a7/src/android/build.gradle)

[react-native-maps uses ext to get the support library version it should use](https://github.com/react-native-community/react-native-maps/blob/0a2476ad4578ed8b29de460a62777944818226bc/lib/android/build.gradle)

[react-native-camera uses ext to get the google play services library version it should use](https://github.com/react-native-community/react-native-camera/blob/773d5e88bac60681b90209e8195921b119cd5265/android/build.gradle)

**Comment by tanersener** [comment]
Thanks, I think package and version selection can be simplified for Android. 
Unfortunately I don't have something similar in Cocoapods. I have to work on that.

**Comment by tanersener** [comment]
I made some changes on the development branch and updated the [README](https://github.com/tanersener/react-native-ffmpeg/tree/development). Is there any other improvements you'd suggest?

**Comment by erandagan** [comment]
Looks great, thanks for implementing this and the work you've put into this package!

**Comment by tanersener** [comment]
Thanks for helping me improve it.
