### ISSUE TITLE
Create a thumbnail image from a video

### ISSUE THREAD

**Issue by hamzashahbaz** [tanersener/react-native-ffmpeg#59]
Running FFmpeg command: -y -i /Users/hamza/Library/Developer/CoreSimulator/Devices/FE0CB277-54AD-413B-9C0F-D50427ED8C56/data/Containers/Data/Application/C2088162-769D-421E-B374-F51116FCF155/Library/Caches/test1.mp4 -vframes 1 -filter_complex thumbnail=5,scale=-1:120,tile=5x1 sample.jpg with delimiter  .

RCTLog.js:47 FFmpeg exited with rc: 1

index.js:25 0
index.js:70 ffmpeg version v4.2-dev-480
index.js:70  Copyright (c) 2000-2018 the FFmpeg developers
index.js:70 

index.js:70   built with Apple LLVM version 7.3.0 (clang-703.0.31)

index.js:70   configuration: --sysroot=/Applications/Xcode-v7.3.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk --prefix=/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/ffmpeg --enable-version3 --arch=x86_64 --cpu=x86_64 --target-os=darwin --ar=/Applications/Xcode-v7.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar --cc=/Applications/Xcode-v7.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang --cxx=/Applications/Xcode-v7.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ --as='/Applications/Xcode-v7.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -target x86_64-ios-darwin -march=x86-64 -msse4.2 -mpopcnt -m64 -mtune=intel -DMOBILE_FFMPEG_X86_64 -Wno-unused-function -Wno-deprecated-declarations -fstrict-aliasing -DIOS -DMOBILE_FFMPEG_LTS -isysroot /Applications/Xcode-v7.3.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -O2 -mios-simulator-version-min=9.3 -I/Applications/Xcode-v7.3.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/usr/include' --ranlib=/Applications/Xcode-v7.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib --strip=/Applications/Xcode-v7.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip --disable-neon --enable-cross-compile --enable-pic --enable-asm --enable-inline-asm --enable-optimizations --enable-swscale --enable-static --disable-shared --enable-small --disable-v4l2-m2m --disable-outdev=v4l2 --disable-outdev=fbdev --disable-indev=v4l2 --disable-indev=fbdev --disable-openssl --disable-xmm-clobber-test --disable-debug --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --disable-appkit --disable-alsa --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-gmp --enable-gnutls --enable-libmp3lame --enable-libass --enable-iconv --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxml2 --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libshine --enable-libspeex --enable-libwavpack --enable-libkvazaar --enable-libx264 --enable-gpl --enable-libxvid --enable-gpl --enable-libx265 --enable-gpl --enable-libvidstab --enable-gpl --enable-libilbc --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libaom --enable-libtwolame --disable-sdl2 --enable-zlib --enable-audiotoolbox --enable-coreimage --enable-bzlib --enable-videotoolbox --enable-avfoundation

index.js:70   libavutil      56. 25.100 / 56. 25.100

index.js:70   libavcodec     58. 42.104 / 58. 42.104

index.js:70   libavformat    58. 25.100 / 58. 25.100

index.js:70   libavdevice    58.  6.101 / 58.  6.101

index.js:70   libavfilter     7. 46.101 /  7. 46.101

index.js:70   libswscale      5.  4.100 /  5.  4.100

index.js:70   libswresample   3.  4.100 /  3.  4.100

index.js:70 Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/hamza/Library/Developer/CoreSimulator/Devices/FE0CB277-54AD-413B-9C0F-D50427ED8C56/data/Containers/Data/Application/C2088162-769D-421E-B374-F51116FCF155/Library/Caches/test1.mp4':

index.js:70   Metadata:

index.js:70     major_brand     : 
index.js:70 mp42
index.js:70 

index.js:70     minor_version   : 
index.js:70 0
index.js:70 

index.js:70     compatible_brands: 
index.js:70 mp42mp41
index.js:70 

index.js:70     creation_time   : 
index.js:70 2018-07-06T04:27:13.000000Z
index.js:70 

index.js:70   Duration: 
index.js:70 00:00:13.40
index.js:70 , start: 
index.js:70 0.000000
index.js:70 , bitrate: 
index.js:70 6997 kb/s
index.js:70 

index.js:70     Stream #0:0
index.js:70 (eng)
index.js:70 : Video: h264 (avc1 / 0x31637661), yuv420p, 720x1280 [SAR 1:1 DAR 9:16], 6691 kb/s
index.js:70 , 
index.js:70 23.98 fps, 
index.js:70 23.98 tbr, 
index.js:70 24k tbn, 
index.js:70 47.95 tbc
index.js:70  (default)
index.js:70 

index.js:70     Metadata:

index.js:70       creation_time   : 
index.js:70 2018-07-06T04:27:13.000000Z
index.js:70 

index.js:70       handler_name    : 
index.js:70 Mainconcept Video Media Handler
index.js:70 

index.js:70       encoder         : 
index.js:70 AVC Coding
index.js:70 

index.js:70     Stream #0:1
index.js:70 (eng)
index.js:70 : Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s
index.js:70  (default)
index.js:70 

index.js:70     Metadata:

index.js:70       creation_time   : 
index.js:70 2018-07-06T04:27:13.000000Z
index.js:70 

index.js:70       handler_name    : 
index.js:70 #Mainconcept MP4 Sound Media Handler
index.js:70 

index.js:70 Stream mapping:

index.js:70   Stream #0:0 (h264) -> thumbnail
index.js:70 

index.js:70   tile
index.js:70  -> Stream #0:0 (mjpeg)

index.js:70 Press [q] to stop, [?] for help

index.js:70 deprecated pixel format used, make sure you did set range correctly

index.js:70 Output #0, image2, to 'sample.jpg':

index.js:70   Metadata:

index.js:70     major_brand     : 
index.js:70 mp42
index.js:70 

index.js:70     minor_version   : 
index.js:70 0
index.js:70 

index.js:70     compatible_brands: 
index.js:70 mp42mp41
index.js:70 

index.js:70     encoder         : 
index.js:70 Lavf58.25.100
index.js:70 

index.js:70     Stream #0:0
index.js:70 : Video: mjpeg, yuvj444p(pc), 340x120 [SAR 135:136 DAR 45:16], q=2-31, 200 kb/s
index.js:70 , 
index.js:70 4.80 fps, 
index.js:70 4.80 tbn, 
index.js:70 4.80 tbc
index.js:70  (default)
index.js:70 

index.js:70     Metadata:

index.js:70       encoder         : 
index.js:70 Lavc58.42.104 mjpeg
index.js:70 

index.js:70     Side data:

index.js:70       
index.js:70 cpb: 
index.js:70 bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
index.js:70 

index.js:70 frame id #2 (pts_time=0.083417) selected from a set of 5 images

index.js:70 frame id #2 (pts_time=0.291958) selected from a set of 5 images

index.js:70 frame id #2 (pts_time=0.500500) selected from a set of 5 images

index.js:70 frame id #2 (pts_time=0.709042) selected from a set of 5 images

index.js:70 frame id #2 (pts_time=0.917583) selected from a set of 5 images

index.js:70 Could not open file : sample.jpg

index.js:70 av_interleaved_write_frame(): Input/output error

index.js:70 
index.js:70 frame=    1 fps=0.0 q=4.2 Lsize=N/A time=00:00:00.20 bitrate=N/A speed=0.536x    

index.js:70 video:12kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 
index.js:70 unknown
index.js:70 

index.js:70 Conversion failed!

Here is FFmpeg 
RNFFmpeg.execute(`-y -i ${file} -vframes 1 -filter_complex thumbnail=5,scale=-1:120,tile=5x1 sample.jpg`)

Can you please help me?

**Comment by hamzashahbaz** [comment]
This what I am using for the image path
let outputVideoPath = `${RNFS.CachesDirectoryPath}/${fileName}_preview.jpg`;
 RNFFmpeg.execute(`-y -i ${file} -frames 1 -q:v 1 -vf thumbnail=5,scale=-1:120,tile=5x1 ${outputVideoPath}`)

**Comment by tanersener** [comment]
In your first post image path was `sample.jpg` and `ffmpeg` was failing with `Could not open file : sample.jpg` error.

What is the output when you use `${RNFS.CachesDirectoryPath}/${fileName}_preview.jpg` for image path?

**Comment by hamzashahbaz** [comment]
I am getting the same error.
```
Running FFmpeg command: -y -i /Users/hamza/Library/Developer/CoreSimulator/Devices/FE0CB277-54AD-413B-9C0F-D50427ED8C56/data/Containers/Data/Application/C0AA1123-F5C9-4E29-A072-ED2B2F89AAB1/Library/Caches/test1.mp4 -frames 1 -q:v 1 -vf thumbnail=5,scale=-1:120,tile=5x1 /Users/hamza/Library/Developer/CoreSimulator/Devices/FE0CB277-54AD-413B-9C0F-D50427ED8C56/data/Containers/Data/Application/C0AA1123-F5C9-4E29-A072-ED2B2F89AAB1/Library/Caches//Users/hamza/Library/Developer/CoreSimulator/Devices/FE0CB277-54AD-413B-9C0F-D50427ED8C56/data/Containers/Data/Application/C0AA1123-F5C9-4E29-A072-ED2B2F89AAB1/Library/Caches/test1_preview.jpg with delimiter  .

RCTLog.js:47 FFmpeg exited with rc: 1

index.js:25 0
index.js:70 ffmpeg version v4.2-dev-480
index.js:70  Copyright (c) 2000-2018 the FFmpeg developers
index.js:70 

index.js:70   built with Apple LLVM version 7.3.0 (clang-703.0.31)

index.js:70   configuration: --sysroot=/Applications/Xcode-v7.3.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk --prefix=/Users/taner/Projects/mobile-ffmpeg/prebuilt/ios-x86_64-ios-darwin/ffmpeg --enable-version3 --arch=x86_64 --cpu=x86_64 --target-os=darwin --ar=/Applications/Xcode-v7.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar --cc=/Applications/Xcode-v7.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang --cxx=/Applications/Xcode-v7.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ --as='/Applications/Xcode-v7.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -target x86_64-ios-darwin -march=x86-64 -msse4.2 -mpopcnt -m64 -mtune=intel -DMOBILE_FFMPEG_X86_64 -Wno-unused-function -Wno-deprecated-declarations -fstrict-aliasing -DIOS -DMOBILE_FFMPEG_LTS -isysroot /Applications/Xcode-v7.3.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -O2 -mios-simulator-version-min=9.3 -I/Applications/Xcode-v7.3.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/usr/include' --ranlib=/Applications/Xcode-v7.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib --strip=/Applications/Xcode-v7.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip --disable-neon --enable-cross-compile --enable-pic --enable-asm --enable-inline-asm --enable-optimizations --enable-swscale --enable-static --disable-shared --enable-small --disable-v4l2-m2m --disable-outdev=v4l2 --disable-outdev=fbdev --disable-indev=v4l2 --disable-indev=fbdev --disable-openssl --disable-xmm-clobber-test --disable-debug --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --disable-appkit --disable-alsa --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-gmp --enable-gnutls --enable-libmp3lame --enable-libass --enable-iconv --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxml2 --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libshine --enable-libspeex --enable-libwavpack --enable-libkvazaar --enable-libx264 --enable-gpl --enable-libxvid --enable-gpl --enable-libx265 --enable-gpl --enable-libvidstab --enable-gpl --enable-libilbc --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libaom --enable-libtwolame --disable-sdl2 --enable-zlib --enable-audiotoolbox --enable-coreimage --enable-bzlib --enable-videotoolbox --enable-avfoundation

index.js:70   libavutil      56. 25.100 / 56. 25.100

index.js:70   libavcodec     58. 42.104 / 58. 42.104

index.js:70   libavformat    58. 25.100 / 58. 25.100

index.js:70   libavdevice    58.  6.101 / 58.  6.101

index.js:70   libavfilter     7. 46.101 /  7. 46.101

index.js:70   libswscale      5.  4.100 /  5.  4.100

index.js:70   libswresample   3.  4.100 /  3.  4.100

index.js:70 Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/hamza/Library/Developer/CoreSimulator/Devices/FE0CB277-54AD-413B-9C0F-D50427ED8C56/data/Containers/Data/Application/C0AA1123-F5C9-4E29-A072-ED2B2F89AAB1/Library/Caches/test1.mp4':

index.js:70   Metadata:

index.js:70     major_brand     : 
index.js:70 mp42
index.js:70 

index.js:70     minor_version   : 
index.js:70 0
index.js:70 

index.js:70     compatible_brands: 
index.js:70 mp42mp41
index.js:70 

index.js:70     creation_time   : 
index.js:70 2018-07-06T04:27:13.000000Z
index.js:70 

index.js:70   Duration: 
index.js:70 00:00:13.40
index.js:70 , start: 
index.js:70 0.000000
index.js:70 , bitrate: 
index.js:70 6997 kb/s
index.js:70 

index.js:70     Stream #0:0
index.js:70 (eng)
index.js:70 : Video: h264 (avc1 / 0x31637661), yuv420p, 720x1280 [SAR 1:1 DAR 9:16], 6691 kb/s
index.js:70 , 
index.js:70 23.98 fps, 
index.js:70 23.98 tbr, 
index.js:70 24k tbn, 
index.js:70 47.95 tbc
index.js:70  (default)
index.js:70 

index.js:70     Metadata:

index.js:70       creation_time   : 
index.js:70 2018-07-06T04:27:13.000000Z
index.js:70 

index.js:70       handler_name    : 
index.js:70 Mainconcept Video Media Handler
index.js:70 

index.js:70       encoder         : 
index.js:70 AVC Coding
index.js:70 

index.js:70     Stream #0:1
index.js:70 (eng)
index.js:70 : Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s
index.js:70  (default)
index.js:70 

index.js:70     Metadata:

index.js:70       creation_time   : 
index.js:70 2018-07-06T04:27:13.000000Z
index.js:70 

index.js:70       handler_name    : 
index.js:70 #Mainconcept MP4 Sound Media Handler
index.js:70 

index.js:70 Stream mapping:

index.js:70   Stream #0:0 -> #0:0
index.js:70  (h264 (native) -> mjpeg (native))
index.js:70 

index.js:70 Press [q] to stop, [?] for help

index.js:70 frame=    0 fps=0.0 q=0.0 size=N/A time=-577014:32:22.77 bitrate=N/A speed=N/A    
index.js:70 deprecated pixel format used, make sure you did set range correctly

index.js:70 Output #0, image2, to '/Users/hamza/Library/Developer/CoreSimulator/Devices/FE0CB277-54AD-413B-9C0F-D50427ED8C56/data/Containers/Data/Application/C0AA1123-F5C9-4E29-A072-ED2B2F89AAB1/Library/Caches//Users/hamza/Library/Developer/CoreSimulator/Devices/FE0CB277-54AD-413B-9C0F-D50427ED8C56/data/Containers/Data/Application/C0AA1123-F5C9-4E29-A072-ED2B2F89AAB1/Library/Caches/test1_preview.jpg':

index.js:70   Metadata:

index.js:70     major_brand     : 
index.js:70 mp42
index.js:70 

index.js:70     minor_version   : 
index.js:70 0
index.js:70 

index.js:70     compatible_brands: 
index.js:70 mp42mp41
index.js:70 

index.js:70     encoder         : 
index.js:70 Lavf58.25.100
index.js:70 

index.js:70     Stream #0:0
index.js:70 (eng)
index.js:70 : Video: mjpeg, yuvj444p(pc), 340x120 [SAR 135:136 DAR 45:16], q=2-31, 200 kb/s
index.js:70 , 
index.js:70 4.80 fps, 
index.js:70 4.80 tbn, 
index.js:70 4.80 tbc
index.js:70  (default)
index.js:70 

index.js:70     Metadata:

index.js:70       creation_time   : 
index.js:70 2018-07-06T04:27:13.000000Z
index.js:70 

index.js:70       handler_name    : 
index.js:70 Mainconcept Video Media Handler
index.js:70 

index.js:70       encoder         : 
index.js:70 Lavc58.42.104 mjpeg
index.js:70 

index.js:70     Side data:

index.js:70       
index.js:70 cpb: 
index.js:70 bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
index.js:70 

index.js:70 frame id #2 (pts_time=0.083417) selected from a set of 5 images

index.js:70 frame id #2 (pts_time=0.291958) selected from a set of 5 images

index.js:70 frame id #2 (pts_time=0.500500) selected from a set of 5 images

index.js:70 frame id #2 (pts_time=0.709042) selected from a set of 5 images

index.js:70 frame id #2 (pts_time=0.917583) selected from a set of 5 images

index.js:70 Could not open file : /Users/hamza/Library/Developer/CoreSimulator/Devices/FE0CB277-54AD-413B-9C0F-D50427ED8C56/data/Containers/Data/Application/C0AA1123-F5C9-4E29-A072-ED2B2F89AAB1/Library/Caches//Users/hamza/Library/Developer/CoreSimulator/Devices/FE0CB277-54AD-413B-9C0F-D50427ED8C56/data/Containers/Data/Application/C0AA1123-F5C9-4E29-A072-ED2B2F89AAB1/Library/Caches/test1_preview.jpg

index.js:70 av_interleaved_write_frame(): Input/output error

index.js:70 
index.js:70 frame=    1 fps=0.0 q=1.0 Lsize=N/A time=00:00:00.20 bitrate=N/A speed=0.546x    

index.js:70 video:20kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 
index.js:70 unknown
index.js:70 

index.js:70 Conversion failed!
```

**Comment by tanersener** [comment]
Can you test running your command inside `default` [test-application](https://github.com/tanersener/react-native-ffmpeg-test)?

**Comment by hamzashahbaz** [comment]
I did some configurations and It worked like a charm! Thank you!

**Comment by Neha0595** [comment]
@hamzashahbaz I've run into the same issue. Could you please tell us what configurations did you change?

**Comment by Neha0595** [comment]
@hamzashahbaz I'm also facing the same problem, could you please post here what configuration you done in that.

**Comment by iamadityaaz** [comment]
@Neha0595  Did you solved it ?

**Comment by gustavolsilvano** [comment]
@Neha0595 @iamadityaaz Any solution?
