### ISSUE TITLE
Help to implement librsvg codec

### ISSUE THREAD

**Issue by webmasterdragon** [tanersener/react-native-ffmpeg#6]
Hi,
I want to know if this one is support librsvg codec.
`Codec 'librsvg' is not recognized by FFmpeg.`
I have got this error now.
Thanks.

**Comment by tanersener** [comment]
Hi,

Unfortunately `librsvg` is not supported yet. You can submit your request to support `librsvg` [here](https://github.com/tanersener/react-native-ffmpeg/issues/7) but it is not possible to say that `librsvg` support will be certainly added.

**Comment by tanersener** [comment]
Hi @webmasterdragon. I just checked [dependencies](https://github.com/GNOME/librsvg/blob/master/COMPILING.md#installing-dependencies-for-building) required to build `librsvg`. There are too many mandatory dependencies; this means too much effort to support `librsvg`. So, in short term I'm not planning to add support for `librsvg`.
