### ISSUE TITLE
IOS Release build failed -  Symbol(s) not found for architecture armv7

### ISSUE THREAD

**Issue by TeslaAdis** [tanersener/react-native-ffmpeg#64]
**Description**
The build works just fine in debug in both Android and IOS. Release for Android works fine as well. But running IOS release through XCode results in errors you can see bellow in logs.
Am I missing something (I did run react-native link react-native-ffmpeg for android side, hope this did not affect IOS)

**Expected behavior**
Shie, it should build

**Current behavior**
After following these steps build fails
Fresh clone app
```
npm install // No errors
cd ios/pod update/install // No errors
cd ../react-native run-ios // No errors runs in simulator without any problems

Bundle upp app
react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios

Run vihor.xworkspace -  open XCode
In AppDelegate.m change Replace line 
jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
with
jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];

Navigate  to product/scheme/edit scheme
set Build Configuration to Release

Run Product/Clean = Success
Run Product/Build (selected device iPhone8 Plus) = Fail
Run Product/Build (selected device Generic iOS Device) = Fail

(see image below)
iPhone8Plus = Symbol(s) not found for architecture i386 (I understand this  is since iPhone8 does not support those types of processors)
Generic iOS Device = Symbol(s) not found for architecture amv7
Error Linker command failed with exit code 1 
```
[Build Error iPhone8](https://imgur.com/a/HRjMevH) 
[Build Error Generic](https://imgur.com/a/9FOZg2c)

Used [package.json](https://pastebin.com/KHH0090G)
Used [Podfile](https://pastebin.com/a3uMSVaZ)

**Logs**
Will paste if more detailed log is required

**Environment**
Xcode Version 9.2 (9C40b)
react-native-cli 2.0.1
react-native 0.57.1

**Comment by tanersener** [comment]
You are depending a `Main Release`. Unfortunately [Main Releases](https://github.com/tanersener/react-native-ffmpeg#51-main-release-vs-lts-release) do not support 32-bit architectures. 

If you want to use `Main Release` features you have to disable 32-bit targets, `armv7` and `i386` are both 32-bit targets. 

If you don't need `Main Release` features, then you can update your `react-native-ffmpeg` dependency to depend an `LTS` version which supports 32-bit architectures.

**Comment by TeslaAdis** [comment]
Running without armv7 and errors for react-native-ffmpeg are gone. But what would you say, should I update towards support for LTS or not? 

If I would move towards LTS release, what are the steps needed for this? Don't really see anywhere in the documentation about this.

Thank you for fast response

**Comment by tanersener** [comment]
[2.4 LTS Release](https://github.com/tanersener/react-native-ffmpeg#24-lts-release) section in README includes instructions to install the `LTS` variant.

**Comment by TeslaAdis** [comment]
Everything updated and working.  

Thank you for your time
