### ISSUE TITLE
Could not invoke RNFFmpegModule.enableLogEvents

### ISSUE THREAD

**Issue by ashwinik-mdn** [tanersener/react-native-ffmpeg#67]
**Description**
I have received Could not invoke RNFFmpegModule.enableLogEvents when I use  import  { RNFFmpeg } from 'react-native-ffmpeg' on Android

**Logs**
I ReactNativeJS: Loading react-native-ffmpeg.
I mobile-ffmpeg: Loading mobile-ffmpeg.
E unknown:ReactNative: Exception in native call
E unknown:ReactNative: java.lang.RuntimeException: Could not invoke RNFFmpegModule.enableLogEvents
E unknown:ReactNative: at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
E unknown:ReactNative: at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
E unknown:ReactNative: at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E unknown:ReactNative: at android.os.Handler.handleCallback(Handler.java:836)
E unknown:ReactNative: at android.os.Handler.dispatchMessage(Handler.java:103)
E unknown:ReactNative: at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
E unknown:ReactNative: at android.os.Looper.loop(Looper.java:203)
E unknown:ReactNative: at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
E unknown:ReactNative: at java.lang.Thread.run(Thread.java:761)
E unknown:ReactNative: Caused by: java.lang.reflect.InvocationTargetException
E unknown:ReactNative: at java.lang.reflect.Method.invoke(Native Method)
E unknown:ReactNative: at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
E unknown:ReactNative: ... 8 more
E unknown:ReactNative: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_sscanf" referenced by "/data/app/com.android.androidviewer-1/lib/arm/libavfilter.so"...
E unknown:ReactNative: at java.lang.Runtime.loadLibrary0(Runtime.java:977)
E unknown:ReactNative: at java.lang.System.loadLibrary(System.java:1530)
E unknown:ReactNative: at com.arthenica.mobileffmpeg.Config.(Config.java:116)
E unknown:ReactNative: at com.arthenica.mobileffmpeg.Config.enableLogCallback(Config.java:190)
E unknown:ReactNative: at com.arthenica.reactnative.RNFFmpegModule.enableLogEvents(RNFFmpegModule.java:160)
E unknown:ReactNative: ... 10 more

**Environment**
 - React Native Environment Info
    "react": "16.8.6",
    "react-native": "0.59.8",
    "react-native-ffmpeg": "0.3.2",

**Android build gradle**
        buildToolsVersion = "28.0.3"
        minSdkVersion = 24
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"

**Comment by tanersener** [comment]
Did you try running [test applications](https://github.com/tanersener/react-native-ffmpeg-test)?

If you can run them successfully, this shows that something is wrong in your build configuration (package.json, gradle files, etc.). You can fix your errors by comparing your configuration with `test-application` configuration.

**Comment by anmol-appzoy** [comment]
@ashwinik-mdn did you get any solution for this.

**Comment by ashwinik-mdn** [comment]
It was causing issue for me due to one more jni interface with compiled ffmpeg sources. When I used this library it was looking for some .so files(libavfilter.so) in the first ffmpeg sources. When I added those .so files to that sources issue got resloved.

**Comment by shababcreative** [comment]
@ashwinik-mdn can you explain more? I can't find any .so files, and where to add it?

**Comment by maomeiqi** [comment]
> @ ashwinik-mdn您能解释更多吗？我找不到任何.so文件，并将其添加到哪里？

Did you solve it?

**Comment by huanvu** [comment]
@tanersener Seeing this java error also but with a different failure in the logs -

`E/art ( 2793): dlopen("/data/app/io.evalabs.hotlap-1/lib/x86/libmobileffmpeg.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "av_frame_copy" referenced by "libavfilter.so"...`

Whats weird is according to our crash reporter, this is happening on a Pixel 2 (API 22) which shouldn't be x86. I'm also seeing this same issue happen on a samsung SM-N950N (API 22)

Could it be an issue with older versions of android? I use a Pixel 2 XL myself and I'm not seeing this issue but I'm on API 29 though.

I'm using the min-lts package.

**Comment by tanersener** [comment]
@huanvu I think those two API 22 devices are Simulators not real devices. `Pixel 2` was released with API 26 and and `SM-N950N` was released with API 25. So both of them never had API Level 22 officially. Also they don't have an `x86` ABI.

Did you test running your application on one of those Simulators?

**Comment by huanvu** [comment]
@tanersener Ah you are probably right. This would make sense.

Thank you for the library and the support!

**Comment by alexanderwallin** [comment]
I'm investigating a swap from `react-native-video-processing` to `react-native-ffmpeg`, and I had this issue while the two libs where both installed. After uninstalling the former lib, things worked.

**Comment by Abdullah1428** [comment]
I am still facing this issue even after applying the fix mentioned in the testing-application.

In my project,  since I installed react-native-video-processing I am getting this error, before that there was no error and everything was working fine. Any solution to this? or do I have to remove react-native-video-processing from my project?
