### ISSUE TITLE
ffmpeg comand to extract frames from video crash in IOS

### ISSUE THREAD

**Issue by Neha0595** [tanersener/react-native-ffmpeg#73]
**Description**
In react native IOS ffmpeg command to extract frames from video doesn't work in IOS , while it works perfectly on Android side.
ffmpeg command which I Use is: 

`RNFFmpeg.executeWithArguments([
    '-i',
    mediaUriAbsolutePath,
    '-vf',
    `fps=1/${timing}`,
    output,
    ]).then(this.updateFrames(coversDirectory, index));`

where,
 1. timing = videoLength / 10; // Divide by 10 to extract 10 frames
 2. mediaUriAbsolutePath: 
`/var/mobile/Containers/Data/Application/14660700-6A52-416F-9EAC-B1FEF01EAEBC/Library/Caches/Camera/942E877E-0D2F-4C68-84D1-58837BBD7BE8.mov`

3. output: `${RNFS.CachesDirectoryPath}/Foxy/VideoProcessing/thumbnails%04d.jpg`

**Current behavior**
when I run this command it crash in IOS.While other ffmpeg command works correctly: Other ffmpeg which I Use is: trim video, speed up video, split video, extract cover Image from video.

**Comment by tanersener** [comment]
Tested your command on [default test application](https://github.com/tanersener/react-native-ffmpeg-test/tree/master/default) but it worked successfully.

Can you please share console logs or screenshots of your crash?

**Comment by Neha0595** [comment]
It doesn't print any log on console, application just crash after this command in iPhone not in android, In android it works successfully.

**Comment by tanersener** [comment]
OK, I understand that. But your command works for me on my test environment. I need to see something to help you on this. Can't you provide any screenshots of the crash?

**Comment by stoner2497** [comment]
![image](https://user-images.githubusercontent.com/26773280/106649764-078cfc00-65b8-11eb-9835-b5c4825bc620.png)
 this is what im getting while running the same command as @Neha0595 Please help me with this already wasted one day on this

**Comment by stoner2497** [comment]
@tanersener

**Comment by stoner2497** [comment]
export const thumbnailGenration = (param) => {
  let output = `${RNFetchBlob.CachesDirectoryPath}/Foxy/VideoProcessing/thumbnails%04d.jpg`;
  let timing = param.endTime / 10;
  return `-i ${param.url} -vf fps=1/${timing} ${output}`;
};

**Comment by gustavolsilvano** [comment]
@stoner2497 did you got any solution for this?
