### ISSUE TITLE
Can we use mp3 with react-native-ffmpeg?

### ISSUE THREAD

**Issue by kouohhashi** [tanersener/react-native-ffmpeg#74]
**Description**
Can we handle mp3 file?
When i try to use **_silencedetect_**, it said **_"Automatic encoder selection failed for output stream #1:0. Default encoder for format mp3 (codec mp3) is probably disabled. Please choose an encoder manually."_**

How can I choose encoder manually?

Here's my command
```
RNFFmpeg.execute('-i <audio_path1> -af silencedetect=noise=-30dB:d=0.5 <audio_path>', ' ')
```

Thanks in advance

**My environment**
react-native-ffmpeg: 0.3.2
react-native: 0.59
OS: Android

**Comment by tanersener** [comment]
`mp3` encoding capability is provided by `lame` and `shine` external libraries. You need to install a package which includes one of these libraries. Please refer to [Features](https://github.com/tanersener/react-native-ffmpeg#1-features) section where all packages and external libraries enabled inside these packages are listed.

**Comment by kouohhashi** [comment]
@tanersener 
Thank you so much!

How can I install external library?
Could you give me some good web article?

My question could be silly because i'm newbie for audio processing...

Thanks in advance.

**Comment by tanersener** [comment]
There is a misunderstanding here. You don't need to install an external library, you need install another `react-native-ffmpeg` package. That package already includes external libraries inside.

`react-native-ffmpeg` has 8 different packages. Your dependency `react-native-ffmpeg: 0.3.2` installs the default one, which is the same as `https` package. Please install one of `audio`, `full` or `full-gpl` packages to encode `mp3`. [Packages](https://github.com/tanersener/react-native-ffmpeg#23-packages) section includes instructions to install a package.

**Comment by kouohhashi** [comment]
@tanersener 
It works after specifying the package name as **_audio_**.
Thank you so much.
