### ISSUE TITLE
[Android] build fail : min SDK

### ISSUE THREAD

**Issue by monkibraum** [tanersener/react-native-ffmpeg#76]
**Description**

I installed this library in a newly created project  (RN version @59) and linked it with react-native link.
And react-native run-android fails.
 

**Expected behavior**
What you expected to happen.

successful build

**Current behavior**
build failure

**Screenshots**

![스크린샷 2019-06-17 오후 9 15 14](https://user-images.githubusercontent.com/36508569/59603711-1e61af00-9145-11e9-8474-9c61e200eca6.png)

**Logs**
Post logs here or paste them to [Ghostbin](https://ghostbin.com) and insert the link here.

```
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [:react-native-ffmpeg] /Users/p/Desktop/music_talk/node_modules/react-native-ffmpeg/android/build/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
        Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 21,
                or use tools:overrideLibrary="com.arthenica.reactnative" to force usage (may lead to runtime failures)

```

**Environment**
 - React Native Environment Info

 "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-ffmpeg": "^0.3.2"
  },
  "devDependencies": {
    "@babel/core": "7.4.5",
    "@babel/runtime": "7.4.5",
    "babel-jest": "24.8.0",
    "jest": "24.8.0",
    "metro-react-native-babel-preset": "0.54.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }

**Other**

**Comment by tanersener** [comment]
Your logs explain everything. Your project has minSDK=16 but `react-native-ffmpeg` needs at least minSDK=21. Did you try increasing minSDK in your project?

**Comment by monkibraum** [comment]
@tanersener Yes, actually I had to increase to 24 and add additional property in AndroidManifest.xml as the log message below suggested. Now the build success.

```
> Task :app:processDebugManifest FAILED
/Users/p/Desktop/music_talk/android/app/src/debug/AndroidManifest.xml:11:7-34 Error:
        Attribute application@allowBackup value=(false) from AndroidManifest.xml:11:7-34
        is also present at [com.arthenica:mobile-ffmpeg-https:4.2.1] AndroidManifest.xml:12:9-35 value=(true).
        Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:7:5-117 to override.
```

`<manifest ... xmlns:tools="http://schemas.android.com/tools" >`
`<application ... tools:replace="android:allowBackup"> `

**Comment by tanersener** [comment]
OK, great. 

I want to remind that `LTS` packages of `react-native-ffmpeg` support API level 21. If you need to lower API level, you can install one of these packages.

**Comment by wcandillon** [comment]
@tanersener Thank you for building such a great package. Ran a test for it on iOS and it's awesome.

I need support for the API level 21. How can I install `LTS` packages of `react-native-ffmpeg`?

**Comment by tanersener** [comment]
Hi @wcandillon,  you can install `LTS` packages using instruction in [2.4 LTS Release](https://github.com/tanersener/react-native-ffmpeg#24-lts-release) and [2.3 Packages](https://github.com/tanersener/react-native-ffmpeg#23-packages).

**Comment by wcandillon** [comment]
@tanersener Thank you for your support, I was able to make it work on Android using

```
ext {
    reactNativeFFmpegPackage = "https-lts"
}
```

**Comment by tanersener** [comment]
@wcandillon Great 👍
