### ISSUE TITLE
Can I add watermark using this library in video?

### ISSUE THREAD

**Issue by sharadkatre19** [tanersener/react-native-ffmpeg#78]
**Expected behavior**
Want watermark in the video.

**Current behavior**
Now I am able to record and select a video, But I want to add watermark in the video while saving or else while recording...

**Environment**
 - React Native

**Comment by tanersener** [comment]
This library can do everything `ffmpeg` is capable of doing.

**Comment by sharadkatre19** [comment]
Can you share an example for react-native video watermark?

Thanks.

**Comment by tanersener** [comment]
I don't have an example for that. Why don't you search for `how to add watermark in ffmpeg` and apply the same command in `react-native-ffmpeg`?

**Comment by sharadkatre19** [comment]
I have tried for adding react-native-ffmpeg but it giving me error.

> info error: /Users/iosdeveloper/Projects/ReactNative/VideoWatermark/node_modules/react-native-ffmpeg/ios/Pods/Target Support Files/Pods-ReactNativeFFmpeg/Pods-ReactNativeFFmpeg.debug.xcconfig: unable to open file (in target "ReactNativeFFmpeg" in project "ReactNativeFFmpeg") (in target 'ReactNativeFFmpeg')

>

**Comment by tanersener** [comment]
[Section 2.2](https://github.com/tanersener/react-native-ffmpeg#22-ios) section describes the steps to install this library for IOS. Did you follow the steps defined there? Please remember that `react-native link` shouldn't be used for IOS.

If you have an error about `react-native-ffmpeg`, first refer to [Tips](https://github.com/tanersener/react-native-ffmpeg#6-tips) section and check if your error is listed there. If it is not there then search your error under the Issues and see whether a solution is posted there or not. If you can't find it anywhere then create an issue and fill issue template fields, so I can help you about the fix.

**Comment by HemanthSurimani** [comment]
RNFFmpeg.execute('-i '+ <Input mp4 file>+' -i '+<Inputwatermark image>+' -filter_complex "overlay=10:10" out.mp4').then(result => console.log("FFmpeg process exited with rc " + result));


after adding watermark iam unable find my Output file path 

getting console response::

index.js:70 
index.js:70   libavutil      56. 30.100 / 56. 30.100

3index.js:70 
index.js:70   libavcodec     58. 53.101 / 58. 53.101

3index.js:70 
index.js:70   libavformat    58. 28.101 / 58. 28.101

3index.js:70 
index.js:70   libavdevice    58.  7.100 / 58.  7.100

3index.js:70 
index.js:70   libavfilter     7. 55.100 /  7. 55.100

3index.js:70 
index.js:70   libswscale      5.  4.101 /  5.  4.101

3index.js:70 
index.js:70   libswresample   3.  4.100 /  3.  4.100

3index.js:70 
index.js:70 Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:///storage/emulated/0/DCIM/Camera/VID_20190626_151201.mp4':

3index.js:70 
index.js:70   Metadata:

3index.js:70 
index.js:70     major_brand     : 
3index.js:70 
index.js:70 mp42
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     minor_version   : 
3index.js:70 
index.js:70 0
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     compatible_brands: 
3index.js:70 
index.js:70 isommp42
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     creation_time   : 
3index.js:70 
index.js:70 2019-06-26T09:42:04.000000Z
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     location        : 
3index.js:70 
index.js:70 +37.4220-122.0839/
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     location-eng    : 
3index.js:70 
index.js:70 +37.4220-122.0839/
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     com.android.version: 
3index.js:70 
index.js:70 8.1.0
3index.js:70 
index.js:70 

3index.js:70 
index.js:70   Duration: 
3index.js:70 
index.js:70 00:00:01.74
3index.js:70 
index.js:70 , start: 
3index.js:70 
index.js:70 0.000000
3index.js:70 
index.js:70 , bitrate: 
3index.js:70 
index.js:70 3180 kb/s
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     Stream #0:0
3index.js:70 
index.js:70 (eng)
3index.js:70 
index.js:70 : Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720, 1306 kb/s
3index.js:70 
index.js:70 , SAR 1:1 DAR 16:9
3index.js:70 
index.js:70 , 
3index.js:70 
index.js:70 9.19 fps, 
3index.js:70 
index.js:70 90k tbr, 
3index.js:70 
index.js:70 90k tbn, 
3index.js:70 
index.js:70 180k tbc
3index.js:70 
index.js:70  (default)
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     Metadata:

3index.js:70 
index.js:70       rotate          : 
3index.js:70 
index.js:70 90
3index.js:70 
index.js:70 

3index.js:70 
index.js:70       creation_time   : 
3index.js:70 
index.js:70 2019-06-26T09:42:04.000000Z
3index.js:70 
index.js:70 

3index.js:70 
index.js:70       handler_name    : 
3index.js:70 
index.js:70 VideoHandle
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     Side data:

3index.js:70 
index.js:70       
3index.js:70 
index.js:70 displaymatrix: rotation of -90.00 degrees
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     Stream #0:1
3index.js:70 
index.js:70 (eng)
3index.js:70 
index.js:70 : Audio: amr_nb (samr / 0x726D6173), 8000 Hz, mono, flt, 12 kb/s
3index.js:70 
index.js:70  (default)
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     Metadata:

3index.js:70 
index.js:70       creation_time   : 
3index.js:70 
index.js:70 2019-06-26T09:42:04.000000Z
3index.js:70 
index.js:70 

3index.js:70 
index.js:70       handler_name    : 
3index.js:70 
index.js:70 SoundHandle
3index.js:70 
index.js:70 

3index.js:70 
index.js:70 Input #1, image2, from 'file:///storage/emulated/0/Android/data/com.vikipedia/files/Pictures/image-b2ea7b60-cf3d-4ced-aa14-55665b9da40d.jpg':

3index.js:70 
index.js:70   Duration: 
3index.js:70 
MediadataComponent.js:122 FFmpeg process exited with rc undefined
index.js:70 00:00:00.04
3index.js:70 
index.js:70 , start: 
3index.js:70 
index.js:70 0.000000
3index.js:70 
index.js:70 , bitrate: 
3index.js:70 
index.js:70 20513 kb/s
3index.js:70 
index.js:70 

3index.js:70 
index.js:70     Stream #1:0
3index.js:70 
index.js:70 : Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 375x500 [SAR 1:1 DAR 3:4]
3index.js:70 
index.js:70 , 
3index.js:70 
index.js:70 25 tbr, 
3index.js:70 
index.js:70 25 tbn, 
3index.js:70 
index.js:70 25 tbc
3index.js:70 
index.js:70 

3index.js:70 
index.js:70 out.mp4: Read-only file system

4index.js:70

**Comment by tanersener** [comment]
@HemanthSurimani 

1. Please, try to understand what your logs say
```
index.js:70 out.mp4: Read-only file system
```

2. Please, read [Tips](https://github.com/tanersener/react-native-ffmpeg#6-tips)
