### ISSUE TITLE
No such filter "zoompan"

### ISSUE THREAD

**Issue by yewness** [tanersener/react-native-ffmpeg#80]
**Description**
I'm trying to generate a picture that has Ken Burns' effect (zoompan) for 5 seconds.

My code is as below:
```
  addZoomPan() {
    let picturePath = `${fileDirectoryPath}/baby.jpg`;
    let outputPath = `${fileDirectoryPath}/azoom.mp4`;
    RNFFmpeg.execute(
      `-i ${picturePath} -vf "zoompan=d=25*4:s=1920:1080" -pix_fmt yuv420p -c:v libx264 ${outputPath}`
    );
  }
```

**Expected behavior**
Able to generate 5 seconds video in the phone. It works using Macbook Air.

**Current behavior**
No such filter 'zoompan'. The video couldn't be processed.

**Screenshots**

![Screenshot 2019-07-01 at 4 38 12 PM](https://user-images.githubusercontent.com/14829481/60422570-dd769980-9c1e-11e9-84e0-3dc2a5311eee.png)
_______________________________
Could anyone help on this?

**Comment by tanersener** [comment]
Can you try without double quotes? Please see [Tips](https://github.com/tanersener/react-native-ffmpeg#6-tips).

**Comment by yewness** [comment]
Thanks, it's resolved. Silly mistake!
