### ISSUE TITLE
ld: library not found for -lReactNativeFFmpeg

### ISSUE THREAD

**Issue by kouohhashi** [tanersener/react-native-ffmpeg#81]
Hi,
When I try to build a binary on Xcode, Xcode show an error which says **_ld: library not found for -lReactNativeFFmpeg_**.

I have no clue about that error. Actually I can build Android version without errors.

Here's error details
```
ld: library not found for -lReactNativeFFmpeg
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Here's my environment 

```
System:
  OS: macOS Mojave 10.14.5
  CPU: 1.7 GHz Intel Core i7
  Memory: 8GB 1600 MHz DDR3
  Shell: 3.2.57 - /bin/bash
Binaries:
  Node: 8.10.0 - /Users/username/.nvm/versions/node/v8.10.0/bin/node
  npm: 5.8.0 - /Users/username/.nvm/versions/node/v8.10.0/bin/npm
  Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
  iOS SDK:
    Platforms: iOS 12.3.1, macOS 10.14
IDEs:
  Xcode: 10.2.1 - /usr/bin/xcodebuild
npmPackages:
  react: 16.5.0 => 16.8.3
  react-native: 0.59.9 
```

Here's my Podfile:

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'MyApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PodcastNativeBase
  # pod 'React', :path => '../node_modules/react-native'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'cxxreact',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTWebSocket', # needed for debugging
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-ffmpeg/audio', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      targets_to_ignore = %w(React yoga)
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
    end
end
```

Could you give me a hint?

```
react-native-ffmpeg: 0.3.2
```

Thanks in advance.

**Comment by tanersener** [comment]
Most of the time, there is another error before `ld: library not found for -lReactNativeFFmpeg`. Do you have another error or warning before that?

Does `react-native run-ios` work for you?

**Comment by kouohhashi** [comment]
@tanersener 
Thank you for your response.

**react-native run-ios** gave me an error like below.
But i don't think this was something to do with react-native-ffmpeg...

```
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening PodcastNativeBase.xcworkspace
```

And when I used xcode run command, I got an error like this.
```
ld: warning: directory not found for option '-L/Users/myname/Desktop/aaaaa/PodcastNativeBase/ios/bbb/Build/Products/Debug-iphoneos/React'
ld: warning: directory not found for option '-L/Users/myname/Desktop/aaaaa/PodcastNativeBase/ios/bbb/Build/Products/Debug-iphoneos/yoga'
ld: library not found for -lReactNativeFFmpeg
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Do you think React and yoga is not compiled and linked properly?

Thanks in advance.

**Comment by tanersener** [comment]
I get similar errors when I forget to run `pod install`. Did you run `pod install` before `react-native run-ios`?

**Comment by kouohhashi** [comment]
@tanersener 
Thank you for your response.

I did. 
> I get similar errors when I forget to run `pod install`. Did you run `pod install` before `react-native run-ios`?

Actually it's working fine for Android.

**Comment by tanersener** [comment]
A lot of things can go wrong in `ios` builds. Can you check that you are opening your project's `.xcworkspace` file  in Xcode not `.xcodeproj`?

**Comment by kouohhashi** [comment]
I think my problem was caused by **react-native link commands** because after I created new project by **react-native init** and installed react-native-ffmpeg without using any **react-native link** command it worked.

Since I don't know how to install modules in Android without using react-native link command, I have another problem now but I think I can figure it out.

Anyway **react-native link** seem to create a problem if we use CocoaPod.

Thank you so much anyway!

Could you close the thread?

**Comment by tanersener** [comment]
I'm glad to hear your issue is resolved.
