### ISSUE TITLE
How to call two parallel ffmpeg.execute() at same time.

### ISSUE THREAD

**Issue by sagar789** [tanersener/react-native-ffmpeg#87]
How to call two parallel FFmpeg.execute() at the same time. or how can I call the second request after finish one because I have two or more compression in the queue.

If I call  FFmpeg.execute() in parallel or call before finish first one. React native is giving me this  "lldb rpc server crashed" error

Please help me out for this

#react-native-ffmpeg

**Comment by tanersener** [comment]
Unfortunately, parallel execution is not supported by the library. It is on the roadmap but I don't have an exact release date for it.

**Comment by sagar789** [comment]
Thank you for replying.
But for now, can you please help me for another solution, that I can achieve parallel or call in queue.

It would be appreciate
Thanks

**Comment by tanersener** [comment]
I'm using the following block to execute two sequential calls.

```
async function execute(command) {
    await RNFFmpeg.execute(command, " ").then(result => console.log("FFmpeg process exited with rc " + result.rc));
}

execute(command1).then(rc => {
    execute(command2);
});
```

**Comment by sagar789** [comment]
Thanks for sharing this solution.
If you have 10 commands then what will happen in this case.

I am asking this because I have more than 5 commands. How can I handle this

**Comment by tanersener** [comment]
You can build a recursive function, such as the `executeCommandAtIndex` function in the following example.

```
const commands = ["command 1", "command 2", "command 3", "command 4"];

executeCommandAtIndex = (index) => {
    if (index < commands.length) {
        execute(command[index]).then(rc => {
            this.executeCommandAtIndex(index + 1);
        });
    }
};

this.executeCommandAtIndex(0);
```
