### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by meraklis56** [tanersener/react-native-ffmpeg#88]
**Description**
When the file path includes whitespace, FFMpeg can not process the whitespace giving the "no such file or directory" error message

**Expected behavior**
It would be expected after using single/double quotes or replacing with "\ " and escaping it, would work.

**Current behavior**
Executing the command:

`-y -i /storage/emulated/0/viber/media/Viber\ Videos/video-ac98c32d51f4bfda518684efeb592318-V.mp4 -ss 00:00:01 -vframes 1 /data/user/0/<package>/cache/thumbnail.jpg`

it gives back an error message, shown in the Logs section.

**Logs**
07-09 11:48:53.305 32268 32587 I ReactNativeJS: ffmpeg version v4.2-dev-1156
07-09 11:48:53.305 32268 32587 I ReactNativeJS:
07-09 11:48:53.305 32268 32587 I ReactNativeJS:
07-09 11:48:53.305 32268 32587 I ReactNativeJS:
07-09 11:48:53.306 32268 32587 I ReactNativeJS:  Copyright (c) 2000-2019 the FFmpeg developers
07-09 11:48:53.306 32268 32587 I ReactNativeJS:
07-09 11:48:53.306 32268 32587 I ReactNativeJS:
07-09 11:48:53.306 32268 32587 I ReactNativeJS:
07-09 11:48:53.306 32268 32587 I ReactNativeJS:
07-09 11:48:53.306 32268 32587 I ReactNativeJS:
07-09 11:48:53.307 32268 32587 I ReactNativeJS:   built with Android (5058415 based on r339409) clang version 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec746213857d083c0e8b0abb568790) (https://android.googlesource.com/toolchain/llvm 7a6618d69e7e8111e1d49dc9e7813767c5ca756a) (based on LLVM 8.0.2svn)
07-09 11:48:53.307 32268 32587 I ReactNativeJS:
07-09 11:48:53.307 32268 32587 I ReactNativeJS:
07-09 11:48:53.307 32268 32587 I ReactNativeJS:   configuration: --cross-prefix=aarch64-linux-android- --sysroot=/files/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot --prefix=/home/taner/Projects/mobile-ffmpeg/prebuilt/android-arm64/ffmpeg --pkg-config=/usr/bin/pkg-config --enable-version3 --arch=aarch64 --cpu=armv8-a --cc=aarch64-linux-android24-clang --cxx=aarch64-linux-android24-clang++ --target-os=android --enable-neon --enable-asm --enable-inline-asm --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --enable-shared --disable-v4l2-m2m --disable-outdev=v4l2 --disable-outdev=fbdev --disable-indev=v4l2 --disable-indev=fbdev --enable-small --disable-openssl --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-static --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --disable-videotoolbox --disable-audiotoolbox --disable-appkit --disable-alsa --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-gmp --enable-gnutls --enable-libmp3lame --enable-libass --enable-iconv --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxml2 --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libshine --enable-libspeex --enable-libwavpack --enable-libkvazaar --enable-libilbc --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libaom --enable-libtwolame --disable-sdl2 --enable-zlib --enable-mediacodec
07-09 11:48:53.307 32268 32587 I ReactNativeJS:
07-09 11:48:53.308 32268 32587 I ReactNativeJS:
07-09 11:48:53.308 32268 32587 I ReactNativeJS:
07-09 11:48:53.308 32268 32587 I ReactNativeJS:   libavutil      56. 26.100 / 56. 26.100
07-09 11:48:53.308 32268 32587 I ReactNativeJS:
07-09 11:48:53.308 32268 32587 I ReactNativeJS:
07-09 11:48:53.308 32268 32587 I ReactNativeJS:
07-09 11:48:53.308 32268 32587 I ReactNativeJS:   libavcodec     58. 47.106 / 58. 47.106
07-09 11:48:53.308 32268 32587 I ReactNativeJS:
07-09 11:48:53.309 32268 32587 I ReactNativeJS:
07-09 11:48:53.309 32268 32587 I ReactNativeJS:
07-09 11:48:53.309 32268 32587 I ReactNativeJS:   libavformat    58. 26.101 / 58. 26.101
07-09 11:48:53.309 32268 32587 I ReactNativeJS:
07-09 11:48:53.309 32268 32587 I ReactNativeJS:
07-09 11:48:53.309 32268 32587 I ReactNativeJS:   libavdevice    58.  7.100 / 58.  7.100
07-09 11:48:53.309 32268 32587 I ReactNativeJS:
07-09 11:48:53.310 32268 32587 I ReactNativeJS:
07-09 11:48:53.310 32268 32587 I ReactNativeJS:   libavfilter     7. 48.100 /  7. 48.100
07-09 11:48:53.310 32268 32587 I ReactNativeJS:
07-09 11:48:53.310 32268 32587 I ReactNativeJS:
07-09 11:48:53.310 32268 32587 I ReactNativeJS:   libswscale      5.  4.100 /  5.  4.100
07-09 11:48:53.311 32268 32587 I ReactNativeJS:
07-09 11:48:53.311 32268 32587 I ReactNativeJS:
07-09 11:48:53.311 32268 32587 I ReactNativeJS:
07-09 11:48:53.311 32268 32587 I ReactNativeJS:   libswresample   3.  4.100 /  3.  4.100
07-09 11:48:53.311 32268 32587 I ReactNativeJS:
07-09 11:48:53.311 32268 32587 I ReactNativeJS:
07-09 11:48:53.311 32268 32587 I ReactNativeJS:
07-09 11:48:53.311 32268 32587 I ReactNativeJS: /storage/emulated/0/viber/media/Viber\: No such file or directory
07-09 11:48:53.312 32268 32587 I ReactNativeJS:
07-09 11:48:53.312 32268 32587 I ReactNativeJS:
07-09 11:48:53.312 32268 32587 I ReactNativeJS: Conversion failed!

**Environment**
    "react": "^16.8.6",
    "react-native": "^0.59.10",
    "react-native-ffmpeg": "^0.3.2",

**Comment by tanersener** [comment]
[Tips](https://github.com/tanersener/react-native-ffmpeg#6-tips) section in README explains the current behavior. Can you use one of the solutions posted there?

- You should not use double quotes (") to define your complex filters or map definitions.
    ```
     -filter_complex [0:v]scale=1280:-1[v] -map [v]
    ```

- If your commands include unnecessary quotes or space characters, your command will fail with `No such filter: ' '` errors. Please check your command and remove them.

- `execute` method is overloaded and has an optional delimiter parameter. Delimiter defines how the command string will be split into arguments.
When delimiter is not specified the space character is used as the default delimiter.
Based on this, if one or more of your command arguments include a space character, in filename path or in `-filter_complex` block, then your command string will be split into invalid arguments and execution will fail.
You can fix this error by splitting your command string into array yourself and calling `executeWithArguments` method or using a different delimiter character in your command string and specifying it in `execute` call.

**Comment by meraklis56** [comment]
Yes, with the RNFFmpeg.executeWithArguments i get no errors.
