### ISSUE TITLE
cannot run my app (gradle error)

### ISSUE THREAD

**Issue by 3bodyZZ** [tanersener/react-native-ffmpeg#97]
i have installed react native ffmpeg and i ran my project using command react-native run-android and i get this gradle error

`* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 24 declared in library [:react-native-ffmpeg] C:\Users\3bodyZZ\node_modules\react-native-ffmpeg\android\build\intermediates\library_manifest\debug\AndroidManifest.xml as the library might be using APIs not available in 16
        Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 24,
                or use tools:overrideLibrary="com.arthenica.reactnative" to force usage (may lead to runtime failures)`

what should i do ?

**Comment by tanersener** [comment]
> uses-sdk:minSdkVersion 16 cannot be smaller than version 24 declared in library [:react-native-ffmpeg] 

Can you try to understand what this log message says?

**Comment by 3bodyZZ** [comment]
> 
> 
> > uses-sdk:minSdkVersion 16 cannot be smaller than version 24 declared in library [:react-native-ffmpeg]
> 
> Can you try to understand what this log message says?

i don't understand it , I'm fairly new to react native

**Comment by 3bodyZZ** [comment]
> 
> 
> > uses-sdk:minSdkVersion 16 cannot be smaller than version 24 declared in library [:react-native-ffmpeg]
> 
> Can you try to understand what this log message says?

i have found a fix after one hour of searching , open build.gradle and change minsdk to 24
