### ISSUE TITLE
I have to run the function twice to get an output

### ISSUE THREAD

**Issue by 3bodyZZ** [tanersener/react-native-ffmpeg#98]
i have this function

`encrypt = () => {
  RNFFmpeg.executeWithArguments([
    "-i", this.state.uri.replace("file://",""),
    "-c:a", "aac",
    "-c:v", "mpeg4",
    "-encryption_scheme", "cenc-aes-ctr",
    "-encryption_key", this.state.key,
    "-encryption_kid", "a7e61c373e219033c21091fa607bf3b8",
    RNFS.TemporaryDirectoryPath + this.state.randomFileName + ".mp4"

    ])`
and i have a button that runs this function on press

the problem is i have to click that button twice to get an output

is this a bug in the library or i have done something wrong ?

platform : android
running on emulator

**Comment by tanersener** [comment]
How about replacing `RNFFmpeg` calls with `console.log` and seeing it yourself?

**Comment by 3bodyZZ** [comment]
> 
> 
> How about replacing `RNFFmpeg` calls with `console.log` and seeing if it is bug or not?

i did before posting here , the console logs fine but still need to run it twice to get an output file

**Comment by tanersener** [comment]
Did you check the last return code and the last command output after the first click? Maybe you've an error in your command which you don't know.

```
RNFFmpeg.getLastReturnCode().then(result => {
    console.log("Last return code: " + result.lastRc);
});

RNFFmpeg.getLastCommandOutput().then(result => {
    console.log("Last command output: " + result.lastCommandOutput);
});
```

**Comment by 3bodyZZ** [comment]
> 
> 
> Did you check the last return code and the last command output after the first click? Maybe you've an error in your command which you don't know.
> 
> ```
> RNFFmpeg.getLastReturnCode().then(result => {
>     console.log("Last return code: " + result.lastRc);
> });
> 
> RNFFmpeg.getLastCommandOutput().then(result => {
>     console.log("Last command output: " + result.lastCommandOutput);
> });
> ```

i just did, the last command output is empty and the last return code is 1, the command works fine after the second click i was able to decrypt and watch the video, weird

**Comment by tanersener** [comment]
> i just did, the last command output is empty and the last return code is 1

It means that you command fails. You need to understand why your command fails. Can you share your execution logs please?
