### ISSUE TITLE
ffmpeg functions make the app published to expo failed to open

### ISSUE THREAD

**Issue by toinyumi** [tanersener/react-native-ffmpeg#99]
**Description**
Init a new project using expo, then run `expo eject`, install the library through `npm` and setup android and ios linking
I'm using the package `https-lts` and expo sdk 33
Then I write an async function with `await RNFFmpeg.getFFmpegVersion()` in one component, build both android and ios projects, run `expo publish`

**Expected behavior**
The app should be able to open in expo client

**Current behavior**
"Unhandled JS Exception: Application main has not been registered"

**Screenshots**
Would provide on require

**Logs**
Would provide on require

**Environment**
"expo": "^33.0.0"
"expokit": "33.0.4"
"react": "16.8.3"
"react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz"
"react-native-ffmpeg": "^0.3.5"
react-native-ffmpeg package : `https-lts`

**Other**
Currently no

**Comment by tanersener** [comment]
It doesn't look like a `react-native-ffmpeg` issue. I don't use `expo` too much but I tested your case locally and it worked for me. I used the following `App.js` file. 

`Unhandled JS Exception: Application main has not been registered` error message sounds like a linking error. I recommend reading the README and using the correct steps to link `react-native-ffmpeg`.

```
import React, { Component } from 'react';
import {Text, TouchableOpacity, View} from 'react-native';
import {RNFFmpeg} from 'react-native-ffmpeg';

async function testVersion() {
    await RNFFmpeg.getFFmpegVersion().then(rc => {
        console.log('RC is ' + rc.version);
    });
}

export default class HelloWorldApp extends Component {
    run = () => {
        testVersion();
    };

    render() {
    return (
        <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
            <Text>Hello, world!</Text>
            <TouchableOpacity style={{backgroundColor: 'red', padding: 30, margin: 40}}
                              onPress={this.run}>
                <Text>RUN</Text>
            </TouchableOpacity>
        </View>
    );
  }
}
```

**Comment by toinyumi** [comment]
Did you try this by publishing the app to expo and run the app through the expo client app?

**Comment by tanersener** [comment]
Applications can't use `expo client app` after `expo eject`. Are you sure you are trying something valid?

Please see [Ejecting to ExpoKit](https://docs.expo.io/versions/latest/expokit/eject/) documentation.
> We call this "ejecting" because you still depend on the Expo SDK, but your project no longer lives inside the standard Expo client. You control the native projects, including configuring and building them yourself.
